### ISSUE TITLE
Elide 5.0 - SQLQueryEngine: Fix Sorting on AggregationMetric

### ISSUE THREAD

**Issue by hellohanchen** [yahoo/elide#1023]
When sorting is applied on a metric aggregation, we should expect the generated SQL to be
```SQL
ORDER BY aggregation_expression( field_name )
```
But currently it is only generating
```SQL
ORDER BY field_name
```
Which is not correct.

## Possible Solution
Fix `extractOrderBy()` in `SQLQueryEngine`
And add test

**Comment by chczy** [comment]
Merged.
