### ISSUE TITLE
Elide 5.0 - SQLQueryEngine: Sorting by id should be prohibited

### ISSUE THREAD

**Issue by hellohanchen** [yahoo/elide#1024]
When SQLQueryEngine generates an aggregation query, it would not fetch the **id** field because that's meaningless and the ids are generated in-memory after aggregated results return. So we don't actually query **id** in the aggregation query and that prevent user from sorting on **id** field.

## Expected Behavior
Check sorting clause on id and reject or ignore it.

## Current Behavior
No checks for this situation, the query would fail as **id** is not defined in the query.

## Solution
Fix the issue and add test cases

**Comment by chczy** [comment]
Merged.
