### ISSUE TITLE
Elide 5.0 - SQLQueryEngine: Add join clause for attributes in having clause

### ISSUE THREAD

**Issue by hellohanchen** [yahoo/elide#1027]
When QueryEngine splits a query's original filter expression into where clause and having clause, it would do **where clause promotion** in some cases which pushes all where clause into having clause. For example
```
WHERE a OR HAVING b
```
to be 
```
HAVING a OR b
```
If `WHERE a` is a where clause that require joins, after it is pushed into having clause, the joins would not happen as `toSQL` method currently doesn't create joins for having clause.

## Solution
Fix the issue and add test cases

**Comment by chczy** [comment]
This issue is closed as the PR is already merge.
