### ISSUE TITLE
Elide 5.0 - SQLQueryEngine: Ambiguous table aliases

### ISSUE THREAD

**Issue by hellohanchen** [yahoo/elide#1053]
Ambiguous table aliases from `SQLQueryEngine.toSQL()`.

## Expected Behavior
No ambiguity generated.

## Current Behavior
Currently, in `SQLQueryEngine.toSQL()` method, we are generating table aliases based on class name only, this would cause ambiguity when we have a relationship like `tb1.country.country`. As **country** shows up twice in this query, the generated aliases would be ambiguous.

## Possible Solution
Maybe the table alias should contain the information from the path like *user.country*, such as 
```SQL
select * from user join country AS user_country ON ...
```
There are multiple solutions we can try.

## Testing
Add data model that would cause ambiguity and make unit tests and integration tests for it.

**Comment by chczy** [comment]
Merged.
