### ISSUE TITLE
Objects returned from AggregationDataStore need to support aliased attributes.

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#1056]
GraphQL supports aliases and the ability to request the same field multiple times.  
In the AggregationDataStore, a metric can be requested multiple times with different aliases.

Elide relies on the data store to hydrate concrete implementations of the model object.   The API response is serialized from the hydrated model object.    Because all metrics in the aggregation data store are evaluated before response serialization, Elide will overwrite one of the metric values when it hydrates the object model instance.

## Possible Solution
Entities which represent `AnalyticViews` can be required to implement a new abstract class:

```java
public abstract class AnalyticViewInstance  {
    //Generalize ID handling.
    @Id
    private int id;
   
    @Exclude
    private Map<String, Object> aliasMap = new HashMap<>();

    public Object getFieldByAlias(String alias) {
        return aliasMap.get(alias);
    }
}
```

Implementations of `AnalyticViewInstance` can store the metric and dimension values by their alias names.  

The AggregationDataStore can then implement `getAttribute` which either:
1. Sources the value of an attribute or relationship from the entity if the alias matches the name of the attribute or relationship.
2. Sources the value of an attribute or relationship from the AnalyticViewInstance map if the alias does not match the name of the attribute or relationship.

JSON-API does not support aliases - so all JSON-API queries will take the first path.  GraphQL will either take the first or second path depending on whether an alias is present in the query.

The `AbstractEntityHydrator` will be responsible for both hydrating the entity as well as populating the `AnalyticViewInstance` map.

**Comment by chczy** [comment]
The `ColumnProjection` interface in aggregation data store is already using Alias to project columns. But if we want to support alias projection, we should also figure out how to use alias in filters and sortings.

**Comment by aklish** [comment]
This has been implemented.
