### ISSUE TITLE
POST to To-One not returning relationships

### ISSUE THREAD

**Issue by DennisMcWherter** [yahoo/elide#109]
I noticed that `POST`ing to To-One relationships does not return the parent reverse relationship (on bi-directional) to the user. When running a `GET`, this does work properly and the relationship exists. Need to investigate further and ensure this doesn't occur for other types of `POST` as well.

**Comment by aklish** [comment]
Closing - old bug and not valid.  Elide returns a 204:

https://jsonapi.org/format/#crud-updating-relationship-responses-204
