### ISSUE TITLE
Use Spring Boot dependency managements versions rather than specific versions

### ISSUE THREAD

**Issue by snicoll** [yahoo/elide#1116]
It would be more consistent to use Spring Boot's dependency management in `elide-spring` at the very least. Right now the Spring Boot version is specified in both modules and reuses an specific Jetty version.

Spring Boot users adding the starter are more likely to use its dependency management and therefore the version that Spring Boot promotes. It would be better if tests were running against that arrangement.

One way would be to add the following to `elide-spring`

```xml
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-dependencies</artifactId>
			<version>${spring.boot.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```

alongside

```
<properties>
	...
	<spring.boot.version>2.2.2.RELEASE</spring.boot.version>
</properties>
```

and then remove all the versions that Spring Boot provides.

**Comment by aklish** [comment]
Thanks.  That's good feedback.  Will add it to our next sprint.
