### ISSUE TITLE
Add MEMBER OF Operation 

### ISSUE THREAD

**Issue by Chandrasekar-Rajasekar** [yahoo/elide#1197]
Elide should support MEMBER OF operation to check if a value is a member of the specified collection.

## Expected Behavior
Member of operation should work only on Collection attributes. We do not support the relationship.
-->`filter=book.awards=hasmember='Booker Prize'`
-->`filter=book.awards=hasnomember='Hugo Award'`

## Possible Solution
Should replicate hibernate behavior.
https://docs.oracle.com/html/E13946_04/ejb3_langref.html#ejb3_langref_collection_member

**Comment by bukajsytlos** [comment]
doesn't `filter=book.awards.name=='Booker Prize'` achieve what you want?
