### ISSUE TITLE
Support overriding how GraphQL types are named

### ISSUE THREAD

**Issue by DanyBv** [yahoo/elide#1209]
Apollo-android is a library that generates a client from GraphQL queries. 
It builds the java model according to the name of the types in the GraphQL schema.
Some names from a schema created by Elide can have this format: my_package_MyEnum.
This will result in classes generated for the client that do not respect the java naming conventions.

## Possible Solution
Support overriding how GraphQL types are named.

**Comment by DanyBv** [comment]
Let me know if you want me to work on this feature.
Here is working prototype to make this feature available: 
https://github.com/DanyBv/elide/commit/f5837a20cff4278e66b455d100d7452a10378109

**Comment by aklish** [comment]
This seems like this would be a really useful capability.  I'd be happy to review a submission if you want to take up the issue.

I did look at the prototype.  My only comment is that I'm wondering if annotations will become burdensome - and maybe a global approach might be better?  

In that case, maybe we can support a registration function that can be overwritten.

For elide 5.0, we could also change the default behavior to be something compatible with the library (so there is no need to register anything).

Thoughts?

**Comment by DanyBv** [comment]
I think all three can be part of the solution.
Elide could work with apollo-android out of the box.
Developers could provide their own logic for naming types.
And in case of name collision or for any other reason an annotation is provided to override the name.
What do you think?

**Comment by DanyBv** [comment]
The more I think about it, the less new annotations seem like a good idea. `@Include (type = "...")` already exists to rename a type if necessary so I don't think adding other annotations would bring any real benefit.

**Comment by aklish** [comment]
I think minimally, we should change Elide 5 to have a more friendly naming schema for types that mirror the Apollo library you are using.

Elide 5. is probably 1-2 months from release (best guesstimate).  In the meantime, I think a static method that lets someone override the naming scheme seems like it could help.

**Comment by DanyBv** [comment]
Here is an example where it is possible to modify the way in which the types are named in GraphQL:
https://github.com/DanyBv/elide/commit/81e4d7c0289e0b4e2762b7697845e92229a35c54
I wonder if this feature will really be used. I am thinking of making a more minimal version where the names of the schema respect the naming conventions of java without the naming strategy and which will only target the 5.x version of Elide.

**Comment by DanyBv** [comment]
Here is the minimal version:
https://github.com/DanyBv/elide/commit/74be8cfd0097d8f1c55367771c103f22b5561519
Tell me which one you prefer. I will test it and send a pull request.

**Comment by aklish** [comment]
Thanks for submitting both of them.  My guess is probably the minimal one will suffice.  I'm not sure if there would be more naming problems with other languages & tools.  My guess is Java naming is likely sufficient.
