### ISSUE TITLE
Cross-Site Scripting: Reflected

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [yahoo/elide#1211]
https://github.com/yahoo/elide/blob/680606834ce4058c0af5aabb78ce6f09583b35e3/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/SwaggerController.java#L84

https://github.com/yahoo/elide/blob/680606834ce4058c0af5aabb78ce6f09583b35e3/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/SwaggerController.java#L89

Sending unvalidated data to a web browser can result in the browser executing malicious code.

**Comment by aklish** [comment]
Fixed in #1221
