### ISSUE TITLE
[Exclude annotation] Potential bug - probably its not working on relationships

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#1219]
`@Exclude` is working on fields but not on relationships even though the [relevant issue](https://github.com/yahoo/elide/pull/217) was resolved a few years back.

## Expected Behavior
@Exclude to work on relationships

## Current Behavior
`@Exclude` is working on fields but not on relationships. Exception InvalidCollectionException is thrown.
`@JsonIgnore` is not working either.

## Steps to Reproduce (for bugs)
1. Create 2 models: Customer and Shop that have one-to-many relationship. Placed `@Exclude` on customer.shops
2. Start app and create a customer via POST /customer
3. Create a Shop via POST /customer/{customerId}/shops
4. InvalidCollectionException is thrown

## Your Environment
* Elide version used: 4.5.9 (not tested with the latest one)
* Environment name and version (Java 1.8.0_202):
* Operating System and version: MacOS
* Link to your project: [1st commit of this sample project](https://github.com/thaingo/elide-issue)

Thanks,
Thai

**Comment by aklish** [comment]
Thanks for filing the issue.  I checked the sample project but didn't see `@Exclude` on either of the models.  

In your example, was it on customer.shops?  

What did you expect the behavior to be in the steps to reproduce?  Thanks.

**Comment by thaingo** [comment]
Since  you checked the sample project, could you please switch to the 1st commit like mentioned above? In that example, @`Exclude` was on customer.shops

Thanks for your time.

**Comment by aklish** [comment]
What is the behavior you are expecting?

I would expect creating a Shop via POST /customer/{customerId}/shops
would throw an InvalidCollectionException because customer.shops doesn't exist in the exposed model.

**Comment by thaingo** [comment]
I am expecting that `@Exclude` allows the relationship to be ignored but to exist in the underlying persistence layer so that developer can choose when to show or hide it on demand. 

As you already confirmed the expected behavior, I now understand that.

Is there a similar way in Elide that I can use to expect a similar function like Jackson `@JsonIgnore`?

Thanks.

**Comment by aklish** [comment]
`@Exclude` on an attribute or relationship removes that attribute or relationship from the API.  However, it is still persisted (the ORM still knows about it). 

I'm not sure what you mean by "show or hide on demand".

**Comment by thaingo** [comment]
Given the context (the relationship between these 2 models), show or hide on-demand means backend developer will use `@Exclude`, for example, on `customer.shops` when he does not want to include `shops` in response to clients but he still wants to allow clients to do operations on `shop` like create a shop for a given customer, update that shop and so on. 

But `@Exclude` is not working that way. Of course, `sparse fields` can help in this case but then it is up to clients to specify fields they need in request or we have to enforce them somehow.

Thanks.
