### ISSUE TITLE
Incorrect pagination with ToMany filtering

### ISSUE THREAD

**Issue by bukajsytlos** [yahoo/elide#1244]
## Expected Behavior
When issuing query with filter on ToMany relationship and pagination should return correct number of results vs page size

## Current Behavior
When issuing query with filter on ToMany relationship and pagination,
then resulting product of join vs distinct rows differs resulting in broken pagination

## Possible Solution
distinct should be applied in this case

## Your Environment

* Elide version used: 4.5.14
* Environment name and version (Java 11.0.2):
* Operating System and version:
* Link to your project: https://github.com/FAForever/faf-java-api/issues/338

**Comment by bukajsytlos** [comment]
I fixed this (will push tomorrow) by applying distinct in com.yahoo.elide.core.hibernate.hql.RootCollectionFetchQueryBuilder#build
when there is ToMany in FilterExpression.
Not sure if this should be applied somewhere else (com.yahoo.elide.core.hibernate.hql.SubCollectionFetchQueryBuilder)?

**Comment by aklish** [comment]
Sounds good.  Send the push and I'll take a look.
