### ISSUE TITLE
RFC: Download Async Query Result

### ISSUE THREAD

**Issue by moizarafat** [yahoo/elide#1272]
# Overview
Elide will support the downloading of the results of the async query execution. 

Also, the current implementation stores the results in a database table. This will work if the results are not too large. If the result size is large, it may be better to store the results in different storage like a filesystem, S3.  

## Supported Download Formats
The following formats will be supported.
- JSON (Already supported)
- CSV
- ~~TSV~~ (Not Needed for MVP)
- ~~XLSX~~ (Not Needed for MVP)

For JSON to CSV conversion, we can use jackson-dataformats-text library, earlier known as jackson-dataformat-csv. 

## Record Count filter
The MVP requirement says it should allow up to 10K records but for the long term it should be scalable. At this point, I don't see a reason to put in any limitations of 10K right now, we can go ahead and stream back all the records. 

## Supported Storage
Elide will have in-built support to store the results in a database table. But can be expanded to any other storage.

## ResultStorageEngine Interface
A new ResultStorageEngine Interface will be created. The interface will have methods:
- Store the results.  should return the URL to the results.
- retrieve the results by id 
- delete the results by id
- delete all the results 
- access permission check //Only the original requester can retrieve the results. No update/delete allowed to users.

### DatabaseResultStorageEngine
Elide will come in-built with a default implementation of ResultStorageEngine Interface, which will store/retrieve the results in a database table. 

A new Entity will be created for storing the results.  This will be used only for the default Implementation case (Database). **So no relationship with AsyncQueryResult established.**

```java
@Exclude //We don't want this to be exposed through the standard Elide APIs. 
@Entity
@Data 
public class asyncQueryResultStorage {
    @Id
    @Column(columnDefinition="varchar(36)")
    private UUID id; //Matches UUID in query.
    
    private java.sql.Blob result; // To allow expansion to XLSX? 
}

public enum ResultFormatType {
    JSON,
    CSV
}
```
Existing Model to be updated: 

``` java
@Embeddable
@Data
public class AsyncQueryResult extends AsyncBase  {
    private Integer contentLength;

    private Integer recordCount; // New Column to be added. No of records in the final result

    ResultType resultType; //EMBEDDED, DOWNLOAD
    String result;  //URL or Response body
    private Integer status; // HTTP Status
    Date completedOn; 

}

@Entity
@Include(type = "asyncQuery", rootLevel = true)
@ReadPermission(expression = "Principal is Owner")
@UpdatePermission(expression = "Prefab.Role.None")
@DeletePermission(expression = "Prefab.Role.None")
@Data
public class AsyncQuery extends AsyncBase implements PrincipalOwned {
    
   private ResultFormatType resultFormatType; //New Column to be added. JSON, CSV
   
   // Remaining attributes in the model remain as-is
}
```
## AsyncQueryDAO 
Enhancements to AsyncQueryDAO to include the clean up for the QueryResultStorage. Apart from cleaning the AsyncQuery table, AsyncCleanerService should clean up the ResultStorage by calling appropriate methods from ResultStorageEngine. 

## ResultDownload Controller
A new controller will be created with the following mappings:
- /asyncQueryResultStore/{id}  - Results will be streamed based on result format provided at run time. Response.Type will be set accordingly as well.                
- ~~/asyncQueryResultStore/{id}/download-Default Format JSON~~ 
- ~~/asyncQueryResultStore/{id}/download/{format}-Other formats~~ 

 ## Deliberation Points
1. Formatting data on the fly may potentially slow the response.
    * Should we pre-format the data to a supplied/selected format during execution or allow the user to select format when clicking the download button? - Yes, Preformat based on input.
    * ~~If the data is pre-formatted before storing and how will the UI render work with different formats like xlsx?~~ 
2. Should the click on the download button return a link to download for later or it needs to return an attachment to download?
    * When working with S3 or any other cloud file system, they might just want to return a URL to the S3 path instead.
    * Security considerations -  if a download URL is provided. Should anyone with the URL be able they be able to download the data?
    * Attachment generation could take a few seconds/minutes depending on the records count.
3. Do we want to limit the results when downloading and also for UI rendering? - MVP suggests upto 10K records but should be scalable beyond that.

**Comment by aklish** [comment]
A couple of thoughts:

1. I think the download (resultStorage) should be a URL rather than a String
2. Interesting idea to support download in different formats, but I wonder if we should simply store the result in the requested format.  For engines like S3, Elide won't be involved at all in the download then.  
3. For really large formats, I think streaming is important - so modeling as an Elide entity might not be the best approach. 
4. For security, generating a sufficiently large identifier in the URL should be sufficient to protect the download in many/most cases.   Restricting the download further (by the requester) can also be done but definitely requires a proxy then (no direct download from S3).

**Comment by moizarafat** [comment]
> A couple of thoughts:
> 
> 1. I think the download (resultStorage) should be a URL rather than a String
> 2. Interesting idea to support download in different formats, but I wonder if we should simply store the result in the requested format.  For engines like S3, Elide won't be involved at all in the download then.
> 3. For really large formats, I think streaming is important - so modeling as an Elide entity might not be the best approach.
> 4. For security, generating a sufficiently large identifier in the URL should be sufficient to protect the download in many/most cases.   Restricting the download further (by the requester) can also be done but definitely requires a proxy then (no direct download from S3).

i) For the first comment above, now in AsyncQueryResult we store the URL resultURL. the URL will be pointing to a new Download Controller, /asyncQueryResultStore/{id} . So users can hit that URL and we will stream the data back through the end-point.
ii) We will pre-format the data based on input and store. Now the async request takes the additional option of the required format.
iii) We are marking the new table to store the results with `@Exclude` so it will not be available through Elide. Also, this model will be only created when we have the default implementation of ResultStorageEngine. We can override this to go to any Filesystem by providing our own implmentation.
iv) The URL will have UUID which will be unguessable in some way. And as per the new MVP requirements, the URL should be shareable so no permissions will be checked.
