### ISSUE TITLE
How to Manage API Versioning which supports both JSON-API and GraphQL spec. 

### ISSUE THREAD

**Issue by rsrini7** [yahoo/elide#1274]
How to apply in generic way of versioning api which supports both spec with "Best Practice" and "Example". 

Open Issue in Json-Api Spec : https://github.com/json-api/json-api/issues/406

Can we have custom annotations with version specific fields to be filtered based on Media Type Versioning / Custom Header / URI ?

Thanks in advance.

**Comment by aklish** [comment]
Yes to this.  I think this is a _must_ have feature.  I'll write up an RFC for I how I think this ought to work - and we should prioritize this for Elide 5.0 (probably doing this correctly will break the API contract).

A couple of initial thoughts:
1.  I think the versioning ought to apply at the entity level (as opposed to field).
2. Version will likely will be a mandatory attribute in the `@Include` annotation.
3. Probably best practice here is to create models with the same name but belonging to different versioned packages.
4. Version will be baked into the URL for all Elide controllers and JAX-RS endpoints.

I think most of the version challenges happen around making structural changes to the entity relationship graph.
