### ISSUE TITLE
Patch Extension handling attribute updates

### ISSUE THREAD

**Issue by duseja2** [yahoo/elide#136]
Refer to "Updating attributes" section at http://jsonapi.org/extensions/jsonpatch/
Currently elide expects the "value" parameter to contain data in the form of JsonApiDocument, but we should also allow individual attribute updates by accepting simple string, int, boolean, etc in the "value" parameter as per the JsonApi spec.

**Comment by aklish** [comment]
As the patch extension is deprecated in JSON-API, we will not be making any changes to it.
