### ISSUE TITLE
JSONAPI Swagger filtering using the wrong dialect.

### ISSUE THREAD

**Issue by whgibbo** [yahoo/elide#1362]
I'm new to using the **elide-spring-boot-starter** and noticed it provides swagger documentation.
However that the documentation seems to use an older dialect and not the RSQL dialect.

## Expected Behavior
That the swagger documentation should display the RSQL dialect, but appears to be displaying the old dialect.

## Current Behavior
![image](https://user-images.githubusercontent.com/8224638/83419292-c6d35680-a41c-11ea-9e89-ece15b10d8ed.png)
As you can see from the screen it is displaying the old dialect and when you use the dialect displayed on swagger, it reports an error.

## Steps to Reproduce
1. Check out the example and build
2. Run the application
3. Go to the swagger documentation and pick a filter example
4. Then attempt to apply the filter, which files.
5. Try RSQL filter and it works. 

## Your Environment
* Elide version used: **4.6.4**
* Java version:  **1.8.0_232**
* Operating System and version: **Windows**

**Comment by aklish** [comment]
The logic currently is showing both the old dialect and RSQL:

```java
            /* Add RSQL Disjoint Filter Query Param */
            params.add(new QueryParameter()
                    .type("string")
                    .name("filter[" + typeName + "]")
                    .description("Filters the collection of " + typeName + " using a 'disjoint' RSQL expression"));

            if (lineage.isEmpty()) {
                 /* Add RSQL Joined Filter Query Param */
                params.add(new QueryParameter()
                        .type("string")
                        .name("filter")
                        .description("Filters the collection of " + typeName + " using a 'joined' RSQL expression"));
            }

            for (Operator op : filterOperators) {
                attributeNames.forEach((name) -> {
                    Class<?> attributeClass = dictionary.getType(type, name);

                    /* Only filter attributes that can be assigned to strings or primitives */
                    if (attributeClass.isPrimitive() || String.class.isAssignableFrom(attributeClass)) {
                        params.add(new QueryParameter()
                                .type("string")
                                .name("filter[" + typeName + "." + name + "][" + op.getNotation() + "]")
                                .description("Filters the collection of " + typeName + " by the attribute "
                                        + name + " " + "using the operator " + op.getNotation()));
                    }
                });
            }
```

However, it probably should disable the filter options for dialects that are not in use.  

Just to clarify the issue, are you looking for the swagger docs to disable the old dialect filter options?

**Comment by whgibbo** [comment]
I think the swagger documentation should show only the dialect(s) being supported.  So yes it should only display one..
