### ISSUE TITLE
Datastore transaction and Sorting

### ISSUE THREAD

**Issue by whgibbo** [yahoo/elide#1370]
I'm using a custom data source, so have been using the DataStore and DataStoreTransaction interfaces to create interface with it.. Which is coming along..

But have a few questions regarding the Sorting.
1. The [Sorting](https://javadoc.io/doc/com.yahoo.elide/elide-core/4.6.4/com/yahoo/elide/core/sort/Sorting.html) instance past does **not** appear to have a method to retrieve the parsed sorting criteria.  Was wondering if there was a reason or if I'm missing something.

2. Is there an annotation that I can put on the data model class to disable sorting for particular attributes, or a hook to check if the sort filters are permitted?

**Comment by whgibbo** [comment]
For point 1, would it be acceptable to raise a pull request for this ?

**Comment by aklish** [comment]
For 1:
In elide 5, the method is:
```java
    /**
     * Return an ordered map of paths and their sort order.
     * @param <T> The type to sort.
     * @return An ordered map of paths and their sort order.
     */
    public <T> Map<Path, SortOrder> getSortingPaths();
```

For Elide 4, this is the method:
```
    public <T> Map<Path, SortOrder> getValidSortingRules(final Class<T> entityClass,
                                                         final EntityDictionary dictionary)
```

Sorting is one of the interfaces that needs rework - hence the cleanup in 5. 

What did you have in mind?

**Comment by aklish** [comment]
For 2, 

The DataStoreTransaction has the following method:

```java
    /**
     * Whether or not the transaction can sort the provided class.
     * @param entityClass
     * @return true if sorting is possible
     */
    default boolean supportsSorting(Class<?> entityClass, Sorting sorting) {
        return true;
    }
```

A custom store can decide which entities it supports sorting on.  However, Elide will attempt to sort in memory if the store doesn't support sorting.  There is no way to turn it off altogether (like there is for pagination).

A new annotation to disable sorting altogether would be a nice addition.

**Comment by whgibbo** [comment]
So for:

1.  **Sorting** contains the sort criteria requested ( in the sortRules member).  However there is no method to retrieve it so that they can be validated in the sort term.  For the time being I'm using reflection to obtain it, which isn't ideal.

2. Whilst the **supportsSorting** method on the DataStoreTransaction looks promising its the same issue, how to retrieve the fieldnames from Sorting..  Which is why I was looking for the method to retrieve the rules..

I think having an new annotation to indicate if the field can or cannot be used in the sort query would be good.  This means that Swagger module can then take advantage of it.

For those that don't want to use annotations, then exposing the a method to retrieve the sortRules would be useful.  Something like this.
```
public Map<String, SortOrder> getSortRules() {
   return ImmutableMap.copyOf(sortRules);
}
```

**Comment by aklish** [comment]
This is resolved in latest elide 5 (now master).  supportsSorting now takes RequestScope.
