### ISSUE TITLE
Elide 5.0 - 2 SQLs fired when creating an entity instance. 

### ISSUE THREAD

**Issue by moizarafat** [yahoo/elide#1397]
Currently while creating an entity instance with a pre-commit hook, it runs an insert SQL and an update SQL. 

Detail discussion on Spectrum. https://spectrum.chat/elide/general/life-cycle-hook-execution~5982e92a-a84f-4b64-877a-083eb59cd53e 

## Expected Behavior
Instead of the 2 SQLs, we should fire 1 SQL.

-->

## Current Behavior
2 SQLs are fired, 1 insert and 1 update, because we run a flush before commit.

-->

## Possible Solution
Introduce a pre-flush hook for updating the entities before the flush.

## Steps to Reproduce (for bugs)
1. https://spectrum.chat/elide/general/life-cycle-hook-execution~5982e92a-a84f-4b64-877a-083eb59cd53e

## Context
https://spectrum.chat/elide/general/life-cycle-hook-execution~5982e92a-a84f-4b64-877a-083eb59cd53e

## Your Environment
https://spectrum.chat/elide/general/life-cycle-hook-execution~5982e92a-a84f-4b64-877a-083eb59cd53e

**Comment by thaingo** [comment]
@moizarafat The issue happens as well when updating an entity instance.

```
10-07-2020 15:53:52.858 [task-12] DEBUG org.hibernate.SQL.logStatement - select company0_.id as id1_6_0_, company0_.createdBy as createdb3_6_0_, company0_.createdDate as createdd5_6_0_, company0_.lastModifiedBy as lastmodi6_6_0_, company0_.lastModifiedDate as lastmodi7_6_0_, company0_.address as address9_6_0_, company0_.description as descrip16_6_0_, company0_.email as email17_6_0, company0_.manager as manager4_6_0_, company0_.staff as staff21_6_0_ where (company0_.staff in (?) or company0_.manager in (?)) and (company0_.id in (?))
10-07-2020 15:53:52.859 [task-12] DEBUG org.hibernate.SQL.logStatement - update company set createdBy=?, createdDate=?, lastModifiedBy=?, lastModifiedDate=?, address=?, description=?, email=?, industry=?, ltv=?, manager=?, phone=?, staff=? where id=?
10-07-2020 15:53:52.860 [task-12] DEBUG org.hibernate.SQL.logStatement - update company set createdBy=?, createdDate=?, lastModifiedBy=?, lastModifiedDate=?, address=?, description=?, email=?, industry=?, ltv=?, manager=?, phone=?, staff=? where id=?
0:0:0:0:0:0:0:1 - 0908592998 [10/Jul/2020:15:53:52 +0700] "PATCH /api/v1/company/suno HTTP/1.1" 204 0
```
