### ISSUE TITLE
POST, PATCH, DELETE operations do not make query parameters available from request scope.

### ISSUE THREAD

**Issue by gmckerrell** [yahoo/elide#1410]
Currently query parameters are **only** put into the request scope for GET operations.

## Expected Behavior
query parameters passed in for POST,PATCH and DELETE requests should be processed and made available in the request scope if present.
```java
    scope.getLoadFilterExpression(Foobar.class) // provides value
```

## Current Behavior
only GET requests provide 
```java
    scope.getLoadFilterExpression(Foobar.class) // Optional.empty()
```

## Possible Solution
Update `Elide.java` to provide queryParam variants of the post(), patch() and delete() methods.

## Context
We have a usage scenario where we need to bulk update a large number of entities. (in the region of thousands) To accomplish this we have some "virtual" entities which each map down to an underlying set of real entities which are defined by a filter expression. In our case we map through to an elastic search expression and perform the bulk update.

Currently we have had to derive our own Elide instance which passes down the query parameters for non-GET operations, but it would be better if query parameter support was provided native in the library.

## Your Environment
* Elide version used: Elide 4.6.5
* Environment name and version (Java 1.8.0_152): spring-boot/JDK-11

**Comment by thaingo** [comment]
@gmckerrell I am curious about this. Could you please share more details of the use-case you are talking about and how these query params are benefit to you?

Thanks.

**Comment by gmckerrell** [comment]
Hi @thaingo

We have a use-case with a set of many thousands of entities in a particular collection (similar to a ticketing system)

In order to deal with these entries, our user will filter down the set to those tickets in which they are interested. e.g. they may only be interested in tickets with a particular severity between these dates and assigned to a particular engineer. The mechanism by which this is filtered down is the normal query parameter `filter[]` type syntax.

This works well for read-only collections (using GET) however when a bulk edit is required, it is not practical to pass thousands of entity updates in a single request.

Our solution is to invent an entity that represented a "bulk job" related to the ticket collection. We create an instance of this by POSTing a body containing the deltas that need to be applied to a sub-set of tickets, and that sub-set is defined by the `filter` queryParameters.

As these are the same parameters used to filter down the customer's original view of the system, they are readily available to the UI to use when making a bulk update.

On our backend this all gets translated into an elastic search request, that applies the changes to the specified sub-set of entries.

Currently we perform the update synchronously, only returning from the POST when the persistence layer has completed, but the model we have chosen would also adapt to an asynchronous situation, where the "bulk job" entity represents the update process running in the background. It could be queried to monitor how far it has progressed, and could be used to cancel/revert the changes.

Hope this makes it clearer how the query parameters can be used to provide a specific context when dealing with large collection sets.

**Comment by thaingo** [comment]
Thanks a lot @gmckerrell. It is clear now. Interesting approach!

I do have a similar use-case but I took a different approach - emitting an event per delta to a queue from which bulk job is executed.
