### ISSUE TITLE
Provide mechanism to override Elide provided Serdes

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#1421]
Elide provides a number of Serdes (type serializer/deserializers) out of the box.   These Serdes are found and registered by scanning for the ElideTypeConverter annotation.

There is no mechanism in Elide to override these default Serdes.

## Expected Behavior

Elide should give precedence to Serdes outside the `com.yahoo.elide` package namespace when registering a new Serde.

**Comment by edu-chk** [comment]
Hello devs,
any update on this one? to me it looks like a pretty critical to have such a feature.

**Comment by aklish** [comment]
There are two options:

1. There is a workaround where you can manually register your Serde after the Elide object is created by calling `CoerceUtil.register`.   This will replace an existing Serde with one of your choosing.  You can do this in Spring Boot anytime after this bean is created: https://github.com/yahoo/elide/blob/master/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java#L168Sup
2. Submit a PR to resolve this issue by:
  - Removing the `ElideTypeConverter` annotation from any Serde in the com.yahoo.elide.core.utils.coerce package (so Elide will not scan for them).
  - Registering the Elide Serdes from the previous step (by calling CoerceUtil.register) in ElideSettingsBuilder here: https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/ElideSettingsBuilder.java#L95
 
If you opt for option 2, I will make it a priority to get it released.

**Comment by edu-chk** [comment]
Thanks,
if I go with a PR option, I would like to clarify one thing. On a line
https://github.com/yahoo/elide/blob/c3d71ad98a89137ed78e86deb091897836203f75/elide-core/src/main/java/com/yahoo/elide/Elide.java#L117
when it registers annotation marked serdes it also registers them in an object mapper
https://github.com/yahoo/elide/blob/c3d71ad98a89137ed78e86deb091897836203f75/elide-core/src/main/java/com/yahoo/elide/Elide.java#L132
should I also perform this action for ootb serdes? Since for now this is also happens for ootb serdes as well.

**Comment by aklish** [comment]
> Thanks,
> if I go with a PR option, I would like to clarify one thing. On a line
> https://github.com/yahoo/elide/blob/c3d71ad98a89137ed78e86deb091897836203f75/elide-core/src/main/java/com/yahoo/elide/Elide.java#L117
> 
> 
> when it registers annotation marked serdes it also registers them in an object mapper
> https://github.com/yahoo/elide/blob/c3d71ad98a89137ed78e86deb091897836203f75/elide-core/src/main/java/com/yahoo/elide/Elide.java#L132
> 
> 
> should I also perform this action for ootb serdes? Since for now this happens for ootb serdes as well.

Yes.

**Comment by aklish** [comment]
Release will be this Friday.
