### ISSUE TITLE
Elide data stores should not run page total query if results from data load return no records.

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#1428]
## Expected Behavior
Elide should validate results of security checks before performing pagination

## Current Behavior
Elide always performs query `select count(distinct ...) `regardless of results of security checks.

```
10-07-2020 19:13:59.553 [task-11] DEBUG org.hibernate.SQL.logStatement - select count(distinct account0_.id) as col_0_0_ from Account ... where ...
10-07-2020 19:13:59.554 [task-11] DEBUG org.hibernate.SQL.logStatement - select account0_.id as id1_1_0_, ... where ... limit ?
0:0:0:0:0:0:0:1 - 0908592998 [10/Jul/2020:19:13:59 +0700] "GET /api/v1/account?page[offset]=0&page[limit]=10&page[totals] HTTP/1.1" 200 83
```

## Possible Solution
1. Elide should validate results of security checks first
2. Elide would perform next actions/queries upon the validation

## Your Environment
* Elide version used: Elide 5.0.0 - pr13 (as well as Elide 4.6.5)
* Environment name and version (Java 1.8.0_152): 1.8.0_202
* Operating System and version: MacOS 10.15.5
* Link to your project: N/A

**Comment by aklish** [comment]
Pagination is part of the act of fetching data from persistence.  It is not possible (or desirable) to separate these two things.  I don't think this is what you are asking though - but just calling this out based on the title of the ticket.

When reading collections, security is primarily focused on limiting the results that are returned (through filters applied to the queries and are pushed to the data store) - not through explicit checks.

For page totals, the only scenario where Elide can _not_ run the page total query is if the the results of the data load returned no records.  We could skip the page totals query in that case.

I'm going to edit the description of this issue accordingly.
