### ISSUE TITLE
RFC - Design for Multi Data Source Support for SQL Query Engine

### ISSUE THREAD

**Issue by moizarafat** [yahoo/elide#1465]
## Overview
Elide SQL Query Engine should support connections to multiple databases at the same time for running analytical queries. Elide will also support a configuration file format for the Query Engine DB properties.

On startup, the Elide service will create Persistent Units and EntityManagerFactorys using the DB properties from the configuration files. If no configuration is provided, the existing functionality should remain functional (use the existing Entity/CRUD DB connection for aggregation datastore).  

## DB Configuration Format
The database connection properties will be provided in [HJSON](https://hjson.github.io/) format config file (used with Dynamic Model Config currently). There can be multiple config files or a single config file with an array of properties.

## Location of Config

Elide will reuse the URL configuration setting, _modelConfig_ used for dynamic config model file location (point to a web or filesystem root directory containing the configuration) for the DB configuration.  The configuration will be stored in a directory, _db_. There will be separate directories for each query engine like SQL/NoSQL.

Optionally, the DB file (tarball archive) can be signed with PGP to verify its integrity (Similar to Dynamic Model Config).

```
db
└───sql
    │   db1.hjson
    │   db2.hjson
└───nonsql
    │   db1.hjson
    │   db2.hjson
└───variables.hjson
└───db.asc
```

The DB hjson files will be handlebar templates, allowing substitution through a variables.hjson file (Similar to Dynamic Model Config).

## Database Properties (in HJSON Config)
Any compulsory parameters will have to be passed along as top-level param and optional params can be passed as a Map.

| Property                      | Required   | Description                               | Default Value |
| ----------------------------- | ---------- | ----------------------------------------- | ------------- |
| name                          | Yes        | The name of the database connection.  This will be used for the persistent unit name. | N/A |
| url                 | Yes        |  The JDBC URL for the database connection i.e. javax.persistence.jdbc.URL  .| N/A |
| driver                 | Yes        |  The  JDBC driver for the database connection i.e. javax.persistence.jdbc.driver.| N/A |
| user                 | Yes        |  The  user for the database connection i.e. javax.persistence.jdbc.user.| N/A |
| dialect                 | Yes        |  The  Elide Dialect to use for query generation.| N/A |
| propertyMap                 | No        |  A map of Hibernate properties and persistence properties like , hibernate.show_sql, etc.| N/A |

Refer [additional properties](https://github.com/yahoo/elide/blob/9c5a5245ef29e9eb409255ead42f509f1c709ba9/elide-standalone/src/main/java/com/yahoo/elide/standalone/Util.java#L39-L60) that can be passed in the map. It will not be limited to these options, any option that PersistenUnit supports can be passed along.

## AggregationStore Annotation changes:
* Add a new attribute dbConnectionName to FromTable and FromSubquery Annotation.
* Update the ID population logic in Table.java, to include the dbConnectionName. 
* Table should have a method to retrieve the dbConnectionName from ID.

## Dynamic Config Helper Changes:
* A new JSON schema representing the config above.
* A new POJO representing the config above.
* Parse variables.hjson to get the variable map.
* DynamicConfigValidator will include logic to read, validate, variable substitution, and convert the DB config to POJO and make it accessible as property similar to ElideTable/ElideVariables/ElideSecurity POJOs.
* Support the passing of dbConnectionName through the table.hjson files and hydrate the handlebar template. 

## Dynamic Config Helper Validation Changes:
* In a Table definition, we need to verify the join clause does not refer to a Table which is not in the same DBConnection. 

## Query Engine Interface Changes:
* Add a new method getManagedClasses which will return a set of classes managed by the QueryEngine.
 
## SQL Query Engine Changes: 
* The SQL query engine should take 2 additional params; DBConfigPOJO and DynamicEntityCompiler(Optional), DefaultEntityManagerFactory created by Elide from Settings/Application.yaml.
* Existing attributes of SQL QueryEngine:  entity manager factory will be replaced by a list of entity manager factory.
* Using the DBConfig SQL Query Engine should create multiple Persistent Units and EntityManagerFactory. Refer [existing implementation](https://github.com/yahoo/elide/blob/9c5a5245ef29e9eb409255ead42f509f1c709ba9/elide-standalone/src/main/java/com/yahoo/elide/standalone/Util.java#L34). 
  - Attributes like user, driver, etc should be taken from the POJO to populate the corresponding javax.persistence arguments in propertyMap. 
  - Call the password extraction class. 
  - Also, convert propertyMap to java.util.properties.  
* Create a mapping of dbConnectionName provided in the DBConfig with corresponding EntityManagerFactory. 
  - Add the DefaultEntityManagerFactory to the mapping with default persistent unit db connection name.
* Create a Set of Classes (Dynamically compiled and from the classpath). The Set of Classes will only include the classes corresponding to the connectionName in Table Definition and is supported by this particular QueryEngine.
  - If any Table provided in the list is not present in the classpath or dynamicEntityCompiler, the process will fail.
* In SQLTransaction we should have the mapping of connectionName to EntityManagerFactory instead of EntityManagerFactory. 
* The initialization of the transaction in the SQLTransaction query will have to be moved to the executeQuery Method. 
  - From the Query object, in the executeQuery method, we should get Table and then from Table's Id parse the connection name. 
  - From connectionName to EntityManagerFactory mapping get the corresponding factory.  
  - Using the factory initialize the Entity Manager and Transaction. 
  - If there is no DB connection name in the Id of the table assume the default entity manager factory will be used.
* Another constructor that takes DynamicEntityCompiler(Optional) and an EntityManagerFactory will be created to support the use case if DB Config is not provided. In the DB connection name to EntityManagerFactory, use the default DbconnectionName.

## Aggregation Datastore Changes:
* The Aggregation Datastore will not take the Set of dynamic classes as an argument anymore.
* The Aggregation Datastore will take a Set of QueryEngines instead of single QueryEngine.
* The populateEntityDictionary method should iterate through the QueryEngine, retrieve the set of managed Classes, and bind them to the dictionary. 
* The Aggregation Datastore will also maintain a Class to QueryEngine mapping.

## Aggregation Datastore Transaction Changes:
* The Aggregation Datastore Transaction will take a Class to QueryEngine mapping instead of QueryEngine.
* queryEngineTransaction will have to be delayed until loadObjects is called and we determine which queryEngine to use. Other methods in the class will have to include checks if the transaction is active or not null before operating on it. 
* In `loadObjects` method, will have to get the type from EntityProjection. For the corresponding type retrieve the QueryEngine and use it.

## Elide Spring and Standalone Changes:
* Changes needed in configuration and initialization classes as per changes to the above. 
* Elide Spring, LocalEntityManagerFactoryBean logic used to support dynamic config will not be needed.
* Standardize the persistent unit name between elide standalone and elide-spring for the default case. They should both use a common name.

## Support for 3rd Party Password Extraction: 
A lot of applications do not pass the password in the config and rely on Secret / Key management services. We need to support a generic solution for that.

* A new interface DBPasswordExtractor with a method getDBPassword which takes DBConfigPOJO will be added. 
* The default implementation of this will set javax.persistence.passsword as blank in the PropertyMap and return the DBConfigPOJO back.

## Open to Discussion: 
~~i) We can have an aggregation store correspond to each Query Engine implementation. But that does not seem to add any benefits in the long run currently.~~

**Comment by aklish** [comment]
Rather than have the database reference the list of tables, I think each table should reference the database it belongs to.

**Comment by aklish** [comment]
Is QueryManager a typo?  Did you mean QueryEngine?  Or is QueryManager a new concept?

**Comment by moizarafat** [comment]
> Is QueryManager a typo? Did you mean QueryEngine? Or is QueryManager a new concept?

Sorry, that was a typo. Fixed now.

**Comment by aklish** [comment]
A few more things we should add/consider:

- The HJSON config file should support handlebars substitution
- Tables should have a reference to the DB where they are sourced from.   The DB should be part of the table ID in the metadata model.
- We should support handlebars substitution from the User and or Request Scope object in elide.  This will allow the database driver configuration to include properties from the request/user.  This is a requirement to have more complex authentication models where we pass credentials to the JDBC driver from the request itself (not from the server startup).

**Comment by moizarafat** [comment]
> A few more things we should add/consider:
> 
> * The HJSON config file should support handlebars substitution

Updated

> * Tables should have a reference to the DB where they are sourced from.   The DB should be part of the table ID in the metadata model.

Updated

**Comment by moizarafat** [comment]
> * We should support handlebars substitution from the User and or Request Scope object in elide.  This will allow the database driver configuration to include properties from the request/user.  This is a requirement to have more complex authentication models where we pass credentials to the JDBC driver from the request itself (not from the server startup).

As discussed, this change will be made part of a separate effort. My initial thoughts are this will be an extension of the other changes describe above and not involve any throwaway work. 

- `executequery` method will have to take requestScope as an argument.
-  requestScope and User will have to be enhanced to hold additional runtime config values.
- handlebar substitution from variables.hjson will have to be delayed till the `executequery` as handlebar substitution will re-place with `empty` string if variables can not be resolved.
- EntityManagerFactory and PersistentUnit creation will have to be delayed till `executequery` is called and will have to be recreated at every execution. So the SQLTransaction will need some modifications to change the attributes.

**Comment by moizarafat** [comment]
@aklish we have support for multiple QueryEngines. But is it possible that we will have multiple SQLQueryEngines or NoSQLQueryEngines? 
For example:
SQLQueryEngineA
SQLQueryEngineB
NoSQLQueryEngineA
