### ISSUE TITLE
Don't leak data from /relationships

### ISSUE THREAD

**Issue by clayreimann** [yahoo/elide#147]
Currently no permissions are evaluated if the contents of a relationship don't change. 

For example:
`A.foo = [B, C, D]`
and I 
`POST /A/relationships/foo [B, C]` 
I will always get `204` even when I don't have permission to modify `A#foo`

**Comment by DeathByTape** [comment]
Just a note: this fix is required for the testing framework to work properly. Consequently, I think it is of high priority.

**Comment by duseja2** [comment]
https://github.com/yahoo/elide/pull/273

**Comment by duseja2** [comment]
Reverting the change: https://github.com/yahoo/elide/pull/283 and reopening the issue

**Comment by DeathByTape** [comment]
@duseja2 can you comment on why we reverted and what we need to do to fix it?

**Comment by carueda** [comment]
Just learned about Elide a few minutes ago and looks interesting; however, sorry to be a bit blunt, but it's disappointing to see a 5+year old bug entry without any followup...

**Comment by aklish** [comment]
Sadly the bug still exists.  I agree that's disappointing.  We'll get a fix out asap.
