### ISSUE TITLE
RFC - Time Dimension should support different formats during serialization

### ISSUE THREAD

**Issue by moizarafat** [yahoo/elide#1474]
## Overview
Currently, Time Dimensions are represented as Java Date. This forces the SQL definitions to ensure it returns Date instead of String. Dates are then serialized using the serde and may include additional information like Hour, Minutes, etc depending on the Serde Format even though the SQL definition only included Year, Month, Date.  Also, there are use cases where we would want to return formats like YYYY-MM, YYMM, etc.

To address this, Elide will represent Time Dimension as new subclass of Date. Elide will introduce multiple in-built time grains which will have a pre-defined format, represented by a Date Subclass with a registered serde.  These time grains will also include the format information as an attribute.  Changing to subclass of Date will result in removal of support of multiple time grains for a time dimension cos results will have to display in the correct format. Instead, If multiple time grains are required on a database column, they will have to be represented as separate attributes in the model.

Note: The SQL Definition in the Model for the time grain will remain the same as now i.e. it should return a date/timestamp and Elide Serde will format it to the correct format. 

## Supported TimeGrains
TimeGrain Enum will represent the TimeGrains supported by Elide. The TimeGrain Enum will have a new attribute format. 

```
public enum TimeGrain {
    DATETIME("yyyy-MM-dd HH:mm:ss"),
    DATE("yyyy-MM-dd"),
    YEAR_MONTH("yyyy-MM"),
    MONTH_NAME("MMMMM")
    ..........
    ..........;
    
    private final String format;
    TimeGrain(final String format) {
        this.format = format;
    }
    ..... getter for Format
}
```

Supported Time Grains for now: 
- DATETIME("yyyy-MM-dd HH:mm:ss")
- DATE("yyyy-MM-dd"),
- YEAR_MONTH("yyyy-MM"),
- YEAR (Year in yyyy)
- YEAR_QUARTER("yyyy-Q<num 1-4>"),
- MONTH_NAME_FULL (January, February)
- MONTH (Month Number 1-12)
- WEEK_DAY (Monday, Tuesday ... )
- WEEK_OF_YEAR (1,2,3... )
- WEEK_DAY_NUM (1=Monday, 2=Tuesday ... )
- DATE_HOUR("yyyy-MM-dd HH")
- DAY_TIME("HH:mm:ss")
- HOUR("HH")
- HOUR_MINUTE("HH:mm")
- QUARTER("Q<num 1-4>")

## Changes to TimeGrainDefinition
Default Time Grain should be TimeGrain.Date

## Changes to TimeDimensionGrain
TimeDimensionGrain will have an additional attribute, format. It will be a string populated by getting the format from the grain.

## Changes to Temporal Annotation
Instead of an Array of grains, it will only support single Grain

## Changes to TimeDimension
- Instead of a set of TimeDimensionGrain, it will have only 1  TimeDimensionGrain

## New Timegrains 
A new package com.yahoo.elide.datastores.aggregation.timegrains will be created. New Sub Classes extending the java Date Class will be created. For example: 
```
public class DATETIME extends Date{
//Default Constructor
//Constructor that takes Date as argument and calls super(date.getTime())

}
```

A new package com.yahoo.elide.datastores.aggregation.timegrains.serde will be created. New Serdes will be created for serializing and deserializing the date classes. Refer com.yahoo.elide.utils.coerce.converters.TimeZoneSerde,  com.yahoo.elide.utils.coerce.converters.ISO8601DateSerde. 

- Serialize method will take the SubClassDate as an argument and convert the results to format represented by that class. For example, YearMonthSerde Serialize will take YearMonth type object as argument and then use java date format functions to convert to a string representing YYYY-MM 
- DeSerialize method will take the String as an argument and convert it to SubClassDate type object. For example, YearMonthSerde DeSerialize will take a string in format of YYYY-MM as an argument, create a date by parsing the string and then return java.sql.Date or java.sql.Time or java.sql.TimeStamp or YearMonth type object as needed.

## Changes to AggregationDataStore
- Remove logic to add 'grain' argument to each TimeDimensionColumn 

## Changes to Dynamic Config Models
- JSON Schema will be updated to allow only single Grain per time dimension instead of an Array of time grains.
- Table POJO should be updated
- Table Handlebar template will be updated to have only one TimeGrainDefinition for `@Temporal` annotation.
- In Handlebar hydration logic, we currently assign the Java Type as Date when dimension type = time. Instead the logic should look for the TimeGrain and then accordingly assign the SubClassDate type. 

## Open to discussion
i) Since the parent of the new subclasses is Date, will we have a conflict with DateSerde?

**Comment by aklish** [comment]
Instead of strings, each grain should be a new subclass of date with a
registered Serde.

**Comment by moizarafat** [comment]
> Instead of strings, each grain should be a new subclass of date with a registered Serde.

Corrected.

**Comment by moizarafat** [comment]
@aklish This is ready for review.

**Comment by aklish** [comment]
We will also need to remove the grain parameter from the TimeDimension for GraphQL schema.

**Comment by moizarafat** [comment]
> We will also need to remove the grain parameter from the TimeDimension for GraphQL schema.

Done
