### ISSUE TITLE
New Annotation to exclude @Table from MetaDataStore 

### ISSUE THREAD

**Issue by moizarafat** [yahoo/elide#1544]
`@Table` and `@Subselect` Annotated Models are getting included in the Analytics MetaDataStore

## Expected Behavior
Not all @Table Annotated Models satisfy the Analytics/Aggregated Model requirement. So we should be exclude them.

## Current Behavior
All @Table annotated Models are getting included.

## Possible Solution
A new annotation or option to exclude @Table and @SubSelect annotated models from MetaDataStore

**Comment by aklish** [comment]
Let's discuss more before implementing.
