### ISSUE TITLE
Filter syntax mistake  "??filter%5Bshop%5D=id%3D%3D'1"

### ISSUE THREAD

**Issue by Galand-V** [yahoo/elide#1697]
## Expected Behavior

I tried to filter on an entity, I made a mistake on the formalism : 

??filter%5Bshop%5D=id%3D%3D'1

I sould have an error because there is 2 mistakes in this filter : 
- two "?" instead of one
- the missing " '  " at the end to close the '1' 

## Current Behavior

Currently, the API call is working because of my double mistake... 

If I remove one "?" I have the expected error

## Possible Solution

Add an error message for this case ?

**Comment by aklish** [comment]
Seems reasonable.  The double ?? is causing the filter parameter to be '?filter' instead of 'filter'.  We should probably check for valid filter parameters in all of the controllers and JAX-RS endpoints.

**Comment by aklish** [comment]
The missing quote on its own does throw an error.  So it seems like the main issue here is the lack of validation on the provided query parameters.
