### ISSUE TITLE
Please drop Spectrum

### ISSUE THREAD

**Issue by Brutus5000** [yahoo/elide#1742]
Spectrum is a pain in the a** ever since you moved there. More than 50% of the time I try to read email notifications or try to ask something it's down or broken and I only use it for Elide (so not very often). I tried to publish this request there and again it just didn't work.

The Slack workspace just worked. Alternatively Zulip offers free Cloud hosting for open source projects. We use it at FAForever with more than 100 users and it just works.

**Comment by aklish** [comment]
@jkusa Thoughts on this?

**Comment by aklish** [comment]
@Brutus5000 - My thoughts on this:  I generally agree Spectrum has been a disappointment relative to other chat programs.   We had hoped github would have done more to improve spectrum and perhaps embed it more deeply into the github ecosystem.  I haven't seen either of those happen over two years.

Also, the lack of a mobile app is another negative.  I'd like to get some opinions from others though.  We already migrated from slack two years ago.  If we do migrate, I really don't want to do this again.

Thanks for the feedback and happy new year!

**Comment by jkusa** [comment]
I agree, Spectrum is a little rough around the edges plus no mobile app. The nice thing about Spectrum is that you can browse without a login or jump in with your Github account.

I have used Discord with other tech communities and I think the experience is a bit nicer.

**Comment by Brutus5000** [comment]
From my experience Discord chat can't be followed up on topic level such as Spectrum, slack threads or Zulip topics do. Slack and Zulip require a lot of discipline though to keep it organized. (Mattermost has no useful concept in that regard either)

**Comment by aklish** [comment]
I've turned on Github discussions for the repo as an experiment.  For now, we'll keep both Spectrum and github discussions active and see where conversations naturally end up.

I like that github discussions add "activity" to user profiles.  This seems like a good way to reward feedback and questions in a similar way to code contributions.

Let me know your thoughts.  Hopefully things won't get too fragmented.

**Comment by Brutus5000** [comment]
Github discussion works for me.
