### ISSUE TITLE
Fix elide-datastore-hibernate javadoc build warnings

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#1891]
Fix the following javadoc build warnings in elide-datastore-hibernate:

```
[WARNING] Javadoc Warnings
[WARNING] /sd/workspace/src/github.com/yahoo/elide/elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java:300: warning: no description for @param
[WARNING] * @param filterExpression
[WARNING] ^
```

**Comment by ved-asole** [comment]
HI @aklish, let me know what issue it's about and I will take care of it. It seems that some Java doc comments are missing.

**Comment by aklish** [comment]
You can take any sub module in elide and fix build warnings.  You are
correct that most are javadoc warnings.  You can either hunt for the
warnings in the last build:

https://cd.screwdriver.cd/pipelines/6103/builds/901732/steps/build

or better build locally.  Build instructions can be found here:

https://elide.io/pages/guide/v7/19-development.html#building

If you are interested in doing more than one PR, multiple modules have
these build warnings.

Thanks!  Let me know if you have any more questions.

**Comment by aklish** [comment]
Also, any PR you do that fixes warnings should get credit for
Hacktoberfest.
