### ISSUE TITLE
Should update Readme to highlight articles

### ISSUE THREAD

**Issue by clayreimann** [yahoo/elide#193]
https://dzone.com/articles/create-a-json-api-rest-service-with-spring-boot-an
https://dzone.com/articles/custom-security-with-a-spring-bootelide-json-api-s

**Comment by IDragonfire** [comment]
More usefull articles exists:

https://dzone.com/articles/logging-into-a-spring-bootelide-json-api-server
https://dzone.com/articles/securing-a-json-api-rest-service-with-spring-boot
https://dzone.com/articles/creating-entities-in-a-spring-bootelide-json-api-s
https://dzone.com/articles/updating-and-deleting-with-a-spring-bootelide-json

**Comment by DeathByTape** [comment]
I'll open a PR for this. Many of those tutorials may be slightly dated with the release of Elide 3.0 which will hopefully make things much cleaner :)
