### ISSUE TITLE
Complete an Accessibility Review for our site

### ISSUE THREAD

**Issue by r-andrew-dev** [yahoo/elide#1934]
Use our [accessibility review guide](https://yahoo.github.io/hacktogether/html/contribute.html#accessible) and template to complete a review for our site: https://elide.io/

** Please only complete one review per project in scope for Yahoo Hack together. 
* Link to your project:

**Comment by rishu2403** [comment]
Hi, I have done a quick accessibility review for https://elide.io/ as a contribution for HackTogether . I have attached PDF report below , please let me know if you have any questions.

[Elide_Hacktogether - Accessibility test .pdf](https://github.com/yahoo/elide/files/6218865/Elide_Hacktogether.-.Accessibility.test.pdf)

**Comment by r-andrew-dev** [comment]
Thank you!! -- Will not close out issue to ensure project maintainers can see and grab the review.

**Comment by aklish** [comment]
Thanks for this detailed report.  We will look into fixing these!
