### ISSUE TITLE
Seeking SPANISH translation for Readme.md

### ISSUE THREAD

**Issue by r-andrew-dev** [yahoo/elide#1943]
Use our [translation guide](https://yahoo.github.io/hacktogether/html/contribute.html#translation) to provide a translation in SPANISH  for the following files: 

[README.md ](https://github.com/yahoo/elide/blob/master/README.md)

**Comment by JFernando122** [comment]
I can help with the translation if still need it

**Comment by aklish** [comment]
Yes please!

**Comment by aklish** [comment]
Thanks.  Will look at this tomorrow.
