### ISSUE TITLE
RFC: Refactor tableSource to support multiple suggestion columns.

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#2003]
Dimensions in the aggregation store have an optional property, `tableSource`, which enables type-ahead search for filters in Yavin.

The format of `tableSource` is currently `tableName.columName` where tableName is the name of the Elide model and columName is the name of the attribute within that model that contains valid values for the dimension.

For star and snowflake database schemas, this often requires a join at query time to reference the textual names of dimensions in the query filters.

An alternative approach is for the user to select a dimension by its ID, but leverage other columns in the dimension table for type ahead search.

The proposal is to change tableSource from a string to an object with the following HJSON configuration format:

```json
"tableSource" : {
   "table" : "MyDimension",
   "column" : "id",
   "suggestionColumns" : ["name", "description"]
}
```

The property, `suggestionColumns` is optional and provides alternate fields to search in conjunction with the primary column.

The metadata API will expose a similar structure (replacing the existing Column.tableSource attribute with a new relationship):

```java
@Include(root = false)
class TableSource {
    @Id
    long id;

    @OneToOne
    Column valueSource;

    @ManyToMany
    Set<Column> suggestionSources;
}
```

**Comment by watfagithub** [comment]
👍 This is a good approach

**Comment by jkusa** [comment]
Looks good. My only comment is the name `suggestionColumns`. Maybe `contextColumns` or `relatedColumns`?

**Comment by jkusa** [comment]
Also, as @kevinhinterlong brought up, can the `suggestionColumns` be from a different table other that provided `table`?
