### ISSUE TITLE
RFC: Analytic Model Namespaces

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#2010]
# Overview

It would be convenient to build a hosted Elide service with multiple analytic models published by different teams.  These models need to be grouped together by subject area for better navigation.

Elide should introduce a new Namespace concept for organizing tables.

# HJSON Directory Layout

Namespaces will be created in a new namespace directory:

```
CONFIG_ROOT/
  ├── models/
  |  ├── tables/
  |  |  ├── model1.hjson
  |  |  ├── model2.hjson
  |  ├── namespaces/
  |  |  ├── namespace1.hjson
  |  |  ├── namespace2.hjson
  |  ├── security.hjson
  |  └── variables.hjson
  ├── db/
  |  ├── sql/
  |  |  ├── db1.hjson
  |  ├── variables.hjson
```

Namespaces and namespace files are optional.

# HJSON Configuration

Namespace files will have the following properties:

```
{
  name: MyNamespace
  friendlyName: 'My Namespace'
  readAccess: 'Admin'  #Default table permissions.  Can be overridden in any given table.
  description: 'A description of the MyNamespace namespace'
}
```

Table files will have a new, optional namespace attribute.  The attribute should be set to the name of a namespace.  Each table can only belong to a single namespace.  If no namespace is defined, a table belongs to the 'default' namespace.
```
{ 
  name: PlayerStats
  namespace: MyNamespace
  table: playerStats
  dbConnectionName: Presto Data Source
  ...
}
```

Table joins will also have a new, optional namespace attribute:

```
joins: [
 {
   name: playerCountry
   namespace: Foo
   to: PlayerCountry
   kind: toOne
   type: left
   definition: '{{playerCountry.id}} = {{country_id}}'
  }
]
```

If no namespace attribute is defined, the join refers to the table in the 'default' namespace.

# Metadata

Elide will introduce a new metadata model, Namespace:

```java
@Include(type = "namespace")
class Namespace {
    @Id
    private final String id;

    private final String name;

    private final String friendlyName;

    private final String description;

    @OneToMany
    private Set<Table> tables;
}
```

The Table metadata model will have a new relationship to its Namespace:

```java
@Include(type = "table")
class Table {
    ...

    @OneToOne
    private Namespace namespace;
}
```

The table ID will be modified to include the namespace.

# Default Namespace

The default namespace properties can be changed by creating a HJSON namespace with the name "default" - case insensitive.

**Comment by jkusa** [comment]
Will there be an ability to set config items for the `default` namespace?

**Comment by aklish** [comment]
> Will there be an ability to set config items for the `default` namespace?

Yes - modified description
