### ISSUE TITLE
Adding api version to swagger breaks swagger endpoint

### ISSUE THREAD

**Issue by white3km** [yahoo/elide#2124]
When adding the api version to the swagger properties for Spring Boot the swagger endpoint returns an empty array as the result.

## Expected Behavior
Should return elide generated swagger json.

## Current Behavior
Returns an empty array []

## Steps to Reproduce (for bugs)
1. Clone Elide Spring Boot Example (https://github.com/yahoo/elide-spring-boot-example)
2. Add `version: "1.0"` to elide.swagger in application.yaml
3. Run project and go the /doc endpoint

## Your Environment
* Elide version used: 5.0.1
* Environment name and version (Java 1.8.0_152): Open JDK 11.0.11
* Operating System and version: Windows

**Comment by aklish** [comment]
My guess is that the Elide models have not been versioned.  You will need to add the `ApiVersion` annotation to the Elide models to match the swagger API version in the application.yaml.

**Comment by thaingo** [comment]
When added `ApiVersion` annotation at package level (package that has all models), I face a new issue:
```
XYZ
[ Base URL: /api/v1 ]
/doc
No operations defined in spec!
```

Could you please advise @aklish ?

Also, Could I still use swagger without API versioning?

**Comment by aklish** [comment]
The SwaggerController in Spring has two constructors:

```java
    /**
     * Constructs the resource.
     *
     * @param docs A list of documents to register.
     */
    @Autowired(required = false)
    public SwaggerController(List<SwaggerRegistration> docs) {
        log.debug("Started ~~");
        documents = new HashMap<>();

        docs.forEach((doc) -> {
            String apiVersion = doc.document.getInfo().getVersion();
            apiVersion = apiVersion == null ? NO_VERSION : apiVersion;
            String apiPath = doc.path;

            documents.put(Pair.of(apiVersion, apiPath), SwaggerBuilder.getDocument(doc.document));
        });
    }

    @Autowired(required = false)
    public SwaggerController(Swagger doc) {
        log.debug("Started ~~");
        documents = new HashMap<>();
        String apiVersion = doc.getInfo().getVersion();
        apiVersion = apiVersion == null ? NO_VERSION : apiVersion;

        documents.put(Pair.of(apiVersion, ""), SwaggerBuilder.getDocument(doc));
    }
```

The second one takes a single Swagger document (with a single API Version).  It is what ElideAutoConfiguration is currently using.    When requesting swagger documents, the API version must also be specified.

To create multiple swagger documents (for different API versions), the first constructor must be called.  We probably can remove the second constructor and replace it entirely with the first.

**Comment by thaingo** [comment]
thanks @aklish for the guidance. Defined a custom one and it works perfectly.

**Comment by aklish** [comment]
Marking as closed.  Reopen if this is still an issue.
