### ISSUE TITLE
JsonApiController swallows repeated params

### ISSUE THREAD

**Issue by Brutus5000** [yahoo/elide#2166]
The Elide RequestScope has a field [MultivaluedMap<String, String> queryParams](https://github.com/yahoo/elide/blob/309f35b792124bfbef9cc0bb504b49d2f49f425a/elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java#L58) .
This indicates that we can have multiple parameters such as `a=1&a=2`.

However, the Spring Starter JsonApiController swallows everything except the first occurence of the parameter. I assume it's due to the param type in the controller being [Map<String, String>](https://github.com/yahoo/elide/blob/309f35b792124bfbef9cc0bb504b49d2f49f425a/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java#L69) rather than Map<String, List\<String>> or MultivaluedMap

So which behavior is the intended one? Before I start fixing the JsonApiController I'd like to have confirmation that you want to support multiple parameters with the same key.

**Comment by aklish** [comment]
We definitely don't want the controller to swallow query params.  `Map<String, List<String>>` is probably what we want here.
