### ISSUE TITLE
Do Elide support for HTTP 202 Accepted handling ?

### ISSUE THREAD

**Issue by aalex21** [yahoo/elide#2175]
Whether Elide has the following capability ?
1. If a request has been accepted for processing, but the processing has not been completed by the time the server responds, the server MUST return a 202 Accepted
2. For 202 Accepted response --  Any option to include an indication of the request's current status and either a pointer to a status monitor or some estimate of when the user can expect the request to be fulfilled.

**Comment by aklish** [comment]
The JSON-API spec is silent on what to return for a 202 Accepted response in terms of header or body.

You could try the following:

1. Create a LifeCycleHook for CREATE operations in the POSTCOMMIT phase.  In this post commit hook, throw a subclass of CustomErrorException:  https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/exceptions/CustomErrorException.java
2. Your subclass of CustomErrorException can return a 202 and customize the response body by overriding getErrorResponse and getVerboseErrorResponse.

Let me know if that works for you.

**Comment by aalex21** [comment]
Thanks, able to solve to some extends ..
