### ISSUE TITLE
Life cycle hook on a field in mapped superclass does not work correctly

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#2178]
Given a mapped superclass:
```
@MappedSuperclass
public abstract class BaseEntity  {

    @LifeCycleHookBinding(hook = NoUpdate.class, operation = LifeCycleHookBinding.Operation.UPDATE)
    private Instant createdAt;

    private String createdBy;

}
```

There are 2 concrete classes `Entity1` and `Entity2` that extend this `BaseEntity`.

And here is a simple hook on the field `createdAt` above:
```
public class NoUpdate implements LifeCycleHook<BaseEntity> {
    @Override
    public void execute(LifeCycleHookBinding.Operation operation,
                        LifeCycleHookBinding.TransactionPhase transactionPhase, BaseEntity baseEntity,
                        RequestScope requestScope, Optional<ChangeSpec> changeSpec) {
        throw new IllegalAction(HttpStatus.SC_BAD_REQUEST, "Cannot update this field ");
    }
}
```

Then we create an instance of `Entity1`  and an instance of `Entity2` as well. After that perform update the field `createdAt` on the both instances. The life cycle hook gets called in the 1st case when updating an `Entity1` instance, i.e. the exception is thrown. However, the very life cycle hook is not called in the 2nd case when update an `Entity2` instance.

## Expected Behavior
The life cycle hook should be called in both cases and should produce same result, i.e. the exception will be thrown as expected.

## Possible Solution

Replicate the field in all needed classes (models), then create a life cycle hook respectively on the field in every single class.

## Steps to Reproduce (for bugs)

1. Create an instance of `Entity1`
2. Create an instance of `Entity2`
3. Update field `createdAt` on the created Entity1 instance. Exception will be thrown
4. Update field `createdAt` on the created Entity2 instance. No exception will be thrown and the update operation is successful.

## Your Environment

* Elide version used: 5.0.3
* Environment name and version (Java 1.8.0_152): Oracle JDK 15
* Operating System and version: macOS
* Link to your project: N/A

**Comment by aklish** [comment]
Can you also post Entity1 and Entity2 and the request(s) you issued?

**Comment by thaingo** [comment]
@aklish I created a demo project but couldn't reproduce this issue. The life cycle hook is always invoked as expected.

However, I can always reproduce the issue with my current project, even at this moment. In the current project, unlike `Entity1` which `extends` only a mapped superclass, `Entity2` is also `implements` other 4 interfaces (these interfaces are used for building of security checks) - that is the major difference between current project and the demo. I also **disabled all security checks** on these 2 entities but still met this issue.

Appreciate if any hint for further investigation.

**Comment by aklish** [comment]
To help me figure out what might be happening, I still need more info - namely the beans (or something like them simplified) and the request(s).

**Comment by thaingo** [comment]
@aklish Thanks for your time, I finally found the evil. I was not consistent in placing Hibernate annotations. In some models I put annotations on fields, others - on their getters. That happened when I was experimenting some security checks and I didn't pay attention to. Consistently placing annotations has fixed the issue.
