### ISSUE TITLE
@ApiModel annotations disappear in swagger

### ISSUE THREAD

**Issue by Brutus5000** [yahoo/elide#2203]
While `@ApiModelProperty` annotations work fine, any class annotations with `@ApiModel` do not appear in the swagger file.
(I used the Spring Boot starter with the regular /doc endpoint).

## Expected Behavior
An Elide entity class annotated with `@ApiModel` should show the value on the model description of swagger.

## Current Behavior
The text from `@ApiModel` gets lost.

## Your Environment

* Elide version used: elide-spring-boot-starter:5.0.2
* Environment name and version (Java 1.8.0_152): AdoptOpenJDK 11.0.11
* Operating System and version: Arch Linux
* Link to your project: none

**Comment by aklish** [comment]
ApiModel is currently ignored.  Seems like a good thing to add.  We should also add new elide Annotations for ApiModel and ApiModelProperty that are Swagger agnostic so they can be leveraged for Graphiql as well.
