### ISSUE TITLE
Caching of ClassType instead of instantiating each time?

### ISSUE THREAD

**Issue by Brutus5000** [yahoo/elide#2215]
I'm currently trying to find causes for high GC activity when moving from getter-annotations to field level annotations. I do **not** think this issue is related, but it is a potential finding nevertheless.

https://github.com/yahoo/elide/blob/7edc5d2b329f99f6d14a44f9bd8969d7c9444576/elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java#L2003-L2007

## Expected Behavior

Elide doesn't recreate reusable stateless objects thousands of times for throwaway usage.

## Current Behavior

In my application EntityDictionary.getType creates a new ClassType on every call (object seems never to be instanceof Dynamic). If I'm running this on my main entity for a single id without any includes it is called ~300 times. This scales linearly with a page size. On 10 items on a page it's 3000 times, on 100 times it's 30000 times and so on (I have users scraping max page size of 10k, which causes then 3 million new ClassTypes for a single call).

## Possible Solution

The amount of possible "inputs" from object.getClass() is heavily restricted by the entities used in Elide.
Would it be beneficial to store the ClassTypes in a `HashMap<Class, ClassType>` and look them up every time instead of creating a new ClassType every time?

## Your Environment

* Elide version used: 5.0.3
* Environment name and version (Java 1.8.0_152): JDK 11
* Operating System and version: Arch Linux
* Link to your project: https://github.com/FAForever/faf-java-api/

**Comment by aklish** [comment]
Sounds like a good fix.
