### ISSUE TITLE
Patch extension and filter expression check issue

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#2239]
A value which is passed in from request header by API client, is used to build a filter expression check. This check is used in `UpdatePermission` for Elide model. Everything works fine except request using Patch extension.

## Steps to Reproduce (for bugs)

1. Create 2 `Sample` instances using
```
POST /api/v1/sample HTTP/1.1
Host: localhost:8080
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
Content-Length: 113

{
    "data": {
        "type": "sample",
        "attributes": {
            "owner": "owner1"
        }
    }
}
```

2. Update a created `Sample` instance using normal Patch method
```
PATCH /api/v1/sample/1 HTTP/1.1
Host: localhost:8080
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
x-owner: owner1
Content-Length: 130

{
    "data": {
        "type": "sample",
        "id": 1,
        "attributes": {
            "email": "email1"
        }
    }
}
```

3. Update batch of created `Sample` instances using Patch extension
```
PATCH /api/v1/sample HTTP/1.1
Host: localhost:8080
Accept: application/vnd.api+json;ext=jsonpatch
Content-Type: application/vnd.api+json;ext=jsonpatch
x-owner: owner1
Content-Length: 434

[
    {
        "op": "replace",
        "path": "/1",
        "value": {
            "type": "sample",
            "id": 1,
            "attributes": {
                "email": "email1"
            }
        }
    },
    {
        "op": "replace",
        "path": "/2",
        "value": {
            "type": "sample",
            "id": 2,
            "attributes": {
                "email": "email2"
            }
        }
    }
]
```

4. Error occur with request in step 3
```
[
    {
        "errors": [
            {
                "detail": "No x-owner header",
                "status": "400"
            }
        ]
    },
    {
        "errors": [
            {
                "detail": "Operation not executed. Terminated by earlier failure."
            }
        ]
    }
]
```

## Your Environment

* Elide version used: 5.0.6
* Environment name and version (Java 1.8.0_152): JDK 15
* Operating System and version: macOS
* Link to your project: [demo project](https://github.com/thaingo/elide-issue-cont)

**Comment by aklish** [comment]
I was able to reproduce with a test case.  Will look more into it today.

**Comment by aklish** [comment]
Found the bug:
https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java#L214

This should copy the headers from the outer scope.

**Comment by aklish** [comment]
I was planning on doing a release today.  I'll patch this and add it to the release.

**Comment by thaingo** [comment]
thanks a lot @aklish !
