### ISSUE TITLE
Strange result when doing Update on embedded object of a model

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#2277]
## Current Behavior

When updating a field of `embedded` object of an entity model, values of remaining fields of the embedded object are set to `null`.

## Expected Behavior

Value of interested field is updated as expected but values of remaining fields of `embedded` object should not be set to `null`.

## Steps to Reproduce (for bugs)

1. Create a **Sample** instance
```
POST /api/v1/sample HTTP/1.1
Host: localhost:8080
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
Content-Length: 219

{
    "data": {
        "type": "sample",
        "attributes": {
            "owner": "owner1",
            "address": {
                "city": "HCM",
                "country": "VN"
            }
        }
    }
}
```

2. Fetch created **Sample** instance
```
GET /api/v1/sample HTTP/1.1
Host: localhost:8080
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
```

3. Update the **Sample** instance
```
PATCH /api/v1/sample/1 HTTP/1.1
Host: localhost:8080
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
x-owner: owner1
Content-Length: 169

{
    "data": {
        "type": "sample",
        "id": 1,
        "attributes": {
            "address": {
                "city": "Saigon"
            }
        }
    }
}
```

4. Fetch the **Sample** instance again and will see that field `country` is `null` now.

## Your Environment

* Elide version used: 5.0.11
* Environment name and version (Java 1.8.0_152): JDK 15
* Operating System and version: MacOS
* Link to your project: [demo](https://github.com/thaingo/elide-issue-cont)

**Comment by aklish** [comment]
There are two ways to interpret how updates to complex attributes should be handled:
1. If you look at JSON-API spec, it says the following regarding update requests where some (but not all) of a model's attributes were provided: "If a request does not include all of the attributes for a resource, the server MUST interpret the missing attributes as if they were included with their current values. The server MUST NOT interpret missing attributes as null values."  This I believe is the behavior you are looking for _within_ attributes that have multiple fields.
2. The other approach is to consider the lack of supplying values for a given complex attribute field to signify the value should be null.  

Both are valid approaches.  Probably the first is more intuitive.  I believe Elide has had this behavior for sometime.  I don't think it is not a regression for a recent release.  If we were going to change the semantics here, it would be a breaking API change, and we would need to put it behind a feature flag.

In general, I don't think it would be too hard to implement.  PersistentResource.updateAttribute would be the place to add this logic.  It has the old and new values - and it could _merge_ the old with the new (preferring the new if it is explicitly set).

**Comment by thaingo** [comment]
Ok, I will find time for this PR soon.

Quick scanned over the `PersistentResource.updateAttribute`, looks like there are potential changes to:
1. `PersistentResource.setValueChecked`, hence `EntityDictionary.setValue` as well.
2. code segment doing custom logic for `setAttribute`.
3. place this change behind a feature flag.

Question:
1. What is difference between `EntityDictionary.setValue` vs. `Transaction.setAttribute` and what is business logic that requires to perform those actions (to call the 2 methods) whenever a change happens to an entity attribute?
2. Is there existing utility method helping to merge old and new values?
