### ISSUE TITLE
Explore Supporting Arbitrary Object Instantiation

### ISSUE THREAD

**Issue by DennisMcWherter** [yahoo/elide#234]
We should explore our options to instantiate checks and classes through a user-specified way. In particular, this would allow users to use injection for creation of things such as checks. As far as objects are concerned, users can already do this by overriding the data store `createObject()` directly.

Anyway, this merits some deeper thought.

**Comment by DeathByTape** [comment]
My current thoughts on this are to use an existing injection framework if possible; I have done this on some of our internal services.

Namely, the pattern is to bind your injector's `inject()` function (i.e. `injector.inject()`) to the `EntityDictionary`'s `bindInitializer()`.

That is, your object would still contain a trivial construct with your required fields `@Inject`'d. Moreover, you can obviously make this arbitrarily complex by composing your injection framework and arbitrary initialization functions to be used with `bindInitializer()`.

**Comment by DeathByTape** [comment]
NOTE: we have proven out this concept in our own systems. We should add this to docs before closing this ticket to show an example of this pattern.
