### ISSUE TITLE
CONTRIBUTING.md and IntelliJ code style xml

### ISSUE THREAD

**Issue by xiaoyao1991** [yahoo/elide#247]
What drives me to create this ticket is that I see import orders changed in git diff when I'm making changes. Maybe we should decide on the code style, and have a CONTRIBUTING.md like [this](https://github.com/druid-io/druid/blob/master/CONTRIBUTING.md) and an intelliJ code style xml like [this](https://raw.githubusercontent.com/druid-io/druid/master/druid_intellij_formatting.xml)

**Comment by shadanan** [comment]
Agree. You should put it together and do a PR.
