### ISSUE TITLE
Support for different filtering strategies

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#255]
# Multiple Filter Support

Elide should have the ability to support multiple filtering strategies - including those that allow complete boolean expressions supporting
_and_, _or_, _not_ operators, parenthesis, and various comparison operators.

## FIQL

One standard in this space is [FIQL](https://tools.ietf.org/html/draft-nottingham-atompub-fiql-00).

FIQL is lacking operators for:
* in/any
* all
* is null
* is not null
* not in/none

I propose we extend FIQL to include these operators:
* in would be denotedy by `=in=`
* any would be denotedy by `=any=`
* all would be denotedy by `=all=`
* none would be denotedy by `=none=`
* notin would be denotedy by `=!in=`
* is null would be denotedy by `=null=`
* not null would be denotedy by `=!null=`

## Supporting Multiple Strategies

Each strategy should have a formal grammar that compiles to an expression of filter predicates.
The expression is an abstract syntax tree that supports the visitor pattern.  The syntax tree will be
common for all Elide filtering strategies.  Each grammar will have its own syntax tree that must
be transformed into the common syntax tree that will be passed to `DataStoreTransaction` methods.

`Elide` will extend its builder pattern to select one or more filtering strategies that are supported:

 - `withFilqFilters` to add support for FILQ filtering strategy
 - `withJsonApiFilters` to add support for JSON-API recommended strategy

If more than one strategy is selected, the strategies will be applied in order to parse any query parameter
starting with 'filter'.

If parsing fails with one strategy, the next strategy in the list of selected strategies will be attempted until
all strategies have been exhausted.

## Not Breaking Elide 2.0

Methods which currently take a `Set<Predicate>` will still be supported:
```
    @Deprecated
    default <T> Collection filterCollection(Collection collection, Class<T> entityClass, Set<Predicate> predicates) {
        ...
    }

    @Deprecated
    default <T> Collection filterCollectionWithSortingAndPagination(Collection collection, Class<T> entityClass,
                                                          EntityDictionary dictionary, Optional<Set<Predicate>> filters,
                                                          Optional<Sorting> sorting, Optional<Pagination> pagination) {
        ...
    }

    default <T> Object getRelation(
            Object entity,
            RelationshipType relationshipType,
            String relationName,
            Class<T> relationClass,
            EntityDictionary dictionary,
            Set<Predicate> filters
    ) {
        ...
    }

    default <T> Object getRelationWithSortingAndPagination(
            Object entity,
            RelationshipType relationshipType,
            String relationName,
            Class<T> relationClass,
            EntityDictionary dictionary,
            Set<Predicate> filters,
            Sorting sorting,
            Pagination pagination
    ) {
        ...
    }
```

However, all the above methods will be deprecated, and they will only be invoked if `Elide` is constructed with only
the default JSON-API filter strategy.  If any other filter strategy is selected, a new set of similar methods will be invoked that
take a FilterExpression abstract syntax tree instead of a `Set<Predicate>`.

The deprecated methods will be removed in Elide 3.0

**Comment by johnoscott** [comment]
so what are some examples of filters using this change ? 

In particular, how could I craft a filter with an `OR` operator such as : `person.firstname like %john% or person.middleName like %john%`

**Comment by aklish** [comment]
That's coming in the next pr.  You can look at FIQL.  That is the first
dialect that will support and, or, not and grouping.  I hope to have a
follow up this weekend with supporting docs.

**Comment by aklish** [comment]
I saw this on my mobile - thought it was in relation to the code PR.  I'll update with more examples.  The code PR will allow support for different dialects - and for the developer to select which dialect(s) they want enabled.  FIQL will be one new dialect that supports more complex expressions.

FIQL uses ';' for conjunction and ',' for disjunction.  I believe your query would look like:
person.firstname=*john*,person.middlename=*john*

**Comment by aklish** [comment]
[Elide docs](http://elide.io/pages/guide/08-filters.html) have been updated.  PR is integrated.  I'm closing this issue.
