### ISSUE TITLE
Difference between createObject and createNewObject

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#2625]
I'm implementing a custom [`DataStoreTransaction`](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStoreTransaction.java) but have trouble telling the difference between [`createObject`](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStoreTransaction.java#L84) and [`createNewObject`](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStoreTransaction.java#L93).

Having read the source code a little bit, I feel like the former is creating a JPA managed object while the latter simply creates a POJO; is that right?

**Comment by aklish** [comment]
> I feel like the former is creating a JPA managed object.

createObject passes you a fully initialized object (all the attributes and
relationships have been set).  The ID field must still be set by the
DataStore however.
createNewObject just instantiates the POJO.

**Comment by QubitPi** [comment]
Thank you.
