### ISSUE TITLE
Support for GraphQL Federation

### ISSUE THREAD

**Issue by chirdeeptomar** [yahoo/elide#2638]
It would be very useful to provide support for Graphql federation so Elide can be adopted into a microservices architecture. Any plans to support that?

**Comment by chirdeeptomar** [comment]
Federation is a specification by Apollo. Apollo already provides federation library that can be added to an existing Graphql Java project to support federation.  When I added that dependency into Elide Standalone, the gateway could not recognise the entities on the graph.

My intent is to have Elide based microservices, called subgraph is federation terminology, to play well with hand-crafted graphql servers and all subgraphs can come together using GraphQL supergraph i.e. Gateway. 

Essentially I want to build simple CRUD like APIs with Elide and more complex API with Netflix DGS and they can play well together by fetching data across each other or directly using Federation and can also be fronted by a Federation Gateway.

**Comment by aklish** [comment]
Looking at https://github.com/apollographql/federation-jvm, it sounds like there is a bit of code required to transform the graphql-java schema into a schema that conforms with federation.

```
graphql-java-support produces a graphql.schema.GraphQLSchema by transforming your existing schema in accordance to the [federation specification](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/). It follows the Builder pattern.
```

and

```
If your schema does not contain any types annotated with the @key directive, nothing else is required. You can build a transformed GraphQLSchema with SchemaTransformer#build(), and confirm it exposes query { _schema { sdl } }.
```

I haven't tried this, but I imagine that transformation could be done in this function:

https://github.com/yahoo/elide/blob/master/elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java#L155

I'm not familiar with the federation specification so would need more time to understand everything that is expected and if there would be other issues.  It might be worth trying though.

**Comment by chirdeeptomar** [comment]
We have a Spring Boot GraphQL server and we recently added federation-jvm to it as we moved to microservices architecture and the types just worked without having the change the schema with @key annotation.  Apollo gateway nodejs could proxy the calls correctly.  I know there is more to just proxying the calls to fully and correctly implement federation.

I was expecting the same behaviour here, anyway, I was hoping to help with a PR but I am clueless with the Elide codebase. I am guessing it would take me a while to get upto speed. I don't mind though if you can point me to more documentation etc than what's already available.

Do check[ Netflix DGS Federation ](https://netflix.github.io/dgs/federation/) all the magic happens in the federation libraries which is already taken care of by federation-jvm.

**Comment by aklish** [comment]
I can play with it and see if I can get it to work.  If I provide a patch, could you test with your Apollo client and see if it works for your use case?

**Comment by chirdeeptomar** [comment]
Sure, I can do that. Would be interesting to see the patch and try to understand it.

**Comment by aklish** [comment]
This is the bare minimum:

https://github.com/yahoo/elide/pull/2640

This would need to behind a configuration flag as _service is intended to be a private field (not something you want to expose unless you have a gateway service).

There are other features in the federation specification.  I didn't have time to read and become familiar with them.  Can you see if this will work at all with Apollo and your use case?  If not, what additional features do you need from the federation spec?  

Thanks.

**Comment by aklish** [comment]
Also, to build Elide, instructions can be found here:
https://elide.io/pages/guide/v6/18-development.html#building

Let me know if you have questions.

**Comment by aklish** [comment]
One of the features I did not support in this minimal branch is the @key annotation on entities that will be merged across subgraphs.  That requires a bit of code to support some aspects of the federation schema.

**Comment by ts-ram** [comment]
Thanks @aklish .. Looking forward for the @key annotation support

**Comment by chirdeeptomar** [comment]
@aklish Not compiling with Adopt Open JDK 16 on home machine, updating max sdk version to 16 not working either. So will test at work with JDK 11.

**Comment by chirdeeptomar** [comment]
@aklish Finally able to compile on Java 11, I don't see enableFederation exposed via ElideStandaloneSettings so unable to override and see if _service is coming through?

**Comment by aklish** [comment]
I didn't add the configuration for ElideStandaloneSettings yet.   You can still enable by overriding:

```java
    default ElideSettings getElideSettings(EntityDictionary dictionary, DataStore dataStore, JsonApiMapper mapper) {

        ElideSettingsBuilder builder = new ElideSettingsBuilder(dataStore)
                .withEntityDictionary(dictionary)
                .withErrorMapper(getErrorMapper())
                .withJoinFilterDialect(RSQLFilterDialect.builder().dictionary(dictionary).build())
                .withSubqueryFilterDialect(RSQLFilterDialect.builder().dictionary(dictionary).build())
                .withBaseUrl(getBaseUrl())
                .withJsonApiPath(getJsonApiPathSpec().replaceAll("/\\*", ""))
                .withGraphQLApiPath(getGraphQLApiPathSpec().replaceAll("/\\*", ""))
                .withJsonApiMapper(mapper)
                .withAuditLogger(getAuditLogger());

        if (verboseErrors()) {
            builder.withVerboseErrors();
        }

        if (getAsyncProperties().enableExport()) {
            builder.withExportApiPath(getAsyncProperties().getExportApiPathSpec().replaceAll("/\\*", ""));
        }

        if (enableISO8601Dates()) {
            builder.withISO8601Dates("yyyy-MM-dd'T'HH:mm'Z'", TimeZone.getTimeZone("UTC"));
        }

        return builder.build();
    }
```

**Comment by aklish** [comment]
Will get back to you on the memory.  I want to profile standalone.

**Comment by aklish** [comment]
I did a quick memory profile of Elide standalone at boot:

<img width="1469" alt="Screen Shot 2022-05-07 at 8 40 44 PM" src="https://user-images.githubusercontent.com/6979393/167278261-e454ad37-917c-47c5-a560-43b29c9417d7.png">

**Comment by chirdeeptomar** [comment]
I haven't profiled it yet but just looked at windows task manager straight after booting standalone up, I am using AdoptJDK with Hotspot. Even the standalone example of yours, took 1.8 GB RAM according to Windows on both work and home machine. I will limit the jvmmax args and see.
