### ISSUE TITLE
Option to expose specific CRUD methods based on a config

### ISSUE THREAD

**Issue by chirdeeptomar** [yahoo/elide#2641]
Not all APIs require a create/update/delete method for example when static data is loaded via backend jobs etc and require only exposing query functionality.

It would be handy to have an elide wide setting that can be overridden by model annotation to specify which Operations are exposed and Swagger and GraphQL UIs take that into account. 

At the moment, I am achieving this via Checks but its not ideal as Update/Delete operations still show up in the Swagger/GraphQL UIs and caller gets the view of capabilities which we don't really support.

**Comment by aklish** [comment]
Love it.  We should definitely support this.

**Comment by chirdeeptomar** [comment]
Same problem with analytical queries, I have a query name empoyeeCountByCountry but swagger UI is generated for all GET/POST/PUT/Delete. I want to be able to define in HJSON that this is a GET method (without id) and perhaps define a url like so /api/empoyees/count or /api/empoyee-count

**Comment by chirdeep-tomar-db** [comment]
@aklish any update on this?

**Comment by chirdeeptomar** [comment]
@aklish any update on this?

**Comment by aklish** [comment]
My initial thought is that we could leverage existing Permission annotations that have NONE as the expression to remove paths from OpenAPI and similarly remove operations from GraphQL.   While not perfect, I expect that would support the most common scenarios without having to introduce a new annotation.

Would this work for your use cases?

**Comment by justin-tay** [comment]
I created a draft pull request to demonstrate a potential implementation of the idea. I think there might by some design needed if there is a need to filter the operations by id ie the `GET resource/{id}`, `DELETE resource/{id}`, `PATCH resource/{id}` endpoints for OpenAPI.
