### ISSUE TITLE
Upgrade hibernate to 6.0

### ISSUE THREAD

**Issue by cythrawll** [yahoo/elide#2679]
Mostly being requested due to H2 needing to be upgraded to 2.0. However this requires hibernate 6.0 in order to support the new H2 dialect. 6.1 is now the stable release and probably a good spot to handle adoption.

**Comment by aklish** [comment]
My sense is that Hibernate is so core here to Elide customers we'll need to spin a new major release for this change.   I agree this is worth doing though.

**Comment by bukajsytlos** [comment]
now that spring 6 is out with hibernate 6.1 I would say this should take some love.

**Comment by aklish** [comment]
I took a stab at this on elide 7 branch, but ran into issues with hibernate search (which doesn't appear to support hibernate 6 yet).

**Comment by aklish** [comment]
Fixed in Elide 7.
