### ISSUE TITLE
Question about why return 204 NO_Content when doing update

### ISSUE THREAD

**Issue by pagexv** [yahoo/elide#2711]
Hi,
I am using the Elide api for update. and I noticed that the update request will always return HttpStatus: 204 No Content. Body:  null
Is there a way to make the update api return the data that is being updated?

## Expected Behavior

Given (update data-type/1)
`curl --location --request PATCH 'http://localhost:9091/json-api/data-type/1' \
--header 'Content-Type: application/vnd.api+json' \
--header 'ApiVersion: v1.0' \
--header 'Authorization: c94856c7-50ac-4fd3-b395-89af4c7d7bbc' \
--header 'Accept-Language: en' \
--data-raw '{
    "data": {
        "id": 1,
        "type": "data-type",
        "attributes": {
            "baseUrl": "http://url"
        }
    }
}
'`

Return (Body after updating):
`{
    "data": {
        "id": 1,
        "type": "data-type",
        "attributes": {
            "baseUrl": "http://url"
        }
    }
}`

## Current Behavior

Given (update data-type/1)
`curl --location --request PATCH 'http://localhost:9091/json-api/data-type/1' \
--header 'Content-Type: application/vnd.api+json' \
--header 'ApiVersion: v1.0' \
--header 'Authorization: c94856c7-50ac-4fd3-b395-89af4c7d7bbc' \
--header 'Accept-Language: en' \
--data-raw '{
    "data": {
        "id": 1,
        "type": "data-type",
        "attributes": {
            "baseUrl": "http://url"
        }
    }
}
'`

Return (Body after updating):
null

## Possible Solution

when construct the patch response, is it possible to let end user decide to return response or not?

https://github.com/yahoo/elide/blob/309f35b792124bfbef9cc0bb504b49d2f49f425a/elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/BaseState.java#L177

## Context

I am in a context of building a CRUD admin api. And I need to present the response (entity after updating)  to client.

Although I have the option to call /Get api after updating, reading the response after update would make work easier. Because I don't need to call extra apis.

## Your Environment

* Elide version used:
* Environment name and version (Java 1.8.0_152):
* Operating System and version:
* Link to your project:

**Comment by moizarafat** [comment]
you can use this configuration. https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/ElideSettingsBuilder.java#L182

**Comment by pagexv** [comment]
Thank you, that is really helpful.

 I think it would be nice to add how to override ElideSetting 

https://github.com/yahoo/elide/blob/309f35b792124bfbef9cc0bb504b49d2f49f425a/elide-spring/elide-spring-boot-autoconfigure/README.md#elide-override

into the Elide documentation

https://elide.io/pages/guide/v6/01-start.html
