### ISSUE TITLE
Server response ignoring invalid parameter name. 

### ISSUE THREAD

**Issue by tarrantzhang** [yahoo/elide#272]
Server responses 200 with GET request like http://localhost:4080/author?haha[author.name]=John, as if the param doesn't exist. I'm not totally sure if ignoring a invalid param is preferable behavior here, or perhaps returning a error will be better?

**Comment by clayreimann** [comment]
I think this is desirable behavior, this allows people using elide to hook their own response filters after elide runs to do post processing if they like.

**Comment by DeathByTape** [comment]
Interesting point. I tend to agree with @clayreimann here; if someone was wrapping Elide and had such a syntax for `haha[author.name]=...` then Elide shouldn't get in the way of that. I believe one of the ultimate goals of Elide (in a general sense) is to be useful for things it does well and not get in the way of things it doesn't where you decide to build custom solutions around it. I think ignoring invalid parameters best jives with this goal.

Somewhat related may be the question of whether or not we should kick back an error for things Elide _does_ expect. For instance, if someone passed `filter[author.haha]=...` and the field `haha` doesn't exist on `Author`, right now we simply ignore the filter iirc. Perhaps it would be better to send a message back to the caller letting them know they made an invalid request. If you wanted to override this behavior you could, of course, subclass the datastore and then handle these filters however you wish.

Anyway, that's an aside and we probably shouldn't hijack this ticket to discuss it.

**Comment by clayreimann** [comment]
Blowing up if we see a query parameter (or header) that we don't understand is undesirable.
