### ISSUE TITLE
Custom AttributeConverter is ignored for enum types

### ISSUE THREAD

**Issue by markpatton** [yahoo/elide#2734]
When a data model is defined that includes an enum field with a custom AttributeConverter, that converter is ignored and instead the name of the enum is used.

## Expected Behavior

The custom AttributeConverter should be called. Consider the Java code below:

```java
@Include
@Entity
public class Widget {
    @Id
    private String name;

    @Convert(converter = WidgetTypeToStringConverter.class)
    private WidgetType type;

    @Convert(converter = LowerCaseStringConverter.class)
    private String lower;

    @Converter
    private static class WidgetTypeToStringConverter implements AttributeConverter<WidgetType, String> {
        @Override
        public String convertToDatabaseColumn(WidgetType attribute) {
            return attribute == null ? null : attribute.toString();
        }

        @Override
        public WidgetType convertToEntityAttribute(String dbData) {
            return dbData == null ? null : WidgetType.of(dbData);
        }
    }

    @Converter
    private static class LowerCaseStringConverter implements AttributeConverter<String, String> {
        @Override
        public String convertToDatabaseColumn(String attribute) {
            return attribute == null ? null : attribute.toLowerCase();
        }

        @Override
        public String convertToEntityAttribute(String dbData) {
            return dbData.toLowerCase();
        }
    }
}

public enum WidgetType {
    GOOD("good_one"), BAD("bad_one");

    private String value;

    WidgetType(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return value;
    }

    public static WidgetType of(String s) {
        return Arrays.stream(WidgetType.values()).filter(t -> t.value.equals(s)).findFirst().orElseThrow(IllegalArgumentException::new);
    }
}
```

The converter for the WidgetType enum should ensure that JSON API calls can use the values good_one and bad_one for the type field.

## Current Behavior

The converter for the WidgetType enum is not used. When using the JSON API endpoint, values for the type field are expected to be GOOD and BAD instead of good_one and bad_one.
The converter for the lower field does work.

## Possible Solution

Unknown. Why does the lower field converter work, but the type field converter not work?
I suppose the enum fields could be changed to strings and then hooks used to make sure standard values are used, but that seems rather ugly.

## Steps to Reproduce (for bugs)

See the enum-test branch of the elide standalone example I have forked here: https://github.com/markpatton/elide-standalone-example/tree/enum-test

1. git clone https://github.com/markpatton/elide-standalone-example
2. git fetch origin
3. git checkout enum-test
4. mvn package
5. java -jar target/elide-heroku-example.jar

Then either visit 'http://localhost:8080' and use the console to test the endpoint or do some curls like below.

This succeeds in creating a Widget entity using a value of GOOD for the type field. It should have failed.
```
curl -X POST "http://localhost:8080/api/v1/widget" -H "accept: application/vnd.api+json" -H "Content-Type: application/vnd.api+json" -d "{ \"data\": { \"type\": \"widget\", \"id\": \"test1\", \"attributes\": { \"lower\": \"MixEdCasE\", \"type\": \"GOOD\" }, \"relationships\": {} }}"
```

Retrieving the entity shows that the lower field converter was used:
```
{
      "type": "widget",
      "id": "test1",
      "attributes": {
        "lower": "mixedcase",
        "type": "GOOD"
      }
}
```

This fails to create a Widget when using good_one as the value of type, but should succeed
```
curl -X POST "http://localhost:8080/api/v1/widget" -H "accept: application/vnd.api+json" -H "Content-Type: application/vnd.api+json" -d "{ \"data\": { \"type\": \"widget\", \"id\": \"test2\", \"attributes\": { \"lower\": \"hmm\", \"type\": \"good_one\" } }}"

{"errors":[{"detail":"Invalid value: good_one"}]}
```

## Context

We have some standard string values for fields which we represent in Java as enums. The enums include those values just like WidgetType above. Those values are different from the Java names.
It would be extremely convenient to be able to wrap the enums in a converter as above.

## Your Environment

* Elide version used: 6.1.4
* Environment name and version Java 11.0.16 
* Operating System and version: Fedora 36
* Link to your project: https://github.com/markpatton/elide-standalone-example

**Comment by aklish** [comment]
Elide isn't aware of JPA converters.  It does have its own concept of Serdes that can convert a complex class attribute into something else.

Thinks of Converters as mapping between your data model and the database whereas Elide serdes map between JSON-API and your data model:

https://elide.io/pages/guide/v5/09-clientapis.html#type-coercion

**Comment by markpatton** [comment]
Ah! That makes sense. I had missed Serdes. So I define a Serde for WidgetType like so:

```
@ElideTypeConverter(type = WidgetType.class, name = "WidgetType")
public class WidgetTypeSerde2 implements Serde<WidgetType, String> {
    @Override
    public String deserialize(WidgetType val) {
        return val.toString();
    }

    @Override
    public WidgetType serialize(String val) {
        return WidgetType.of(val);
    }
}
```

Then I go and test, but still no luck. As above I try to create a Widget with a type of using the string GOOD which should fail. But instead it succeeds. The difference is that when I retrieve the new Widget it looks like:
```
    {
      "type": "widget",
      "id": "test1",
      "attributes": {
        "lower": "mixedcase",
        "type": "good_one"
      }
    }
```

So the Serde was ignored when going from JSON API to the model, but it was used when going from the model to JSON API.  (Trying to create a Widget with a type of "good_one" still fails.)

How can I get JSON API to use that Serde when for WidgetType when I create a Widget? (I have updated the example with the new Serde.)

**Comment by markpatton** [comment]
Looking at CoerceUtil, it seems like ToEnumConverter overrides any relavent Serdes for an enum type. 
See https://github.com/yahoo/elide/blob/52551b397b74b599700e038bf5a940457f4527f7/elide-core/src/main/java/com/yahoo/elide/core/utils/coerce/CoerceUtil.java#L114

This seems to explain why the Serde I defined for WidgetType was used when going a GET on an object, but not when trying to POST a new object.

**Comment by aklish** [comment]
CoerceUtil predates Serdes.  Probably the action here is to move Enum coercion (and probably some of the other types that are handled differently) into standard serdes like InstantSerde.  

Elide standard serdes are not scanned.  They can be turned on and off in ElideSettings which allows more control to disable them or manually enable just the ones you want.  

We can then remove lines like:
https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/utils/coerce/CoerceUtil.java#L118-L123

**Comment by aklish** [comment]
The above PR is a simpler fix.  Hopefully this will work for you.

**Comment by markpatton** [comment]
I tested the pr against the example and was successful! Thanks!
