### ISSUE TITLE
The currentError is null

### ISSUE THREAD

**Issue by tzhao** [yahoo/elide#2757]
## Current Behavior
ErrorObjects.ErrorObjectsBuilder builder = ErrorObjects.builder()
	                .withCode("506")
	                .with("customKey", "customValue")
	                .withDetail("A detailed message")
	                .addError();

The currentError is null, https://github.com/yahoo/elide/blob/309f35b792124bfbef9cc0bb504b49d2f49f425a/elide-core/src/main/java/com/yahoo/elide/core/exceptions/ErrorObjects.java

## Steps to Reproduce (for bugs)

1.  public ErrorObjectsBuilder with(String key, Object value) {
            currentError.put(key, value);
            return this;
        }

## Your Environment

* Elide version used:
* Environment name and version (Java 1.8.0_152):
* Operating System and version:
* Link to your project:

**Comment by aklish** [comment]
Definitely a bug.

**Comment by aklish** [comment]
Looking at this a bit more, I think the contract really does require addError to be called first.   The contract should throw an error if with is called prior to addError.
