### ISSUE TITLE
Changing relationships using Patch extension is not detected if attributes are also changed

### ISSUE THREAD

**Issue by kelseybrennan** [yahoo/elide#2814]
I think I have found a bug when using the Patch extension functionality to do an update. If the request changes both attributes and relationships, only the attribute changes are applied to the object that is provided to the DataStoreTransaction methods.

## Expected Behavior
Expected behavior is that both relationships and attributes can be changed in a single Patch extension request. This does work with the normal Patch request for a single entity.

## Current Behavior
Current behavior is that only the changes to the attributes are applied to the data that is passed to the DataStoreTransaction. The relationships on the object are exactly the same as they were when the object was retrieved through the `loadObject` method.

## Possible Solution
Not sure what the issue but I saw this comment about having to resolve relationships later, might be related to this code? https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/jsonapi/extensions/JsonApiPatch.java#L294

## Steps to Reproduce (for bugs)
Given a model like this:

```
object Book {
  int bookId; // id
  string name; // attribute
  Author author; // relationship
}

object Author {
  int authorId; // id
  string name; // attribute
}
```

1. Create Author 1 and Author 2 with normal post requests
2. Create Book 1 with normal post request, link it to Author 1
3. Send a patch extension request like this to change Book 1's author and name:

```json
[
	{
		"op": "replace",
		"path": "book/1",
		"value": {
			"id": "1",
			"type": "book",
			"attributes": {
				"name": "New Name"
			},
			"relationships": {
				"author": {
					"data": {
						"type": "author",
						"id": 2
					}
				}
			}
		}
	}
]
```

4. The Book object which gets passed into the `save` method has name="New Name" but the author is still pointing to Author 1

## Context
I have a custom implementation of the DataStore and DataStoreTransaction that uses the object passed into the `save` method to generate the changes that need to be performed in my application (https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStoreTransaction.java#L38).

I also have a UI that uses the patch extension endpoint a lot to handle changing different entity types in a single request. It's very confusing for the users to not have the changes they make in the links to other entities be reflected after they have submitted their changes since Elide is not passing that information through to my custom datastore.

## Your Environment
* Elide version used: 6.1.6

**Comment by aklish** [comment]
Patch extension has a more complicated execution plan (similar to GraphQL) for how the models are updated.  It rewrites the original request into two phases:

1. Create objects and update attributes
2. Update relationships

The transaction will still get called to update relationships - but it happens later.  This is because you can express cycles in the request which have to be resolved in this two phased approach.

Hope that helps explains what is going on.

**Comment by kelseybrennan** [comment]
Ok, where in the lifecycle have the relationships been updated then?

**Comment by kelseybrennan** [comment]
I see that the [updateToOneRelation](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStoreTransaction.java#L229) method is called with the correct relationship information. I think it would be useful to note this in [the information about the patch extension](https://elide.io/pages/guide/v6/10-jsonapi.html#bulk-writes-and-complex-mutations). I can adjust my code to handle the relationships this way so I'll close this issue.
