### ISSUE TITLE
elide framework will support for large data?

### ISSUE THREAD

**Issue by VENKATAPPA** [yahoo/elide#2819]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Elide version used:
* Environment name and version (Java 1.8.0_152):
* Operating System and version:
* Link to your project:

**Comment by moizarafat** [comment]
Please provide additional details, like volume, etc. Thanks

**Comment by aklish** [comment]
Do you mean large data as in a large attribute, a large collection, or something else?
