### ISSUE TITLE
Make it possible to fill the meta block in jsonApiDocument

### ISSUE THREAD

**Issue by paubor** [yahoo/elide#2820]
### Custom information in Meta Object of JSON API Responses

We want to be able to add custom fields to meta blocks in JSON API responses. This should be allowed according to the standard.

Currently, there does not seem to be a way to do that. 

I tried doing it inside the DataStoreTransaction, since the RequestScope contains the JsonApiDocument.
However, it does not seem to be used in the CollectionTerminalState, but rather creates a brand new one and fills it. 

Is there any way for us to change this is this a problem/ feature request in elide?

**Comment by aklish** [comment]
Your analysis is correct.  There isn't a way to do this currently, although it looks pretty straightforward to support.

Metadata is currently only returned when fetching collections.  Do you need it for other request types as well?

**Comment by paubor** [comment]
For our use case fetching collections would be enough.

**Comment by paubor** [comment]
Is there any rough estimate on when this could be available?

**Comment by aklish** [comment]
> Is there any rough estimate on when this could be available?

Not sure.  I posted a PR with a possible solution.  It needs tests still.  I think a full solution (setting Meta for individual resources) would require a breaking API change unfortunately.  However, I think your use case is doable.  Let me know what you think of the approach.
