### ISSUE TITLE
Seeking insights on embedding elide in JVM languages without annotations support

### ISSUE THREAD

**Issue by Nitinrajyadav** [yahoo/elide#2840]
Is it possible to use elide embedded where we can't modify entities with additional annotations or in languages having no support for entities; by generating required metadata in JSON or any other formats, and by providing some binding/wrapper.

I have an application that is build in Cold-fusion[A JVM language].
It used hibernate under the hood for Entity-management by generating the **hb.xm**l to get around the annotations.

Is it possibilities to use elide in the same fashion to create a **read-only API** to start with; so far, I haven't figured out anything approachable.

**Comment by aklish** [comment]
Does the hb.xml file map JVM classes to tables in your database?

**Comment by Nitinrajyadav** [comment]
Yes.
The language runtime generates the JVM classes(byte code) and generates the mappings for hibernate in 'classname.hb.xml' file for each entity with required metadata for the hibernate. 
I have access to hibernate's entity manager and the session factory, which is compatible with JPA.

**Comment by aklish** [comment]
I would probably make a set of non-JPA elide models to represent the entities you want to expose through Elide - and then create a custom DataStore that wraps the JpaDataStore.  The custom store just needs to convert between the hibernate entities and the Elide entities and call the corresponding methods in the JpaDataStore.
