### ISSUE TITLE
Serde interface: deserialize to specific subtype

### ISSUE THREAD

**Issue by eedijs** [yahoo/elide#2852]
## Current Behavior
Currently, when implementing the `Serde` interface, it's not possible to check the class of the deserializable value (for example - an enum class) to deserialize the value to that specific class, because in `CoerceUtil` class the `register(Class<T> targetType, Serde<S, T> serde)` method doesn't pass the class to `serde.deserialize`:

```java
    public static <S, T> void register(Class<T> targetType, Serde<S, T> serde) {
        initializeCurrentClassLoaderIfNecessary();

        SERDES.put(targetType, serde);
        ConvertUtils.register(new Converter() {

            @Override
            public <T> T convert(Class<T> aClass, Object o) {
                return (T) serde.deserialize((S) o);
               // here we could pass the class as well - return (T) serde.deserialize(aClass, (S) o);
            }

        }, targetType);
    }
```

If the class is also passed to the `serde.deserialize` method, maybe the `Serde` interface could have another `deserializeWithType`  (or similar) method instead?

Here's an example `@ElideTypeConverter` annotated class that could be used to deserialize enum classes that extend or implement a `BaseEnum` class:
```java
@ElideTypeConverter(name = "BaseEnumSerde", type = Enum.class, subTypes = {
        EnumOne.class,
        EnumTwo.class,
        EnumThree.class
        // etc.
})
public class BaseEnumSerde implements Serde<String, BaseEnum> {

    @Override
    public BaseEnum deserialize(Class<? extends BaseEnum> clazz, String value) {
        return Arrays.stream(clazz.getEnumConstants())
                .filter(enumConstant -> enumConstant.getValue().equals(value))
                .findFirst().orElse(null);
    }

    @Override
    public String serialize(BaseEnum baseEnum) {
        return baseEnum.getValue();
    }
}
```

## Your Environment
* Elide version used: 6.1.9

**Comment by aklish** [comment]
Seems like something we can add before we finalize Elide 7.
