### ISSUE TITLE
Unable to update the recursive relationship attribute

### ISSUE THREAD

**Issue by bhuvanavenkatesh** [yahoo/elide#2853]
Lets say I am having a table **Book**, which is having its child contents as below.
When I am trying to update the title of parent Book, I need to update its child book price as well. Instead of making 
multiple calls I am trying to update in a single call(PATCH operation)

```
public class Book implements Serializable {

  
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "book_id", nullable = false)
  private int book_id;

  @Column(name = "book_title")
  private String book_title;

  @Column(name = "price")
  private Long price;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "parent_book_id")
  private Book parent_book;

  @OneToMany(mappedBy = "parent", cascade = CascadeType.ALL)
  @Builder.Default
  private Collection < Book > child_contents = new ArrayList < > ();

}
```
	
	For Example Values are mapped in this way :
	
	book_id	|	book_title	|	price	|	parent_book_id
	1		Parent book		1000			null
	2		Child 1			400			1
	3		Child 2			400			1

When we try to do the same
Example Request Body : 
PATCH : /v1/book
```
{
    "data": {
        "type": "book",
        "id": "1",
        "attributes": {
            "title": "Parent Book New"
        },
        "relationships": {
            "child_contents": {
                "data": [
                    {
                        "type": "book",
                        "id": "2",
                        "attributes": {
                            "price": "500"
                        }
                    },
                    {
                        "type": "book",
                        "id": "3",
                        "attributes": {
                            "price": "600"
                        }
                    }
                ]
            }
        }
    }
}

```
Expected : parent title and child prices has to be updated.

Is there any suggestions/solutions to fix this issue?

**Comment by aklish** [comment]
Your use case sounds like what the patch extension was created for:

https://elide.io/pages/guide/v6/10-jsonapi.html#bulk-writes-and-complex-mutations

**Comment by bhuvanavenkatesh** [comment]
@aklish 
We tried as below
```
[
  {
    "op": "add",
    "value": {
      "type": "book",
      "attributes": {
        "name": "BookA"
      }
    }
  },
  {
    "op": "add",
    "value": {
      "type": "book",
      "attributes": {
        "name": "BookB"
      }
    }
  }
]
```
content-type
application/vnd.api+json; ext=jsonpatch

`

![MicrosoftTeams-image (38)](https://user-images.githubusercontent.com/120565052/208067033-70a7a719-780b-49a6-89d1-2be2defd37b1.png)


Getting the below error, Could you please help me to resolve the error
