### ISSUE TITLE
How to get 204 response instead of 200 for single end-point

### ISSUE THREAD

**Issue by bhuvanavenkatesh** [yahoo/elide#2854]
Using Elide V5
Consider we have 2 end-points /printers and /books

public class Printers implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "printer_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int printer_id;

	@Column(name = "printer_name", length = 50, nullable = false)
	@NotNull
	@NotBlank()
	private String name;	

}

Actual behaviour : During PATCH operation getting response as 200
Expected behaviour : During PATCH operation getting response as 200

public class Books implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "book_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int book_id;

	@Column(name = "book_name", length = 50, nullable = false)
	@NotNull
	@NotBlank()
	private String name;	

}

Actual behaviour : During PATCH operation getting response as 200

**Expected behaviour : During PATCH we need 204 as response. For only Books end point**

Is there any suggestions/solutions to fix the issue?

**Comment by aklish** [comment]
There isn’t a way to control 200 or 204 for a single endpoint.  There is a setting in Elide to toggle 200 and 204 globally though
