### ISSUE TITLE
Support RSQL INFIX, POSTFIX, and PREFIX filters on string type that has & character

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#2857]
## Current Behavior
Elide does not seem to support filter on string type that contains `&` character. For example: `filter[books]=name='*A&B*'`
It throws an error like:
```
{
    "errors": [
        {
            "detail": "Found undefined keys in request: B*&#39;"
        }
    ]
}
```

## Possible Solution
Encode `&` character before passing it to the filter, i.e. do this filter `filter[books]=name='*A%26B*'` instead.

## Your Environment

* Elide version used: 6.1.9
* Environment name and version (Java 1.8.0_152): JDK 15
* Operating System and version: MacOS
* Link to your project: N/A

**Comment by aklish** [comment]
The particular error above is thrown when the parsing of the HTTP request query params produces a parameter that is invalid.  The parsing in this case is done by Spring or JAX-RS.  The & needs to encoded before sent to the HTTP server.
