### ISSUE TITLE
Support for JPA (eg. EclipseLink)

### ISSUE THREAD

**Issue by jyskit** [yahoo/elide#287]
Currently, Elide relies on the "native Hibernate" API, not the JPA standard. This makes it impossible to use Elide with EclipseLink, OpenJpa, etc.

**Comment by DeathByTape** [comment]
This shouldn't be the case; which annotations are you referring to? In our `elide-core`, we have this set: https://github.com/yahoo/elide/blob/master/elide-core/pom.xml#L70

Are you including the hibernate datastores?

**Comment by wcekan** [comment]
See PR #747 as a start to this.  

Next I will refactor with a generic JPA superclass that supports any JPA with Hibernate 3 and 5 native becoming subclassed implementations.

**Comment by aklish** [comment]
We now support JpaDataStore.
