### ISSUE TITLE
More usable extension points

### ISSUE THREAD

**Issue by clayreimann** [yahoo/elide#291]
Elide currently provides several annotations and a DatastoreTransaction method that allow users to customize its runtime behavior. The current behavior looks like this:

```
--Start Request--
<@OnCreate> / <Load data>
*loop*
    <Update field>
    <@OnUpdate>
*end*
<@OnDelete>
<Request.preCommit>
<Check security>
<Commit transaction>
<@OnCommit>
--End Request--
```

This is not a useful model when:
- the `@OnCreate` relies on the object's values being present from the request
- the `@OnUpdate` hooks capture relationships between the object's attributes
- you want to fix-up an object before security is evaluated without rolling your own `Datastore` + `DatastoreTransaction`
- you want a chance to execute code after you know that the security checks have been successfully evaluated

A more useful set of lifecycle hooks (as it seems to me) would look like:

```
--Start Request--
<<Custom object instantiation>>
<Load data>
<Execute request payload>
<<Fix-up>>
<Check security>
<<Actions conditional on request success>>
<Commit transaction>
<<Final actions>>
```

Ideally all of these actions would be available directly from the beans, without having to create a custom `Datastore` or `DatastoreTransaction`; and these methods would have access to the request scope so they could determine what happened and/or load any additional resources they might require.

**Comment by aklish** [comment]
Custom object instantiation is done today via the Initializer.  I'm not sure what you have in mind for the first step and how it will allow injection of objects to the lifecycle hooks.

**Comment by DeathByTape** [comment]
After further discussion, I'm going to add an addendum to this proposal. I think this captures much of what we need, but as @aklish pointed out, it loses the spirit of its intuitive ties to CRUD. As a result, I propose we merge the two concepts as follows:


```
@PreCreate -> Executed on a create _before_ commit security checks are run, but after object has been fully populated with data (i.e. after all @OnUpdate hooks)
@PostCreate -> Executed on create _after_ commit security checks are run
@OnUpdate -> Executed on update _before_ operation security checks are run
@PreUpdate -> Executed on update _before_ commit security checks but after operation checks are run
@PostUpdate -> Executed on updated _after_ commit security checks are run
@OnDelete -> Executed on delete _before_ operation security checks
@PreDelete -> Executed on delete _before_ commit security checks
@PostDelete -> Executed on delete _after_ commit security checks
```

**Comment by aklish** [comment]
👍

**Comment by clayreimann** [comment]
👍

**Comment by DeathByTape** [comment]
Done in #345
