### ISSUE TITLE
CoerceUtil cannot convert String/Long to Date field properly

### ISSUE THREAD

**Issue by xiaoyao1991** [yahoo/elide#292]
`filter[author.creationDate][gt]=1454638927411` will receive an error complaining `"InvalidValueException: Invalid value: 1454638927411"`

**Comment by DeathByTape** [comment]
This is typically done by adding custom jackson serializers. Does that approach not work here for some reason?

**Comment by Koka** [comment]
@DeathByTape I'm afraid it's not true - almost everything is converted with `CoerceUtil` class wich isn't related to Jenkins at all and relies to Apache BeanUtils instead to perform conversion. To provide BeanUtils with new converter you have to do some ugly classloading tricks like this:

    private void hackElideDateParser() {
        try {
            Class.forName(CoerceUtil.class.getName());
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
        DateConverter dateConverter = new DateConverter();
        dateConverter.setPatterns(new String[]{
                "yyyy-MM-dd",
                "yyyy-MM-dd'T'HH:mm:ss",
                "yyyy-MM-dd'T'HH:mm:ss.SSSX",
        });
        ConvertUtils.register(dateConverter, Date.class);
        ConvertUtils.register(new Base64Converter(), byte[].class);
    }

**Comment by clayreimann** [comment]
@DeathByTape @Koka We should provide an easy way to customize how we serialize/deserialize data in elide

**Comment by xiaoyao1991** [comment]
I'm gonna address this with a custom coerce converter like we did in https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/ToEnumConverter.java

**Comment by DeathByTape** [comment]
@clayreimann this can be done via the jackson `ObjectMapper`. I have added a new constructor to make this more obvious: https://github.com/yahoo/elide/pull/317

We should also add this to the docs!

**Comment by DeathByTape** [comment]
@xiaoyao1991 your change is merged. Can you or @Koka confirm that this fixes the issue?

I will be cutting a new release very shortly so it should push out to maven central.
