### ISSUE TITLE
In-memory datastore ignores filters

### ISSUE THREAD

**Issue by Koka** [yahoo/elide#298]
Hello!

I've tried to setup simple elide service with in-memory datastore and all's fine except elide parses my filter expressions and then totally ignores them.

My Elide version is 2.3.12 and I do `GET http://<myserver>/<my app>/entitycollection?filter[entitycollection.id]=12345`, but it returns all entities from my `entitycollection`, not only one with id = 12345

As far as I can see in sources `com.yahoo.elide.datastores.inmemory.InMemoryTransaction` class doesn't override `com.yahoo.elide.core.DataStoreTransaction#loadObjects(java.lang.Class<T>, com.yahoo.elide.core.FilterScope)` method so it's defaults to return non-filtered collection.

Could someone please clarify if this is intended behaviour or just bug?

**Comment by shadanan** [comment]
The in-memory data store is incomplete. The filters haven't been implemented yet.

**Comment by freben** [comment]
Might I bump this question as well? I just started tinkering with Elide. The in-memory store serves as a neat piece of technical documentation on how to achieve the basics, so I think it would be super nice if the makers would find the time to update it to implement the non-deprecated methods etc. Particularly in regards to filtering; the rest could probably be done at a later time if needed.

**Comment by clayreimann** [comment]
Thanks for the comment. Elide 3, which is close to release, actually moves the InMemoryStore to be the reference implementation instead of a toy.

**Comment by freben** [comment]
That's great to hear. Thanks for your hard work on this library!

**Comment by DeathByTape** [comment]
If you want to build your own elide-3.0 for prototyping (albeit it is still undergoing active development and things may change), you can checkout the elide-3.0-wip branch :)

**Comment by DeathByTape** [comment]
Closing since this is supported in Elide 3.0. We are pretty much fully focused on elide 3.0 right now and are finishing vetting the 3.0 interfaces now. As a result, I don't think we're planning on adding this functionality to 2.0.
