### ISSUE TITLE
Does Elide support "speed" (average over date) measure?

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#3014]
This is not a bug report, so I skipped template fillment.

As the title suggests, our team is having a Yavin app backed by Elide and we need to have some `measure` that report some business logic about how "fast" things go. For example, our data table have 3 columns

1. start_date (an example column value is `2023-06-15`)
2. finish_date (`2023-06-23`)
3. total_amount (an example column value is `21`)

Our speed is defined by 

```
total_amount / (finish_date - start_date)
```

What we would like to see on a Yavin report is, for example, when we have 3 rows in the aforementioned table:

| start_date | end_date   | total_amount |
|------------|------------|--------------|
| 2023-06-01 | 2023-06-02 | 10           |
| 2023-06-02 | 2023-06-05 | 90           |
| 2023-06-08 | 2023-06-10 | 30           |

then we can see some "trending" data like:

[![quickchart.io](https://quickchart.io/chart?v=2.9.4&c=%7B%0A%20%20type%3A%20%27line%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%272023-06-01%27%2C%20%272023-06-02%27%2C%20%272023-06-03%27%2C%20%272023-06-04%27%2C%20%272023-06-05%27%2C%20%272023-06-06%27%2C%20%272023-06-07%27%2C%20%272023-06-08%27%2C%20%272023-06-09%27%2C%20%272023-06-10%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%27Speed%27%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B0%2C%2010%2C%2030%2C%2030%2C%2030%2C%200%2C%200%2C%200%2C%2015%2C%2015%5D%2C%0A%20%20%20%20%20%20%20%20fill%3A%20false%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%27green%27%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%2C%0A%20%20%7D%2C%0A%7D)](https://quickchart.io/sandbox/#%7B%22chart%22%3A%22%7B%5Cn%20%20type%3A%20'line'%2C%5Cn%20%20data%3A%20%7B%5Cn%20%20%20%20labels%3A%20%5B'2023-06-01'%2C%20'2023-06-02'%2C%20'2023-06-03'%2C%20'2023-06-04'%2C%20'2023-06-05'%2C%20'2023-06-06'%2C%20'2023-06-07'%2C%20'2023-06-08'%2C%20'2023-06-09'%2C%20'2023-06-10'%5D%2C%5Cn%20%20%20%20datasets%3A%20%5B%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20label%3A%20'Speed'%2C%5Cn%20%20%20%20%20%20%20%20data%3A%20%5B0%2C%2010%2C%2030%2C%2030%2C%2030%2C%200%2C%200%2C%200%2C%2015%2C%2015%5D%2C%5Cn%20%20%20%20%20%20%20%20fill%3A%20false%2C%5Cn%20%20%20%20%20%20%20%20borderColor%3A%20'green'%2C%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%5D%2C%5Cn%20%20%7D%2C%5Cn%7D%22%2C%22width%22%3A500%2C%22height%22%3A300%2C%22version%22%3A%222.9.4%22%2C%22backgroundColor%22%3A%22%23fff%22%7D)

Our [model configuration](https://elide.io/pages/guide/v5/04-analytics.html#model-configuration) looks like this:

```hjson
{
  tables: [
    {
      name: Speed Data
      friendlyName: Speed Data
      dbConnectionName: DBConnection
      dimensions: [
        {
          name: start_date
          friendlyName: Start Date
          category: Date
          type: TIME
          definition: '{{start_date}}'
          grains: [
            {
               type: DAY
            }
          ]
        }
        {
          name: finish_date
          friendlyName: Finish Date
          category: Date
          type: TIME
          definition: '{{$finish_date}}'
          grains: [
            {
               type: DAY
            }
          ]
        }
        {
          name: total_amount
          friendlyName: Total Amount
          category: Stats
          type: INTEGER
          definition: '{{$total_amount}}'
        }
      ]
      measures: [
        {
          name: speed
          friendlyName: How fast things go
          category: Stats
          type: INTEGER
          definition: '** we don't know yet, so we opened this issue **'
        }
      ]
    }
  ]
}
```

The closest analogy we can give is an `average` measure over some date range. However, we didn't find any documentations on `definition` for `average` on elide.io . We also researched Elide codebase without any satisfying lucks.

I think at the end of the day, what we would like to have is some `definition` that goes like

```
definition : '{{$total_amount}} / {{$finish_date - $start_date}}'
```

And we would like to have Elide calculate this for us so that we don't need an extra db column for "duplicate" data

Any suggestions would be greatly appreciated. Thanks.

**Comment by jkusa** [comment]
See https://github.com/yavin-dev/framework/issues/1725#issuecomment-1593545799
