### ISSUE TITLE
Can every entity be root entity?

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#3135]
Hi Elide team,

The root entity concept in elide sounds logically fair, but we are not sure what's the significance of making a JPA entity special this way. Is it for security reason? Or is it designed specifically for star schema? Would something break if we for example make every entity a root entity in our data model?

Thanks,

Jiaqi

**Comment by QubitPi** [comment]
Is [this](Matching newly created objects to IDs
When using UPSERT, Elide returns object entity bodies (containing newly assigned IDs) in the order in which they were created - assuming all the entities were newly created (and not mixed with entity updates in the request). The client can use this order to map the object created to its server assigned ID.) the answer? This sounds like getting it done in multiple HTTP request. 
If I'm not wrong, then how do we ensure atomicity described [here](https://elide.io/pages/guide/v7/11-graphql.html#:~:text=Perform%20any%20combination%20of%20the%20above%20edits%20together%20so%20they%20can%20happen%20atomically%20in%20a%20single%20request.)?

**Comment by aklish** [comment]
Every entity can be a root entity.  There is no harm in this.

**Comment by QubitPi** [comment]
Thanks
