### ISSUE TITLE
ParseException constructor needs to be public

### ISSUE THREAD

**Issue by Koka** [yahoo/elide#314]
I suggest to make `com.yahoo.elide.core.filter.dialect.ParseException` class constructor public so someone could implement their own filter dialect without any problem.

Currently this conctructor has package visibility so you need to put your dialect into `com.yahoo.elide.core.filter.dialect` package if you want correct handling of parsing errors when using your dialect as a part of `MultipleFilterDialect` for example.

**Comment by DeathByTape** [comment]
@clayreimann any particular reason this needs to go into elide-3.0? This can safely be patched into 2.x without any breaking changes.

**Comment by DeathByTape** [comment]
Done. Thanks for catching this!
