### ISSUE TITLE
@LifeCycleHookBinding doesn't work with ENUM

### ISSUE THREAD

**Issue by Sendvi41** [yahoo/elide#3165]
## Expected Behavior

 @LifeCycleHookBinding should work with ENUM field

## Current Behavior

  @LifeCycleHookBinding doesn't work with ENUM field

## Steps to Reproduce (for bugs)

1. Create Entity with Enum field
2. Use @LifeCycleHookBinding for this field example (
@LifeCycleHookBinding(operation = UPDATE, phase = PRECOMMIT, hook = YourHook.class)
StateEnum state' 
)
4. Try to change entity using json API
5. Hook will not work =(

## Your Environment

* Elide version used: 7.0.1
* Java 17
* Windows 11 pro

**Comment by Brutus5000** [comment]
Are you sure that other field types work?
From your example it is not clear if you use Hibernate field-based annotation or getter-method-level annotations. I never used field based lifecycles but I assume you have to use the same place for the annotation on which you use your general Hibernate annotations.

**Comment by aklish** [comment]
My theory is that elide doesn't see the field because it is transient so the hook never fires.  To verify, try removing transient and see if that resolves the issue.
