### ISSUE TITLE
JsonApiEndpoint problem with DELETEing resources

### ISSUE THREAD

**Issue by Koka** [yahoo/elide#321]
While using elide with JAX-RS integration (using Resteasy as JAX-RS provider) I've found the following: currently when using JsonApiEndpoint you can't delete resource without specifying `Content-Type` header because `delete` method in this class expects request body.

According to [jsonapi spec](http://jsonapi.org/format/#crud-deleting) DELETE requests need body only when you delete relationship but not when you delete resource itself.

HTTP DELETE requests to resource URLs without body and Content-Type header, like the following one, must be valid (but unfortunately currently they doesn't work, will return 415 error):

```
DELETE /photos/1 HTTP/1.1
Accept: application/vnd.api+json
```

**Comment by DeathByTape** [comment]
Updating from the PR: it looks like this is an implementation-specific issue with the RestEasy implementation of JAX-RS. In any case, we should work to resolve this issue for ease-of-use with any JAX-RS impl.

**Comment by DeathByTape** [comment]
I believe this issue is complete with @Koka's PR. feel free to reopen if it's not complete.
