### ISSUE TITLE
Conflicting grammar between Elide and Native GraphQL filterings?

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#3213]
## Expected Behavior

Hi Elide team, we are trying to fetch a person from database by ID.

We have a working native GraphQL query that looks like

```graphql
query GetPerson($id:String!) {
  person(filter:$id) {
    edges {
      node {
        id
        name
      }
    }
  }
}

{
  "id": "12345"
}
```

**We expect this query to work in Elide as well**

## Current Behavior

The query above, however, returns a RSQL parsing error, because it forces us to use RSQL syntax like

```graphql
query GetPerson() {
  person(filter:"id==\"12345\"") {
    edges {
      node {
        id
        name
      }
    }
  }
}
```

In addition, variable substitution *inside string* doesn't seem to work as we was not able to put things like 
`person(filter:"id==${someId}") {`

## Possible Solution

We have a hack like this

```graphql
query GetPerson($id:String!) {
  person(filter:$id) {
    edges {
      node {
        id
        name
      }
    }
  }
}

{
  "id": "id=='12345'"
}
```

But this makes our code non-portable by this non-Graphql syntax: `"id": "id=='12345'"` at the bottom and we are worried about more such conflicts which would complicate our developments in the future

*There would be a much happier Elide user if Elide could transparently maps native GraphQL filtering to Elide's RSQL filtering, because at the end of the day, much more people are comfortable with native GraphQL than adapting a special syntax like RSQL*

## Steps to Reproduce (for bugs)

The documentation mentions a [mandatory grammar of RSQL](https://elide.io/pages/guide/v7/11-graphql.html#filtering) which aligns with what we see at runtime

## Context

We have a frontend project using [Apollo GraphQL](https://www.apollographql.com/blog/how-to-search-and-filter-results-with-graphql) to construct GraphQL query, specifically using [`useQuery`](https://www.apollographql.com/docs/react/data/queries/#usequery-api). 

It'd be much better if elide can accept whatever is produced by `useQuery`

## Your Environment

* Elide version used: 7.x
* Environment name and version (Java 1.8.0_152): JDK 17
* Operating System and version: Ubuntu 22.04
* Link to your project: (This is an internal project. I'm sorry 🫤 )

**Comment by justin-tay** [comment]
As far as I know the GraphQL specification doesn't have any standards regarding the query arguments, let alone the filter argument. Can you indicate where the specification defines this native GraphQL filtering?

I think you would typically manipulate string variables with javascript using template literals.

If you just want to query by id you could use the `ids` argument.

```graphql
query GetPerson($ids:[String]) {
  person(ids:$ids) {
    edges {
      node {
        id
        name
      }
    }
  }
}

{
  "ids": ["12345"]
}
```

**Comment by QubitPi** [comment]
Hi @justin-tay , thank you for the reply.

Sorry for the confusion. What we mean by "filtering" actually turned out to be ["argument"](https://graphql.org/learn/queries/#arguments). Thanks.

We have tried your query which, however, gives back an error of:

<img width="1792" alt="page 1" src="https://github.com/yahoo/elide/assets/16126939/25efd7ca-025a-43f0-a281-8e59dc678214">

**Comment by justin-tay** [comment]
Does a person entity with that id exist? If it doesn't exist I think this is the expected behavior.

**Comment by QubitPi** [comment]
That ID doesn't exist yet.

I looked up [GraphQL Spec](https://spec.graphql.org/draft/#sel-FAPHRPDHAACJAo7K) which basically merits what you just said. I will close this issue then.

Thanks, Justin
