### ISSUE TITLE
EntityDictionary configuration in Elide Spring

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#3228]
Hi Elide team, we are trying to follow [EntityDictionary binding in Spring](https://github.com/yahoo/elide/blob/master/elide-spring/elide-spring-boot-autoconfigure/README.md#entity-dictionary-override). 

The latest Elide, however, gives us this compiler error:

<img width="1192" alt="page 1" src="https://github.com/yahoo/elide/assets/16126939/f3800179-2301-4005-b74b-bb446b796fe5">

Is the doc out-of-date?

**Comment by justin-tay** [comment]
Yes the doc is out of date.

You would typically customize the `EntityDictionary` in Spring with a `EntityDictionaryBuilderCustomizer`.

```java
@Configuration
public class ElideConfiguration {
	@Bean
	EntityDictionaryBuilderCustomizer entityDictionaryCustomizer() {
		return builder -> {
			builder.checks(checks -> {
				checks.put("allow all", Role.ALL.class);
				checks.put("deny all", Role.NONE.class);
			});
		};
	}
}
```

**Comment by QubitPi** [comment]
Thank you, @justin-tay ! That works.
