### ISSUE TITLE
SQL Server – querying all rows of an object fails

### ISSUE THREAD

**Issue by agentS** [yahoo/elide#323]
I am using Dropwizard 1.0.0 in combination with Elide to generate an API from my company's MS SQL Server 2008R2 database. For implementing the connection to the SQL Server I am using version 1.3.1 of the JTDS driver.

Despite of `dropwizard-elide` depending on version 0.9.2 this setup works fine for querying single objects. However, when I want to retrieve all objects of a class I get an exception telling me that there is a syntax error near `@P0`.

[I have done some research](https://stackoverflow.com/questions/7038818/ms-sql-exception-incorrect-syntax-near-p0) and discovered that this corresponds to a error in handling the parameters. Despite of searching for parameters in your code I have not been able to find such an expression.

So, my question is which HQL statements (I suppose you use HQL) are in use and where can I find them in the source code. If there aren't any statements in the code this probably means that there is a bug in Hibernate 5.

Thanks for your help and for the great Elide framework.

**Comment by agentS** [comment]
You can see my persistance classes below

@Entity
    @Table(name = "log_event")
    @Include(rootLevel = true)
    public class LogEvent
    {
	    private long id;
	    private String username;
	    private String severity;
	    private long targetId;
	    private long categoryId;
	    private ZonedDateTime date;
	    private LogAuthenticationEvent authenticationEvent;
	
	    @Id
	    @GeneratedValue(strategy = GenerationType.IDENTITY)
	    @Column(name = "event_id")
	    public long getId()
	    {
		    return this.id;
	    }
	
	    public void setId(long value)
	    {
		    if (value > (-1))
		    {
			    this.id = value;
		    }
	    }

	    @Column(name = "username")
	    public String getUsername()
	    {
		    return this.username;
	    }
	
	    public void setUsername(String value)
	    {
		    this.username = value;
	    }

	    @Column(name = "severity")
	    public String getSeverity()
	    {
		    return this.severity;
	    }
	
	    public void setSeverity(String value)
	    {
		    this.severity = value;
	    }

	    @Column(name = "target_id")
	    public long getTargetId()
	    {
		    return this.targetId;
	    }
	
	    public void setTargetId(long value)
	    {
		    if (value > (-1))
		    {
			    this.targetId = value;
		    }
	    }
	
	    @Column(name = "category")
	    public long getCategoryId()
	    {
		    return this.categoryId;
	    }
	
	    public void setCategoryId(long value)
	    {
		    if (value > (-1))
		    {
			    this.categoryId = value;
		    }
	    }

	    /*@Column(name = "event_date")
	    @Type(type = "org.hibernate.type.ZonedDateTimeType")
	    public ZonedDateTime getDate()
	    {
		    return this.date;
	    }
	
	    public void setDate(ZonedDateTime value)
	    {
		    this.date = value;
	    }*/
	
	    @OneToOne(mappedBy = "event")
	    public LogAuthenticationEvent getAuthenticationEvent()
	    {
		    return this.authenticationEvent;
	    }
	
	    public void setAuthenticationEvent(LogAuthenticationEvent value)
	    {
		    this.authenticationEvent = value;
	    }
    }

@Entity
    @Table(name = "log_remote_client")
    @Include(rootLevel = true)
    public class LogAuthenticationEvent
    {
	    private long id;
	    private String clientAddress;
	    private String userAgent;
	    private LogEvent event;
	
	    @Id
	    @GeneratedValue(strategy = GenerationType.IDENTITY)
	    @Column(name = "user_event_id")
	    public long getId()
	    {
		    return this.id;
	    }
	
	    public void setId(long value)
	    {
		    if (value > (-1))
		    {
			    this.id = value;
		    }
	    }
	
	    @Column(name = "ipv4_address")
	    public String getClientAddress()
	    {
		    return this.clientAddress;
	    }
	
	    public void setClientAddress(String clientAddress)
	    {
		    this.clientAddress = clientAddress;
	    }
	
	    @Column(name = "user_agent")
	    public String getUserAgent()
	    {
		    return this.userAgent;
	    }
	
	    public void setUserAgent(String userAgent)
	    {
		    this.userAgent = userAgent;
	    }
	
	    @OneToOne
	    @JoinColumn(name = "event_id")
	    public LogEvent getEvent()
	    {
		    return this.event;
	    }
	
	    public void setEvent(LogEvent event)
	    {
		    this.event = event;
	    }
    }

**Comment by DeathByTape** [comment]
Thanks for reporting this @agentS :) Just wanted to ping this ticket and let you know we've started thinking about this a little bit on our end. If you're not using any filters, I don't think we use any HQL in our default loading path (and will hopefully eliminate it with the upcoming release of elide 3.0!). 

Anyway, can you post some hibernate logging?

Specifically, I would be interested in seeing `DEBUG` log for `org.hibernate` and `TRACE` debug for `org.hibernate.type.descriptor`. You can set this in your log4j2.xml or logback.xml (or whatever logger you happen to be using). This should show you both the _precise_ query that is being fired and also some additional information about known values. Thanks!

**Comment by agentS** [comment]
Thank you for reply. Using your tips I have been able to locate the exception. The query shown below causes the error.

    DEBUG [2016-08-22 05:54:58,311] org.hibernate.SQL: /* criteria query */ select TOP ?  this_.event_id as event_id1_0_1_, this_.category as category2_0_1_, this_.severity as severity3_0_1_, this_.target_id as target_i4_0_1_, this_.username as username5_0_1_, logauthent2_.user_event_id as user_eve1_1_0_, logauthent2_.ipv4_address as ipv2_1_0_, logauthent2_.event_id as event_id4_1_0_, logauthent2_.user_agent as user_age3_1_0_ from log_event this_ left outer join log_remote_client logauthent2_ on this_.event_id=logauthent2_.event_id
    DEBUG [2016-08-22 05:54:58,317] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: could not extract ResultSet [n/a]
! java.sql.SQLException: incorrect syntax near '@P0'.

Being interpreted as parameter without parentheses the `?` after the `TOP` statement needs to be put in parentheses.

**Comment by DeathByTape** [comment]
@agentS could you also show me the query URI you're using as well? Depending on what your query looks like, the criteria is probably created in one of the following places:

https://github.com/yahoo/elide/blob/master/elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java#L175
or
https://github.com/yahoo/elide/blob/master/elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java#L195

Are you explicitly passing in `@P0`? If not, this _could_ be a hibernate bug, I suppose. That being said, it seems as though a query to fetch all objects of a given type should be one of the most basic queries that can be made :) so I would still be hesitant about actually pointing my finger over there.

Unfortunately, I don't have access to a SQL server instance here, but I may be able to look into this a little deeper at home.

Please keep reporting your findings as it does help drill-down overall. In the meantime, I would suggest setting some breakpoints in the code I mentioned above and see if your query triggers either of them. You may be able to gain some more information by taking a look at the variable states and so forth at that point.

**Comment by agentS** [comment]
The query URL which is not working is `http://[::1]:8082/logEvent`. An example of a working URL is `http://[::1]:8082/logEvent/702`.

Using your provided information I am going to try to debug the issue. However, I am on holiday starting tomorrow. So this might take some time.

**Comment by DeathByTape** [comment]
Sorry for losing track of this ticket @agentS, did you have any luck in solving this?

**Comment by DeathByTape** [comment]
Any update?

**Comment by DeathByTape** [comment]
Going to close this for now since it seems to be stale. If anyone else faces this issue, please feel free to reopen this issue or open a new one.

Thanks!
