### ISSUE TITLE
PDF extension for exported data

### ISSUE THREAD

**Issue by HassanAzzam** [yahoo/elide#3285]
My use case is to export a bunch of data rendered in PDF format. I know that the library doesn't support exporting PDF out-of-box, but I was wondering if I can register a renderer class(which puts exported data into place in the file) for a corresponding custom extension. The renderer class would work as a post-processor for the fetched data.

## Context
Async API
export

**Comment by justin-tay** [comment]
You will need to

* Write your own `TableExportFormatter`
* Register the formatter using `TableExportFormattersBuilderCustomizer`
* Have a `ResultTypeFileExtensionMapper` that supports the file extension

You can see [AsyncTest](https://github.com/yahoo/elide/blob/4b5667b9bd23f2b5835adec7fa3c0cf26fb4bccd/elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AsyncTest.java#L29) and [XlsxExportFormatter](https://github.com/yahoo/elide/blob/4b5667b9bd23f2b5835adec7fa3c0cf26fb4bccd/elide-async/src/main/java/com/yahoo/elide/async/export/formatter/XlsxExportFormatter.java#L19)

**Comment by HassanAzzam** [comment]
This was very helpful, Thank you!
