### ISSUE TITLE
Failure to initialise objects with Hibernate5

### ISSUE THREAD

**Issue by pettermahlen** [yahoo/elide#336]
I'm seeing a really weird behaviour where retrieving a collection of objects works well, but retrieving by individual ID leaves all fields in the returned JSON 'null'. 

```
$ http localhost:8080/v2/project
HTTP/1.1 200 OK
Content-Length: 385
Content-Type: application/vnd.api+json
Date: Mon, 24 Oct 2016 06:16:55 GMT
Server: Jetty(9.3.4.v20151007)

{
    "data": [
        {
            "attributes": {
                "gcpProject": "flerp",
                "name": "The Hubble Project"
            },
            "id": "hubble",
            "relationships": {
                "owner": {
                    "data": {
                        "id": "tools",
                        "type": "team"
                    }
                },
                "roles": {
                    "data": []
                }
            },
            "type": "project"
        },
        {
            "attributes": {
                "gcpProject": "xpn-system-z-1",
                "name": "The System-Z Project"
            },
            "id": "system-z",
            "relationships": {
                "owner": {
                    "data": {
                        "id": "tools",
                        "type": "team"
                    }
                },
                "roles": {
                    "data": []
                }
            },
            "type": "project"
        }
    ]
}

$ http localhost:8080/v2/project/hubble
HTTP/1.1 200 OK
Content-Length: 144
Content-Type: application/vnd.api+json
Date: Mon, 24 Oct 2016 06:16:59 GMT
Server: Jetty(9.3.4.v20151007)

{
    "data": {
        "attributes": {
            "gcpProject": null,
            "name": null
        },
        "id": "null",
        "relationships": {
            "owner": {
                "data": null
            },
            "roles": {
                "data": []
            }
        },
        "type": "project"
    }
}
```

Searching for a non-existent ID gives a 404, as expected.

I've been able to trace this via the debugger to being some kind of initialization problem. There is a proxy object with an initialized `AbstractLazyInitializer` whose `target` has the right data, but the proxy itself has just nulls in all fields.

The setup:

- MySQL DB
- HikariCP for connection pooling
- Hibernate 5.0.2.Final (tried 5.2.3 as well but that throws an UnsupportedOperationException in the Elide `HibernateStore.populateEntityDictionary` method)

Any ideas or pointers?

**Comment by clayreimann** [comment]
Hi @pettermahlen, can you provide more of your code (or even better a minimal example project that also exhibits the problem)?

**Comment by pettermahlen** [comment]
Not sure if it's minimal, but it's at least pretty small: https://github.com/pettermahlen/elide-repro

**Comment by clayreimann** [comment]
Thanks for the example, it turns out that `Hibernate.load` + `Hibernate.initialize` does not populate the fields on a bean.

On a related note, I tried updating your example for Hibernate 5.2.3.Final but I ran into this error: `org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.connections.spi.ConnectionProvider]`

**Comment by pettermahlen** [comment]
I can verify that the change fixes my problem also in the larger context where I was trying to use it!
