### ISSUE TITLE
Elide logo on Ubuntu

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#349]
I'm seeing this in Chrome browser on Ubuntu 16.04. The logo looks funny

![ubuntu](https://cloud.githubusercontent.com/assets/16126939/20332469/a430e2ca-ab71-11e6-9971-7a0c4e907dbf.png)

**Comment by DeathByTape** [comment]
SVG fail :( Anyone good with graphics? :)

**Comment by QubitPi** [comment]
How about converting it to PNG?

**Comment by clayreimann** [comment]
It's an artifact of the `HelveticaNeue-Light` font not being present on Linux, I'm guessing. We should probably just convert the letters to vector paths (or pick a font that's available on all platforms)

**Comment by cdeszaq** [comment]
Vector paths are the only way to ensure that things don't get messed up with SVG. (it's also what svg-based font use...). Trying to find a font that's available on all platforms is a fruitless effort because there are so many variations. Illustrator should have no problem doing that conversion...

**Comment by emergie** [comment]
use http://elide.io/assets/images/elide.svg 

it is based on svg paths and looks good:
![selection_010](https://user-images.githubusercontent.com/2456881/31051537-10ba1d7c-a66b-11e7-8eb3-1e1a0d19ebfb.png)

the one from gh page defines text 
``` xml
<text transform="matrix(1, 0, 0, 1, 61.233, 86.5)">
  <tspan x="-56.016" y="52.5" font-family="HelveticaNeue-Light" font-size="144" fill="#000000">El</tspan>
</text>
```
and as such will always look bad on platforms without  `HelveticaNeue-Light`:
![selection_011](https://user-images.githubusercontent.com/2456881/31051567-bf16fc96-a66b-11e7-8652-0f70214f4b54.png)
