### ISSUE TITLE
Should add support for private id field and getter

### ISSUE THREAD

**Issue by exports** [yahoo/elide#352]
If entity's id field is private and annotated `@Id private String id`, the id's getter method should be used if present instead of returning `{ id: null }` in response. For example, by adding following code in the end of [EntityBinding:: bindEntityFields](https://github.com/yahoo/elide/blob/1586d264ccd41a285f11d784930dbe7c09db457b/elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java#L120-L139) may solve this issue (not tested yet):

```
if (idField == null) {
        try {
              AccessibleObject getIdMethod = cls.getMethod("getId");
              this.bindEntityId(cls, type, getIdMethod);
        } catch(NoSuchMethodException ignored) {};
}
```

**Comment by aklish** [comment]
I haven't tested this yet but your diagnosis looks correct.

**Comment by DeathByTape** [comment]
That's likely the case. I think we fell into the hibernate trap here? I think hibernate often chokes when you annotate the field in the presence of a getter. In any case, perhaps we should be smart about this. @wcekan do you have any thoughts on potential gotchas here?

**Comment by aklish** [comment]
This issue was resolved when Elide added support for both property (method) and field access.
