### ISSUE TITLE
Add support for sorting based on relationship attributes

### ISSUE THREAD

**Issue by Nikash** [yahoo/elide#353]
Seems like this isn't supported right now.

The [spec](http://jsonapi.org/format/#fetching-sorting) says:

> Note: It is recommended that dot-separated (U+002E FULL-STOP, ".") sort fields be used to request sorting based upon relationship attributes. For example, a sort field of author.name could be used to request that the primary data be sorted based upon the name attribute of the author relationship.

For example `/books?sort=author.name` or `/books?sort=book.author.name` should be able to return books sorted by author's name.

**Comment by aklish** [comment]
I think something like this might work if we restrict the '.' separated sorting to 'to one' relationships.  This doesn't make a lot of sense if a book can have multiple authors (to many relationships).  It also requires the data store to do a join that is not compatible with pagination in some circumstances and might be hard for some data stores to perform.  

In summary, I agree if we limit when it can be used and maybe return an error in the other cases.

**Comment by micheljung** [comment]
Workaround: `/authors?sort=name&include=books`

**Comment by IDragonfire** [comment]
May related https://github.com/yahoo/elide/pull/299
