### ISSUE TITLE
How to pass-through JSON data stored as such in the DB?

### ISSUE THREAD

**Issue by pettermahlen** [yahoo/elide#355]
My use case is that I want to store JSON data with a schema that is unknown by my elide service - so not quite schemaless, only schemaless at this layer. According to the JSON API spec, attribute values can be (nearly) any JSON object, not just primitives. However, the simple solution of storing the value as a string in the DB leads to the string getting serialised: 

```
    "data": {
        "attributes": {
            "description": "blablah",
            "facts": "{\"lifecycle\":\"production\"}",
        },
```

Seeing that the Elide serialisation is implemented with Jackson, I tried adding a @JsonRawValue to the JPA entity field, but that didn't work - as far as I can tell, because the `PersistentResource` class simply gets the value without looking at annotations. I think I can see two ways to do this, but I'm not sure which one is best:

1. Store the data in the DB in a `factsString` field, and expose it via a @Transient @ComputedAttribute `facts` method that deserialises it. Not sure how I would filter out the `factsString` field with that solution, or if I can.
1. Change the 'facts' field  into a `Map<String, Object>` and do a custom de/serialisation solution when writing/reading to the DB. Not sure if that would be handled correctly by Elide, but I think so?
1. Change the 'facts' field into a JsonNode and do custom de/serialisation as above. I'm even less sure how that would work.

Any suggestions? Is there maybe an easier way to do this without writing custom code?

**Comment by pettermahlen** [comment]
Answering my own question, I went with this solution:

```
/**
 * JPA converter supporting storing string-format JSON in the database, changing it to a
 * {@code Map<String, Object>} in the model objects.
 */
public class JsonStringConverter implements AttributeConverter<Map<String, Object>, String> {
  private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

  @Override
  public String convertToDatabaseColumn(Map<String, Object> attribute) {
    try {
      return OBJECT_MAPPER.writeValueAsString(attribute);
    } catch (JsonProcessingException e) {
      throw Throwables.propagate(e);
    }
  }

  @Override
  public Map<String, Object> convertToEntityAttribute(String dbData) {
    if (dbData == null || dbData.trim().isEmpty()) {
      return ImmutableMap.of();
    }

    try {
      return OBJECT_MAPPER.readValue(dbData, new TypeReference<Map<String, Object>>() {});
    } catch (IOException e) {
      throw Throwables.propagate(e);
    }
  }
}
```

And 
```
  @Convert(converter = JsonStringConverter.class)
  @Column(length = 15000)
  public Map<String, Object> facts;
```

That seems to work well, based on early testing.

**Comment by DeathByTape** [comment]
Hi @pettermahlen, sorry for the delay! I was out for the last couple of days.

Based on further testing, does this seem to be an acceptable solution still?

**Comment by pettermahlen** [comment]
Yes, so far no problems, so it looks like this could be a good option for others with the same use case. Closing this ticket.
