### ISSUE TITLE
Run Integration Tests with elide-dbmanager-hibernate5

### ISSUE THREAD

**Issue by jkusa** [yahoo/elide#38]
Currently the integration tests only run with the elide-dbmanager-hibernate3. To ensure the quality and  stability of elide-dbmanager-hibernate5, we should run the integration tests with elide-dbmanager-hibernate5 as well.

**Comment by danchen** [comment]
Will be handled in https://github.com/yahoo/elide/pull/63

**Comment by danchen** [comment]
Done.
