### ISSUE TITLE
Entities with non-null attributes

### ISSUE THREAD

**Issue by fabrice-etanchaud** [yahoo/elide#391]
Hi all, and thank you for your powerfull framework, that already saved me a long time just to expose rdbms data in json !

However I found impossible to insert new entities with non-null attributes.
I took a look at the source code : it seems that new entities are persisted first, with all attributes set to their default values, and that attributes and relations are populated afterwards based on the incoming json entity.
Could you confirm please ?
New entities are allocated with a call to newInstance().
Do you think that defining a default constructor that sets attributes to their non null default values could do the trick ?

Best regards,
Fabrice Etanchaud
Groupe FBO

**Comment by DeathByTape** [comment]
We do have a notion of an object [initializers](http://elide.io/pages/guide/05-extension.html#initializers) which will allow you to populate an object with data before it is persisted. Similarly, we have used initializers to bind injection frameworks to our entities too if you wanted to use DI.

Does this help your use case?

For some reason I'm having a bit of trouble understanding the exact issue (may just be a Friday thing/brain not working fully 😄). Would you mind providing a short example?

**Comment by fabrice-etanchaud** [comment]
Here is the problem : The underlying sql table has mandatory not null columns.
As seen in the code, a new entity is :  
1. instanciated (myClass.newInstance())
2. persisted
3. its fields are then populated from the posted json.

So the persistence failed because hibernate cannot insert null values (fields yet to be populated) into not null columns.

I added a default constructor  to the entity where default values are set for not null fields, and it worked.
Thank you for your link on initializers, I will give it a try.

Best regards,
Fabrice
