### ISSUE TITLE
manual IDs cannot be inserted

### ISSUE THREAD

**Issue by fabrice-etanchaud** [yahoo/elide#392]
Hi all again.

I cannot insert any entity with a manual id.

When I use a null Integer, I 've got the following error : 
org.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): 

And if I use primitive 0 int, hibernate complains that the "id cannot be changed after persistence" to its definitive value.

Is it because the entity instance is persisted just after construction, with a default null (Integer) or 0 (int) id ?

Best regards,
Fabrice

**Comment by DeathByTape** [comment]
What does your id generation type look like? Are you using `@GeneratedValue(GenerationType.AUTO)`?

**Comment by fabrice-etanchaud** [comment]
There is not @GeneratedValue annotation, because IDs are manually defined by the client, not the RDBMS.
So how could I set the ID value before the entity to be persisted ?

**Comment by clayreimann** [comment]
Just sending an `id` in your payload should set the ID. We have [some tests](https://github.com/yahoo/elide/blob/master/elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java#L1645) around this. Your payload should look like

```
{
  "data": {
    "id": "my supercool id",
...
}```

**Comment by DeathByTape** [comment]
Additionally, the entity for this test lives here: https://github.com/yahoo/elide/blob/master/elide-integration-tests/src/test/java/example/AssignedIdLong.java

**Comment by DeathByTape** [comment]
Does this solve the issue? If so, I will close the ticket. Thanks!

**Comment by DeathByTape** [comment]
Closing. Please reopen if you're still experiencing this issue.
