### ISSUE TITLE
Upgrade hibernate5 and testng

### ISSUE THREAD

**Issue by DennisMcWherter** [yahoo/elide#415]
During our great dependency upgrade of 2017 (see: https://github.com/yahoo/elide/pull/414), we upgraded most dependencies except hibernate5 and testng. We should upgrade to the latest version. It should be noted that this will take a bit of effort, however. 

At time of writing, for hibernate5 the jump between 5.0.2 to 5.2.8 has many deprecated methods. In fact, the code may still compile in many cases but will now throw deprecated exceptions :( This is a bit sad (as it would be better to know at compile time something is broken), but it will take a bit of digging into to fully upgrade.

For testng we noticed sporadic test failures (perhaps related to `priority` settings?) that appeared to be a result of things running out of order. This should also be further investigated.

**Comment by aklish** [comment]
Hibernate has been upgraded to 5.2.15.  Testng still needed.
