### ISSUE TITLE
Elide Permission / Role System / Security

### ISSUE THREAD

**Issue by IDragonfire** [yahoo/elide#426]
I have a typical permission system (user can be assigned to roles, roles have permissions), similiar to:
http://www.erdiagrams.com/datamodel-rbac-idef1x.html

My idea was to create a permission e.g. `Car.Create` and annotate the `Car` class with a `CreatePermission` check. The backend then checks if the user has the permission `Car.Create` (more exactly: the user has a role that has this permission). 

From the current documentation I must create for every permission a new class:
http://elide.io/pages/guide/03-security.html
and add the `static class Inline extends UserCheck ` to the `ConcurrentHashMap<String, Class<? extends Check>> checks = new ConcurrentHashMap<>()` map.
e.g.
```java
public class HasCarCreate {
  public static final String EXPRESSION = "Car.Create";

  public static class Inline extends UserCheck {
    @Override
    public boolean ok(User user) {
      return user.getOpaqueUser() instanceof MyUserDetails &&
          ((MyUserDetails ) user.getOpaqueUser()).hasPermission(HasBanInfoRead.EXPRESSION);
    }
  }
}
```

```java
    ConcurrentHashMap<String, Class<? extends Check>> checks = new ConcurrentHashMap<>();
    checks.put(HasCarCreate .EXPRESSION, HasCarCreate .Inline.class);
    EntityDictionary entityDictionary = new EntityDictionary(checks);
```

Is there a better way or a different approach?

**Comment by DeathByTape** [comment]
Currently, I believe the only way to do this is through a class-per-permission. Admittedly, this is a bit clunky. How we have currently mitigated the pain for this process in our system is by doing something as follows:


```java
       /**
        * Implementation of permission check
        */
        public static class MyUserRole extends RoleBasedPermissionCheck {
		public MyUserRole() {
			super(PermissionRoles.MyUserRolePermission);
		}
	}

        /**
         * Foundation class for all of these roles
         */
        public static abstract class RoleBasedPermissionCheck extends UserCheck {
                private final String userRole;

		private RoleBasedPermissionCheck(String roleName) {
                        userRole = roleName;
		}

                @Override
                public boolean ok(User user) {
                        return user.getOpaqueUser() instanceof MyUserDetails
                                   && ((MyUserDetails ) user.getOpaqueUser()).hasPermission(userRole);
                }
	}
```

That being said, I have a sneaking suspicion that we can clean this up a bit further with some lambda magic in Java8. Let me think about it for a bit and I'll follow up shortly.

**Comment by IDragonfire** [comment]
Thanks for the fast replay ;)

**Comment by clayreimann** [comment]
@IDragonfire did something like this work for you? 

@DennisMcWherter anything else to add?

**Comment by aklish** [comment]
Elide 5 has the following prefabbed check class:

https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/security/checks/prefab/Role.java#L38-L48
