### ISSUE TITLE
Deploying elide on Wildfly server

### ISSUE THREAD

**Issue by mnardellis** [yahoo/elide#427]
Are there any examples or guides explaining how to use elide in a Wildfly Server? I'm trying to build an example running on that server, but so far I couldn't get it to work. Any info or guidance now would be appreciated.
Thanks

**Comment by clayreimann** [comment]
To my knowledge nobody has used Elide in Wildfly (and I'm not familiar with that container in particular) but people have successfully run Elide in JBoss's RESTEasy so I would image that it's would be compatible. 

Have you looked at the [JsonApiEndpoint](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java) class? It's ready to be mounted by most containers.

**Comment by mnardellis** [comment]
Thanks for the reply.

I tried to run th resteasy example that is in the exmples directory, but couldn't make it work. It seem the version of the parent pom is wrong (3.0.0-SNAPSHOT, current one seems to be 3.0.3-SNAPSHOT). The elide dependencies in the example also seem to be wrong (2.3.14-SNAPSHOT). I changed them to 3.0.3-SNAPSHOT, but the code seems to be using some old classes that don't exist in this version (PersistenceStore.java, for instance).

I'll try to look at the JsonApiEndpoint class, as you suggested, to see if I can make it work on Wildfly.

**Comment by clayreimann** [comment]
We should probably go through and do a sweep for stuff like that. There are a few sub-modules that we don't actively use ourselves and have probably become stale.

**Comment by mnardellis** [comment]
Ok, I looked at the JsoApiEndpoint class e made it work on wildfly.

I've had to provide 2 named beans, one @Named("elide") Elide and one @Named("elideUserExtractionFunction") DefaultOpaqueUserFunction, but I guess that is expected (because of the  injection on the JsonApiEndpoint constructor)

The only real problem I've had was with the method "deleteWithoutBody", in class JsonApiEndpoint. It's annotated with @Consumes("") and that gives an error when the Jax-rs implementation (resteasy) tries to parse the media type definition. I had to remove this annotation to make it work. Is it really necessary to use this annotation without a valid Media Type? Can it be removed?

**Comment by DeathByTape** [comment]
Hi @mnardellis I believe we [had problems with this before](https://github.com/yahoo/elide/pull/322). I'll take a look at removing it and making sure that the example code gets automatically built along with everything else. We must not have added it to the testng.xml :(

**Comment by DeathByTape** [comment]
Sorry for the delay, but I have something that seemingly fixes the issue here and behaves as intended: https://github.com/yahoo/elide/pull/436

Does that fix up your issues?
