### ISSUE TITLE
Not able to run examples because of SNAPSHOT upgrade

### ISSUE THREAD

**Issue by pitlv2109** [yahoo/elide#431]
Fails when running `mvn exec`

> The POM for com.yahoo.elide:elide-datastore-hibernate5:jar:3.0.2-SNAPSHOT is missing, no dependency information available
> [ERROR] Failed to execute goal on project elide-blog-example: Could not resolve dependencies for project com.yahoo.elide:elide-blog-example:jar:3.0.2-SNAPSHOT: The following artifacts could not be resolved: com.yahoo.elide:elide-annotations:jar:3.0.2-SNAPSHOT, com.yahoo.elide:elide-core:jar:3.0.2-SNAPSHOT, com.yahoo.elide:elide-datastore-hibernate5:jar:3.0.2-SNAPSHOT: Could not find artifact com.yahoo.elide:elide-annotations:jar:3.0.2-SNAPSHOT -> [Help 1]

**Comment by aklish** [comment]
A couple of points:

I don't think that repo supports the exec build phase.  

Second, if you want to use SNAPSHOT builds, you have to run `mvn install` at the top level.  Then you can go into elide-example and your maven commands should work.

Hope that helps.

**Comment by DeathByTape** [comment]
The [README](https://github.com/yahoo/elide/tree/master/elide-example/elide-blog-example) in the example directories should have detailed instruction on running these examples. :)

It is worth noting that the resteasy example is currently broken (and the README for one). I have a PR here which should be merged soon to fix this: https://github.com/yahoo/elide/pull/436
