### ISSUE TITLE
Unable to run mvn command in elide-blog-example

### ISSUE THREAD

**Issue by akashdeepdeb** [yahoo/elide#435]
Even though I was able to do this properly a while ago, with the newest commit, the command:
`mvn exec:java -Dexec.mainClass="com.yahoo.elide.example.persistence.Main"` throws the following errors:

**[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Elide Example: Persistence API with Security 3.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ elide-blog-example ---
[WARNING] 
java.lang.ClassNotFoundException: com.yahoo.elide.example.persistence.Main
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:270)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.976 s
[INFO] Finished at: 2017-03-16T20:57:42-05:00
[INFO] Final Memory: 21M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project elide-blog-example: An exception occured while executing the Java class. com.yahoo.elide.example.persistence.Main -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException**

This is an issue in the blog-example in elide/elide-example.

**Comment by DeathByTape** [comment]
Thank you for reporting this. Our `README` is out of date :( I have a PR to fix this here: https://github.com/yahoo/elide/pull/436

In any case, you should actually use this command to run the example:

```
$ mvn exec:java -Dexec.mainClass="com.yahoo.elide.example"
```
