### ISSUE TITLE
JPA-annotations on fields lead to infinite recursion

### ISSUE THREAD

**Issue by Brutus5000** [yahoo/elide#443]
Hi there,

I could not find any hint in the docs whether JPA-annotation on field level are allowed.
However, on adding Elide to my project I ran into unexpected infinite recursions. I reduced it to a minimum example of a Parent and a Child class with a OnToMany relationship.

```
@Entity
@Data
@Include(rootLevel = true)
public class Parent {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @OneToMany(mappedBy = "parent")
    private Collection<Child> childs = new ArrayList<>();
}
```

```
@Entity
@Data
@Include(rootLevel = true)
public class Child {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @ManyToOne
    @JoinColumn(name = "fk_parent")
    private Parent parent;
}
```

This results in the following error (my package names removed):

> {
>   "timestamp": 1492381448173,
>   "status": 500,
>   "error": "Internal Server Error",
>   "exception": "java.lang.IllegalArgumentException",
>   "message": "Infinite recursion (StackOverflowError) (through reference chain: Parent[\"childs\"]->org.hibernate.collection.internal.PersistentBag[0]->Child[\"parent\"]->Parent[\"childs\"]->org.hibernate.collection.internal.PersistentBag[0]->Child[\"parent\"]->Parent[\"childs\"]->org.hibernate.collection.internal.PersistentBag[0]->Child[\"parent\"]->Parent[\"childs\"]-
> ....
> }

Moving the annotations to properties removes the error. However, using JPA-annotation on properties leads to non-Elide related difficulties.

**Comment by aklish** [comment]
@Brutus5000 - Thanks for filing the issue.

I was able to reproduce the problem with your snippet of code above.  It looks like there is a bug in Elide when we bind entities into the EntityDictionary.  Elide assumes property level access and does not see the relationship annotations on the fields.  It then treats the relationship as an attribute.  Later when it tries to JSON serialize the data, it ends up in a cycle.

The fix will likely change the entity binding to pay attention to whether the entity is using FIELD or PROPERTY access type and suck up the JPA annotations accordingly.

This is a good catch.  You can tell we don't use FIELD level access internally (none of our tests do this).

**Comment by Brutus5000** [comment]
🥇 
Thanks for the fix.
