### ISSUE TITLE
HibernateStore#getSession return not current session

### ISSUE THREAD

**Issue by IDragonfire** [yahoo/elide#461]
https://github.com/yahoo/elide/blob/a3c03599584f381be929774ef1da703f6fcf4c0a/elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateStore.java#L106

returns NOT the current Session when a transaction is already started, instead internally a new session is created (https://github.com/spring-projects/spring-framework/blob/54004e0d78dd92c62429999b77befbc9d9fcdb68/spring-orm/src/main/java/org/springframework/orm/hibernate5/SpringSessionContext.java#L121). Therefore transactions around test methods have an unexpected behaviour ...

# How to reproduce
1. Clone this project https://github.com/IDragonfire/spring-boot-jpa-elide
2. Run the tests
 * `Test.java` return the the correct created data  (correct)
 * `TransactionalTest.java` return no data (fail)

# Expected behaviour
If your test has a `@Transactional` annotation, it will rollback the transaction at the end of each test method.

# Current behaviour
If your test has a `@Transactional` annotation, Elide use a different session. Therefore Elide has no access to the data from the outer test transaction. In the best case you get only outdated data, under certain situation you get also an `InvalidObjectIdentifierException`. https://github.com/FAForever/faf-java-api/issues/71
The transaction of elide executes no rollback at the end of the test method.

From my viewpoint the current implementation can be usefull to avoid nested transaction + handling and normally you have no transaction around an elide call .... 
For Tests the 'broken' transaction behaviour is annoying because after each test you must manually clean up the datastore ...

Did I miss any configuration option?

# Data
* Hibernate 5
* Spring Boot 1.5.2
* Elide 3

**Comment by DeathByTape** [comment]
Hi there, sorry for the delay. I should have some spare cycles to investigate this soon I hope. In the meantime, if anyone else has ideas feel free to chime in :)

**Comment by IDragonfire** [comment]
In the test is used `Session session = entityManager.unwrap(Session.class);` to get the session from the entitymanager to proof that `Elide` grabs the wrong one ...
Maybe add a config to grab the session optional from the `entityManager`?

**Comment by DeathByTape** [comment]
That sounds like a reasonable option to me. For an immediate-term solution, would it help to subclass the datastore and change the session that is returned?

I am trying to think of a good way to express this option generically since one can have multiple datastores in Elide. Perhaps using something like:

```java
Function<Object, Object> getSession;
```

An example implementation would be like:

```java
Function<Object, Object> getSession = (someDiscriminatingData) -> {
  if (someDiscriminatingData.equals("hibernate")) {
    return new HibernateSession();
  } else {
    return new RedisSession();
  }
};
```

@aklish, @clayreimann thoughts?

**Comment by DeathByTape** [comment]
@IDragonfire I have submitted a preliminary PR here, would this solve your issue? https://github.com/yahoo/elide/pull/469

**Comment by IDragonfire** [comment]
Without testing I cannot say it ...

**Comment by DeathByTape** [comment]
@IDragonfire I skipped over the fact that you provided an example repo when I first went through this. I was able to pull that down and look at this locally. I believe my proposed change will fix this for you. The one thing that seems to be important is that Elide and the tests are using the _same_ `EntityManager`, however.

See the PR I left on your example repo: https://github.com/IDragonfire/spring-boot-jpa-elide/pull/1

Please note, however, PR #469 is not yet fully baked and ready to go in. There are some problems we're still experiencing with this approach that need to be worked out.

**Comment by IDragonfire** [comment]
@DeathByTape Thank you very much for your fast reply! Also thanks for the snapshot warning, I know good stuff need time ;)
I will test the latest snapshot on our project and see if we discover any problems.

**Comment by IDragonfire** [comment]
@DeathByTape I am not able to `install` the snapshot of the PR from elide ...
https://github.com/IDragonfire/elide/tree/entityManagerStore
 
Any install steps needed?

```java
[INFO] Elide: Parent Pom ................................. SUCCESS [2.830s]
[INFO] Elide: Annotations ................................ SUCCESS [7.349s]
[INFO] Elide: Core ....................................... SUCCESS [36.628s]
[INFO] Elide Data Store: Parent Pom ...................... SUCCESS [0.038s]
[INFO] Elide Data Store: Hibernate Common ................ SUCCESS [3.358s]
[INFO] Elide: Integration Test Library ................... SUCCESS [8.280s]
[INFO] Elide Data Store: Hibernate 5 ..................... FAILURE [0.235s]
[INFO] Elide Data Store: Hibernate 3 ..................... SKIPPED
[INFO] Elide Data Store: In-Memory ....................... SKIPPED
[INFO] Elide Data Store: Multiplex Library ............... SKIPPED
[INFO] Elide Data Store: No-Operation Library ............ SKIPPED
[INFO] Elide Example: Parent Pom ......................... SKIPPED
[INFO] Elide Example: Hibernate 3 API with MySQL ......... SKIPPED
[INFO] Elide Example: Hibernate5 API with Security ....... SKIPPED
[INFO] Elide Example: Hibernate5 API with Security (Resteasy)  SKIPPED
[INFO] Elide Contrib: Parent Pom ......................... SKIPPED
[INFO] Dropwizard Elide .................................. SKIPPED
[INFO] Elide Example: Elide with Dropwizard .............. SKIPPED
[INFO] Elide Swagger ..................................... SKIPPED

[ERROR] Failed to execute goal on project elide-datastore-hibernate5: Could not resolve dependencies for project com.yahoo.elide:elide-datastore-hibernate5:jar:3.0.7-SNAPSHOT: Could not find artifact com.yahoo.elide:elide-integration-tests:jar:tests:3.0.7-SNAPSHOT -> [Help 1]
```

**Comment by DeathByTape** [comment]
Absolutely; I've been out the last couple of days, but plan to get back to fix this soon.

**Comment by DeathByTape** [comment]
Sorry for such a delay. I have updated the PR and have completed the work. I noticed that there is a slight problem with test __execution__ so I will work a bit to fix the kinks with the maven build, but in isolation everything looks good now.

**Comment by DeathByTape** [comment]
The change is now merged. We should be able to cut a new release shortly with this new entitymanager store in the build (it should be v3.0.7)
