### ISSUE TITLE
InvalidAttributeException when POST body includes ComputedAttribute

### ISSUE THREAD

**Issue by scathers** [yahoo/elide#481]
I have a ComputedAttribute in my endpoint, similar to this:
```java
@Transient
@ComputedAttribute
public String getPhotoUrl(){
  return "www.test.com/images/" + id + ".png";
}
```
When my client sends a POST request to create a new object, it includes the `photoUrl` property, but this in turn causes a `404 Not Found` response with the following error:
```json
{"errors":["InvalidAttributeException: Unknown attribute 'photoUrl' in 'widgets'"]}
```
The only way I am able to overcome this is by filtering out the property on the client side so that it is not sent in the POST body, but this is inconvenient; I'm hoping there's a way to make Elide simply ignore a read-only computed attribute that's sent in a POST request. Is there a way to do this?

**Comment by DeathByTape** [comment]
We've seen this issue before. The short fix is to add an _empty_ setter for your `photoUrl`. Namely,

```java
public void setPhotoUrl() {
    // Do nothing.
}
```

I know if you're using Hibernate, it will require a setter for all getters. Looking at the [JPA spec](http://download.oracle.com/otn-pub/jcp/persistence-2.0-fr-eval-oth-JSpec/persistence-2_0-final-spec.pdf?AuthParam=1497974034_ab4c0d34d25bb36b42c884e30ff2656e), we interpreted the following as a getter and setter **must** be provided:

> In this case, for every persistent property property of type T of the entity, there is a getter method, getProperty,
and setter method setProperty. For boolean properties, isProperty may be used as an alternative
name for the getter method.[2]

and

> The embedded id attributes that correspond
to the relationship are treated by the provider as “read only”—that is, any updates to them on
the part of the application are not propagated to the database.

That being said, adding empty setters is admittedly a bit clunky. We may be able to look into reworking this requirement for `@Computed*` fields.

**Comment by scathers** [comment]
Thanks for such a quick response!

Adding an empty setter was my first idea, but I realize I made an invalid setter, which is why it wasn't working; mine looked like `setPhoto()` instead of `setPhoto(String unused)`.

Is it possible this tip should be added to the documentation on ComputedAttributes?
https://github.com/yahoo/elide-doc/blob/gh-pages/pages/guide/05-extension.md#simple-translations

Really appreciate all the great work you guys do on this project. It's made hooking up an Ember frontend with a Spring Boot backend a (mostly) pleasantly simple process.

**Comment by DeathByTape** [comment]
Great suggestion. I have added the PR here: https://github.com/yahoo/elide-doc/pull/43

Glad you're enjoying Elide so far! :) Please keep the questions/suggestions/bug reports coming in as you find them!

I'll close this issue for now (with the fix being the doc update) but feel free to reopen for any related reason.
