### ISSUE TITLE
Update lifecycle hook annotations

### ISSUE THREAD

**Issue by DennisMcWherter** [yahoo/elide#490]
We should have add 2 different things to our annotations (and the corresponding support for the changes in Elide). Namely, a numeric `rank` value which will allow us to specify hook execution order for multiple hooks on the same lifecycle and enable list of fields to be specified rather than a only a single field. By allowing a list of fields we can remove redundancy required today in requiring a new method per field to trigger a hook.

**Comment by aklish** [comment]
List of field support is there now in Elide 5.  Rank does not exist however.  The order of the hook invocations is likely in relation to how the client made the request (order of fields).
