### ISSUE TITLE
"Totals" not work with "Joined Filter Syntax"

### ISSUE THREAD

**Issue by songoo** [yahoo/elide#491]
Hello when i use "Joined Filter Syntax" which is enabled with "withJoinFilterDialect", filters works as expected but it get crashed when i add "totals" in pagination settings :

works:
`page: {size:10, number: this.get("page")}`  
does not work :
`page: {size:10, number: this.get("page"), totals: true},`

Resulting in error :
```
{
  "errors":[
    "InternalServerErrorException: org.hibernate.QueryException: illegal attempt to dereference collection [document0_.ticket_id.staffs] with element property reference [id] [SELECT COUNT(*) FROM models.Document Document WHERE (Document.documentType.id IN (:documentType_id_41c7708c) AND (Document.staffs.id IN (:staffs_id_8526eb6c) OR Document.managers.id IN (:managers_id_2a48f153)))]"
  ]
}
```

Here are query parameters :

```
filter:documentType.id==1;(staffs.id==116,managers.id==116)
page[size]:10
page[number]:1
page[totals]:true
sort:-createdAt
```

**Comment by DeathByTape** [comment]
I can look into this soon, but I may defer to @aklish in the meantime as he has the most experience working with the `pageTotals` code.

**Comment by aklish** [comment]
Without getting into the details, it looks like this particular query is attempting to paginate a collection (Document) while also joining (via filters) to another, toMany collection (staffs).  Does that sound correct?

There is no easy way in Hibernate to paginate across a join with a toMany relationship.   The result set that comes back will duplicate document rows (one row per staff) - and Hibernate doesn't handle that correctly.   As a result, Elide doesn't support that scenario with its Hibernate DataStore. 

That said, the count query shouldn't blow in this way.  We should think about how Elide should handle joins across toMany relationship - should we allow them at all?  Should we allow them but not allow pagination?

**Comment by aklish** [comment]
I'm working on a fix that will allow totals to work in conjunction with joined filters.  Caveat though - there still is no workaround to get Hibernate to paginate correctly through a toMany relationship.

**Comment by aklish** [comment]
I'm closing the issue for now.  If there is still a problem, please reopen.

**Comment by songoo** [comment]
Its working, thnx much ^__^
