### ISSUE TITLE
How to order null values first/last

### ISSUE THREAD

**Issue by songoo** [yahoo/elide#492]
Hi.
While setting order for example 
`"sort":  "-deliveryAt"`
Is it possible to order results with null value in deliveryAt as first or last ? Or any way around .

**Comment by DeathByTape** [comment]
I apologize for incredibly long delay on this; I simply must have overlooked this question :(

There is no "out of box" solution for altering the existing sort methods. However, you could look into augmenting the [DefaultFilterDialect](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/DefaultFilterDialect.java#L30) to behave the way you intend (assuming you don't want to roll your own completely).

When you subclass this and modify it, you just specify your sorting implementation in the `ElideSettingsBuilder` to activate it in your configuration.

Please let me know if anything is unclear!

**Comment by songoo** [comment]
We had to override those classes to get it working.

HibernateStore, HibernateTransaction, RootCollectionFetchQueryBuilder("getSortClause" method), Sorting.

Thnx, for help, you can close this issue :)

**Comment by DennisMcWherter** [comment]
Great, glad you got it working! :)
