### ISSUE TITLE
How to set up an Initializer?

### ISSUE THREAD

**Issue by Brutus5000** [yahoo/elide#521]
Hi there,

as there is no example for implementing an initializer, I just gave it a try.
Unfortunately my initializer is not used, whether I put it into the entityDictionary of the DataStore or of the ElideSettingsBuilder.

I have tried GETing an existing collection and POSTing a new entity.
Can you give me a hint what I am doing wrong?
Another question: When is the Initializer supposed to be fired? On loading of each entity or only on creation/commit?

Below you can find my Configuration:

```
@Configuration
@Slf4j
public class ElideConfig {
    @Bean
    public Elide elide(EntityManagerFactory entityManagerFactory) {
        ConcurrentHashMap<String, Class<? extends Check>> checks = new ConcurrentHashMap<>();
//        checks.put("user is a superuser", AdminCheck.class);

        EntityDictionary entityDictionary = new EntityDictionary(checks);
        RSQLFilterDialect rsqlFilterDialect = new RSQLFilterDialect(entityDictionary);

        entityDictionary.bindInitializer(new Initializer<ProductClass>() {
            @Override
            public void initialize(ProductClass productClass) {
                log.info("initializing ProductClass "+productClass);
            }
        }, ProductClass.class);

        HibernateStore hibernateStore = new HibernateStore.Builder(entityManagerFactory.unwrap(SessionFactory.class)).build();
        hibernateStore.populateEntityDictionary(entityDictionary);

        return new Elide(new ElideSettingsBuilder(hibernateStore)
                .withAuditLogger(new Slf4jLogger())
                .withEntityDictionary(entityDictionary)
                .withJoinFilterDialect(rsqlFilterDialect)
                .withSubqueryFilterDialect(rsqlFilterDialect)
                .build());
    }
}

```

**Comment by aklish** [comment]
Did you call ```entityDictionary.bindEntity``` on ProductClass somewhere?

**Comment by aklish** [comment]
Here is another more complicated example that we use in our production servers.  We use Jersey (which has HK2 for dependency injection).  We bind HK2's ```ServiceLocator::inject``` method as our initializer for every class:

To do this, we override the ```HibernateStore``` and do our own entity bindings as follows:
```
    @Override
    public void populateEntityDictionary(EntityDictionary dictionary) {
        /* bind all entities */
        for (ClassMetadata meta : getFactory().getAllClassMetadata().values()) {
            Class mappedClass = meta.getMappedClass(EntityMode.POJO);

            dictionary.bindEntity(mappedClass);

            dictionary.bindInitializer(injector::inject, mappedClass);
        }
        this.dictionary = dictionary;
    }
```

This allows us to just add ```@Inject``` to the beans.

Technically, we use both patterns (prior example and this one) in prod.

**Comment by aklish** [comment]
Let me know if this resolves your issue.  Thanks.

**Comment by Brutus5000** [comment]
Hi aklish,

thanks for your effort. Binding the entity before binding the initializer did the job.
The example on the docs is a bit misleading here, as it indicates that `bindInitializer` binds the entity.

```
        /* Bind the initializer to Foobar.class */
        dictionary.bindInitializer(foobarInitializer, Foobar.class)
```

Except for the initializer, Elide seems to work flawlessly without binding an entity. If the binding is only required for the initializer, wouldn't it make sense to put it both into the same call?

**Comment by aklish** [comment]
It seems like the initializer was bound before the entity was bound.  This
is definitely confusing.  We'll probably patch the code to rectify this as
you suggest.  Thanks!

Aaron
