### ISSUE TITLE
Support for Encrypted ID's

### ISSUE THREAD

**Issue by DennisMcWherter** [yahoo/elide#522]
We should add support for encrypted and/or obfuscated id's. This could be enabled through the builder and allow the users to provide an obfuscation/encryption mechanism. Similarly, we should provide a sane, efficient, default implementation.

**Comment by chaudharydeepak** [comment]
@DennisMcWherter - I would like to help if its ok? Please guide to documentation or code to get started with this. Thank you.

**Comment by aklish** [comment]
I think the right approach here is to use Elide Serde's and create a new type:

```java 
class ObfuscatedId<T> {
    T id;
}
```

Models could then be decorated like:

```java
class Book {
    @Id
    @Embedded
    private ObfuscatedId<Long> id;
}
```

Then we just need to create an [Elide Serde](https://elide.io/pages/guide/v4/09-clientapis.html#type-coercion) to coerce the Obfuscated ID to a string for JSON-API and GraphQL.

Check out the section:
https://elide.io/pages/guide/v4/02-data-model.html#model-identifiers

For an example of how to create a Serde for a composite ID for an Address.

Does this make sense?

**Comment by chaudharydeepak** [comment]
Thank you @aklish. I will spend sometime today on this & get back to you if I have any further questions.

**Comment by aklish** [comment]
👍

**Comment by aklish** [comment]
A few other useful bits of info:

Elide 5 (elide-5.x branch) supports the ability to inject Serdes:
https://github.com/yahoo/elide/blob/elide-5.x/elide-core/src/main/java/com/yahoo/elide/Elide.java#L110

This would allow the injection of security credentials into the Serde to do encryption.

Elide 5 docs are in pre-release right now, but you can find them here:

https://elide.io/pages/guide/v5/01-start.html

While this work can be done on master or the elide-5.x branch - there will be more options to obfuscate the IDs in 5 with injection.

**Comment by chaudharydeepak** [comment]
Thank you @aklish - can you pls share a use case to use encrypted ID? are we saying thus could be any field that needs to be stored as encrypted for sensitive user data - SSN / credit cards etc?

**Comment by aklish** [comment]
The primary use case is to prevent leakage of information.  Let's say I have a new website with a customer model.  I store my customer model with JPA using monotonically increasing identifiers (1,2,3,...).  

If elide exposes this ID directly, a competitor can create a customer account and determine how many other customers my website has.

There are workarounds to this problem, but the most elegant solution is to store a single ID (a long or integer) but expose through the API something that is obfuscated.

If implemented, we ought to also submit a documentation PR to elide-doc in the security section which would count as another hacktoberfest PR.

**Comment by chaudharydeepak** [comment]
@aklish Thank you for the clarification - this is very helpful.

**Comment by cgendreau** [comment]
I know this ticket is getting old but I'm looking for something similar to what @aklish mentioned in https://github.com/yahoo/elide/issues/522#issuecomment-712198702
Internal database identifiers are not exposed and UUIDs are generated on record creation. So, the main difference is that a lookup is necessary since we can't compute the identifier from the UUID.
We are currently using a solution with Hibernate NaturalId but I was wondering if Elide can support such use case?
