### ISSUE TITLE
Support for custom HTTP response codes

### ISSUE THREAD

**Issue by niketh** [yahoo/elide#556]
We had a requirement to return custom HTTP codes when the JsonAPI returns. This is not currently supported. I had a few thoughts around how this can be implemented.

My proposal is to have annotations that can catch custom exceptions and have an http code mapped to that. So we can have an annotation 

`@httpError (exception = "RedirectException", code = HTTP.307, message = "Redirecting url")`

1. RedirectException thrown in the code might be configured via the annotation to throw a 307
2. IAE can be made to throw a 4xx
3. Detailed validation errors and messages can be thrown too.

Would love to contribute if this is a valid use case.

**Comment by clayreimann** [comment]
Can you explain a little more what your use case is? JSON API is pretty specific about what status codes should be returned. Is there a reason that the calling application can not implement this behavior?

**Comment by niketh** [comment]
The use case that i am looking for is this - "I have a workflow which updates my mysql store based on the progress that the worflow has made. When the worflow has not finished i want to be able to return back 200 OK. When the workflow has finished, i want to redirect my users to another endpoint by sending a 307"

**Comment by DennisMcWherter** [comment]
If you control your clients, a simple workaround would be to make this a computed attribute where the value is redirect uri and have the client forward.

On the other hand, to implement this as a first-class feature, we would have to think through the use-cases and where it makes the most sense to provide such a hook for the user. Response "transform hooks" feel like a fair ask to me, but it would be worth going through and verifying that we don't already have support for this through another mechanism. The bigger question, however, is what kind of information would a transformation require to be useful (i.e. `RequestScope`, `User`, etc.).

In any case, would you be able to achieve the effect you're looking for if you rolled your own version of [JsonApiEndpoint](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java#L37)? You could likely just wrap it and transform the response before it gets returned to the caller.

An off-the-cuff example may be something like:

```java
public class MyEndpoint extends JsonApiEndpoint {
  ...
  @GET
  public Response get(...) {
    Response result = super.get(...);
    return myTransform(result);
  }
  ...
```

One thing that could make this better if we actually exposed [JsonApiEndpoint#build](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java#L124) as a protected method. In that case, you could literally transform the `ElideResponse` object into anything you want by just overriding that method.

Let me know if this helps or if we should explore a different solution.

**Comment by clayreimann** [comment]
It sounds as if you're modeling a job as an object in your API. Not inherently bad, so why not have an api like so? (Beans modeled with fields for conciseness)

```java
class Workflow {
  public long id;
  public State state; // PENDING, IN_PROGRESS, DONE, ERROR…
  public Result result;
}

class Result {
  public long id;
  // your expensive things here
}
```

Some routes:
```
/workflow - list all running workflows
/workflow/ID - check the progress of a workflow
/workflow/ID/result - get the result of a workflow
/result - list all results generated by workflows
/result/ID - get the results of a workflow
```

This would allow you to craft a query like `/workflow/1?include=result`. This query would give you the status of the workflow, and if it's done the result too.

**Comment by DennisMcWherter** [comment]
Any update on this?

**Comment by clayreimann** [comment]
Summary from offline discussion with @niketh:

Actually, digging into this I believe if you craft your beans properly you can get this behavior today. [Elide.java](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/Elide.java#L227-L228)  just rethrows any `WebApplicationException` so if you throw `new WebApplicationException(Response.status(307)…)` the servlet container *should* just do the right thing.

**Comment by DennisMcWherter** [comment]
Great, will close in the meantime. Please reopen if this becomes an issue later.
