### ISSUE TITLE
Documentation lacking Security examples

### ISSUE THREAD

**Issue by scathers** [yahoo/elide#605]
I'm trying to understand the [Security](http://elide.io/pages/guide/03-security.html) documentation, but it seems to be lacking example code. In some cases it appears that there's supposed to be code, but it's missing, such as in the [Permission Annotations](http://elide.io/pages/guide/03-security.html#permission-annotations) section.

Is there an example application or anything to look at to see how to apply the various kinds of checks?

**Comment by DennisMcWherter** [comment]
Sorry for the delay; I was looking at this last night and my power went out!

Anyway, thanks for bringing this up! I have restored the example code. Can you please let me know if that's sufficient? If not, I will go through a deeper explanation here if necessary and we can work to convert that into better documentation so it's less confusing in the future.

Thanks!

**Comment by DennisMcWherter** [comment]
To your second question, however, we do have an [example project here](https://github.com/DennisMcWherter/elide-example-blog-kotlin). The example is in Kotlin but hopefully shouldn't be too mentally taxing to convert to java. It doesn't have any `FilterExpressionCheck`s if I recall, but it is relatively complete.

**Comment by scathers** [comment]
Thanks, that's very helpful. I was able to figure it out eventually by searching through the tests in the repo, but that section of example code you restored looks like it does a good job of giving the basics. I also think your example project is a great resource; perhaps you should consider linking to it directly from the Security session. Much appreciated.
