### ISSUE TITLE
HibernateTransaction#save does excessive saveOrUpdate call

### ISSUE THREAD

**Issue by belovaf** [yahoo/elide#607]
As I can see, object passed to HibernateTransaction#save is always in attached state.
Calling saveOrUpdate(object) on attached object is excessive.
Should HibernateTransaction#save just do nothing?

**Comment by DennisMcWherter** [comment]
Hi @belovaf, so we actually don't call `saveOrUpdate` when we hit the transaction `save` method. We queue up an action to it and add that to a set. When `commit` is called, these actions are executed all at once; this was basically to guarantee we don't miss any objects iirc.

@wcekan do you recall why we thought this was necessary and/or harmless?

In any case, if you're noticing issues with this in the meantime, you can override the HibernateTransaction and change this method as you like.

**Comment by belovaf** [comment]
When you fetch entity with a **JPQL query** or the **find** method of the EntityManager, the entity will in **managed** lifecycle state.
When you flush the persistence context, EntityManager will automatically detect changes of all managed entities and perform the required SQL statements.
You don’t need to, and you **should not** call Hibernate’s saveOrUpdate method after you updated an entity. That triggers an additional SaveOrUpdate event without providing any benefits.

If you replace HibernateTransaction#save method with
```
@Override
public void save(Object object, RequestScope scope) { /*empty body*/ }
```
nothing will change. Just try! :)

Sure i can override this implementation, but I think the default implementation should not contain excessive code.

**Comment by aklish** [comment]
I'm not sure when this was fixed, but Elide 6 no longer has this issue (hibernate stores have been retired and JPA store does the following):

```
    @Override
    public <T> void save(T object, RequestScope scope) {
        deferredTasks.add(() -> {
            if (!em.contains(object)) {
                em.merge(object);
            }
        });
    }
```

It only calls save/merge if the object is not managed.
