### ISSUE TITLE
Batch update failed when update one resource and link it with another new resource

### ISSUE THREAD

**Issue by belovaf** [yahoo/elide#608]
I try to play with [Getting Started](https://github.com/clayreimann/elide-demo) tutorial.
Model is very simple: ArtifactGroup <--OneToMany--> ArtifactProduct.

1) Create new ArtifactGroup without relations:
```
{"data": {
   "type": "group",
   "id": "g5",
   "attributes":    {
      "commonName": "New Common Name",
      "description": "New Description"
   },
   "relationships": {"products": {"data": []}}
}}
```

2) Replace group "g5" and add new product to it:
```
[
  {
    "op": "replace",
    "path": "/group/g5",
    "value": {
      "id": "g5",
      "type": "group",
      "attributes": {
        "commonName": "updated name",
        "description": "updated description"
      },
      "relationships": {
        "products": {
          "data": [ { "id": "p5", "type": "product"} ]
        }
      }
    }
  },
  {
    "op": "add",
    "path": "/group/g5/products",
    "value": {
      "id": "p5",
      "type": "product",
      "attributes": {
        "commonName": "Product 5",
        "description": "Product Description 5"
      },
      "relationships": {
        "group": {
          "data": { "id": "g5", "type": "group"}
        }
      }
    }
  }
]
```

Second request returns error:
```
{"errors": [
      {
      "detail": "Unknown identifier 'p5' for product",
      "status": 404
   },
   {"detail": "Operation not executed. Terminated by earlier failure."}
]}
```

**Comment by DennisMcWherter** [comment]
Sorry for the delay on this; with the holiday's things have been a bit crazy. 

Can you give a sample of what your models look like with annotations? At a glance, the query looks valid to me.

**Comment by belovaf** [comment]
Model is exact copy of [https://github.com/clayreimann/elide-demo](https://github.com/clayreimann/elide-demo/tree/master/src/main/java/com/example/repository/beans).
You can reproduce this issue without any changes to this tutorial.

**Comment by DennisMcWherter** [comment]
Great, thanks for the pointer. This appears to be a weird artifact of a cyclic reference; will have to dig deeper to determine the exact cause as this request _should_ work. The short-term workaround is to merely omit `relationships` block on your group update. Instead, this will automatically get updated when you create the product through the path.
