### ISSUE TITLE
PersistentResourceFetcher constructor should be public

### ISSUE THREAD

**Issue by Serg-de-Adelantado** [yahoo/elide#621]
I am trying to implement a GraphQL API executor bean in Kotlin, like this:
```kotlin
@Bean
fun elideGraphQlApi(elide: Elide): GraphQL {
    val fetcher = PersistentResourceFetcher(elide.elideSettings)
    val builder = ModelBuilder(elide.elideSettings.dictionary, fetcher)
    return GraphQL(builder.build())
}
```
Since `PersistentResourceFetcher` constructor is not strictly marked as public, it is not accessible for Kotlin(nor Java) compiler.

**Comment by clayreimann** [comment]
Can you share your use case? I don’t think we anticipated people would need to override or extent this class.

**Comment by Serg-de-Adelantado** [comment]
@clayreimann I am trying to add Elide-based GraphQL API to existing Spring Boot application. Here is my current configuration:
```kotlin
@Transactional
@Configuration
class ElideConfig {
    @Bean
    fun elideDataStore(sessionManager: EntityManagerFactory): AbstractHibernateStore {
        return AbstractHibernateStore.Builder(sessionManager.unwrap(SessionFactory::class.java)).build()
    }

    @Bean
    fun elide(dataStore: AbstractHibernateStore): Elide {
        val entityDictionary = ElideEntityDictionary(emptyMap())
        val filterDialect = RSQLFilterDialect(entityDictionary)

        return ElideSettingsBuilder(dataStore)
                .withUseFilterExpressions(true)
                .withEntityDictionary(entityDictionary)
                .withJoinFilterDialect(filterDialect)
                .withSubqueryFilterDialect(filterDialect)
                .withAuditLogger(Slf4jLogger())
                .build()
                .let(::Elide)
    }

    @Bean
    fun elideUserExtractionFunction() = DefaultOpaqueUserFunction { context: SecurityContext? ->
        context?.userPrincipal
    }
}
```
I've managed to add a Spring MVC `@RestController` for Elide-driven REST API endpoint, and it works as expected. But GraphQL endpoint [needs additional classes](https://github.com/yahoo/elide/blob/2f417d1b4c7293de60237b3a085e37e41800978c/elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java#L72) to build a GraphQL API executor.
So either I have to implement such an endpoint via Spring MVC `@Controller`, or add Jersey support and register that endpoint class shipped with elide-graphql. I've tried a second option and failed with transaction management support:
```kotlin
@Configuration
@Transactional
class ElideJerseyResourceConfig : ResourceConfig() {
    init {
        register(GraphQLEndpoint::class.java)
    }
}
```
It gives me some strange `Allocate exception for servlet` exception with `@Transactional` annotation and `Could not obtain transaction-synchronized Session for current thread` without it(which is expected).
