### ISSUE TITLE
Spreadsheet upload & upsert

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#629]
Does Elide support POSTing a spread sheet of data? How about single row update in that sheet?

**Comment by clayreimann** [comment]
I don't think that really fits with the mission of Elide. Sounds like a great candidate for a custom HTTP endpoint.

**Comment by DennisMcWherter** [comment]
Another option here is to model your CSV requests as compatible with the current interchange formats (i.e. JSON-API or GraphQL). If you only care about row level modifications, you could propose something like this:

```java
public class Document {
  ...
  private List<String> rows = new ArrayList<>();
  ...
}
```

This would enable row-based access to a document. If you wanted something more granular (i.e. cell-based) there are several approaches you could take. You could use something like a `List<List<String>>` where you index into both lists by a `(row,col)` tuple or perform some sort of transformations for easier storage:

```java
public class Document {
  ...
  // Don't expose raw rows via Elide, only store in the DB
  @Exclude private List<String> rows = new ArrayList<>();
  ...

  @Transient
  @ComputedAttribute
  public List<List<String>> getCells() {
    // Convert rows to a list of list of strings which represent cells
    return this.getRows().stream()...
  }

  public void setCells(List<List<String>> cells) {
    // Convert cells into a list of strings representing rows:
    List<String> rows = ...;
    this.setRows(rows);
  }
}
```

Would that work?

**Comment by QubitPi** [comment]
Thank you, guys, for the helpful response! I think a custom endpoint that turns each row of CSV into JPA shall be the best for us.
