### ISSUE TITLE
How does Elide handles Bean type differentiation?

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#631]
How does Elide handles POST of different types of Bean? What info does client has to provide to let Elide direct POSTed entity to its corresponding database table?

Could you point me to the codebase for it's logic?

Thanks!

**Comment by clayreimann** [comment]
I don't understand. Are you asking how Elide knows that `/user/1` corresponds to the `User` bean and `/post/1` corresponds to the `Post` bean? If so, then you'll want to look at the classes [here](https://github.com/yahoo/elide/tree/master/elide-core/src/main/java/com/yahoo/elide/parsers/state)

**Comment by QubitPi** [comment]
@clayreimann Cool. Thanks!
