### ISSUE TITLE
how can I control 'relationships' show in data

### ISSUE THREAD

**Issue by loumzy** [yahoo/elide#632]
#### how can I control 'relationships' don't show by default, sometime I just need the basic info. If I need the 'relationships', I can include it by add include to the query url.
```
{
  "data": [
    {
      "type": "order",
      "id": "7",
      "attributes": {
        "title": "电视"
      },
      "relationships": {
        "corp": {
          "data": {
            "type": "corp",
            "id": "2"
          }
        },
        "user": {
          "data": {
            "type": "user",
            "id": "1"
          }
        }
      }
    }
  ]
}
```

**Comment by clayreimann** [comment]
It sounds like you're looking for the [`fields`](http://elide.io/pages/guide/10-jsonapi.html#sparse-fields) query parameter. At the moment we don't have a way to programmatically define a default set of fields to be sent.

**Comment by belovaf** [comment]
Load all identifiers for all relations is very expensive for fat Entities (1 select for each relation).
May be we shouldn't load them by default? We can return only relation link if the relation is not part of `include`.
What do you think?

**Comment by aklish** [comment]
N+1 should be resolved in Elide 5.  Closing as this suggestion is not compatible with JSON-API.  GraphQL has the inverse model - you only get what you request - which is one small advantage over JSON-API.
