### ISSUE TITLE
InvalidValueException on POST

### ISSUE THREAD

**Issue by sdhawley** [yahoo/elide#635]
I have been setting up a project using elide-standalone@4.0.2, the database gets created and I attempt to seed the database with a test record and get an InvalidValueException returned in the response:
```
{"errors":["InvalidValueException: Invalid value: Resource(type=contact, id=null, attributes=null, relationships=null, links=null, meta=null)"]}
```
The data model class
```java
@Include(rootLevel = true)
@Entity
public class Contact {    
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id;
    String firstName = "";
}
```
and I try to seed using
```sh
curl -X POST http://localhost:8080/api/v1/contact \
  -H"Content-Type: application/vnd.api+json" -H"Accept: application/vnd.api+json" \
  -d '{"data": {"type": "contact", "attributes": { "firstName": "Tim" } } }'

```

I poked around in the debugger and it seems that the Id annotation isn't being found on the Contact object in ``com.yahoo.elide.core.PersistentResource.assignId()``. I've tried declaring the id with and without ``@GeneratedValue`` and got the same result. Is this a bug or did I do something wrong?

In case its relevant:
Mysql 5.7 backend
Hibernate5 data store (the default)

**Comment by DennisMcWherter** [comment]
Hi @sdhawley! I am not sure this is called out in the docs, but if you're going to annotate fields (in general, we recommend using getters and setters) they must be made `public` or Elide will ignore them. This is behavior we could consider changing in the future.

Let me know if that doesn't help solve the issue!

**Comment by sdhawley** [comment]
Thank you @DennisMcWherter! The example in the docs does declare the fields ``public`` but I don't see it saying that it was required so I thought it was "designers choice" for how we setup access control. It was very frustrating because I could see that the field had the annotation using javap!

Its working now that I have made the field ``public``, thanks for your help.

**Comment by sdhawley** [comment]
Just noticed that regardless of the field being public, getters and setters seem to be required for attributes to be persisted as well. If this is the intended behavior it should probably be added to the docs as well.

I'd prefer if it wasn't required though, a good deal of the appeal of elide (for me anyway) was to be able to create a schema with relatively simple java classes. Create the fields, add a few annotations and my json api is up and running. Having to write getters and setters for every field adds relatively significant time to write each class, not bad for a couple classes but could add up over time.

**Comment by sdhawley** [comment]
My mistake, its related to where I put the ``@Id`` annotation (field or method strategy, can't be mixed)

**Comment by DennisMcWherter** [comment]
Glad you found the issue-- is there any other issues you noticed on our end?

**Comment by sdhawley** [comment]
No, just the docs could be more clear about what is required. In the interest of ease of use I would vote for dropping the ``public`` requirement, unless there is some use case for applying a persistence annotation that should be ignored.

**Comment by DennisMcWherter** [comment]
I think that's a fair request. To avoid breaking current behavior, we can make an `ElideSetting` setting for this which defaults to `false` and can then be overridden.

@clayreimann @aklish any objections to something like that?

**Comment by clayreimann** [comment]
I don't have an explicit objection to it, but if a field isn't `public` wouldn't it have to be in a `com.yahoo.elide` package somewhere so that our code has permission to set the value? Or would we do more reflections magic to manipulate the visibility at runtime?

**Comment by DennisMcWherter** [comment]
It would certainly be reflection magic to manipulate its visibility at runtime :)

**Comment by aklish** [comment]
Closing as private field level access has already been implemented.
