### ISSUE TITLE
Is there any plan to support hibernate 5.2.x ?

### ISSUE THREAD

**Issue by olOwOlo** [yahoo/elide#638]
I tried to use this framework with springboot 2.0 (hibernate 5.2.14), but I found hibernate have some breaking changes... 🤒 

- `org.hibernate.Query` move to `org.hibernate.query.Query`
- The `session.getFlushMode()` will return JPA's `FlushModeType` instead of `FlushMode`
- The `sessionFactory.getAllClassMetadata()` is deprecated and will throw `UnsupportedOperationException`

**Comment by clayreimann** [comment]
Which datastore are you using? We have the `elide-datastore-hibernate3` and `elide-datastore-hibernate5` flavors. Are you seeing these problems with the hibernate5 variety?

**Comment by clayreimann** [comment]
Oh, I think @DennisMcWherter ran into this when we tried to upgrade everything to the very latest version. We do eventually want to make this work with the most recent hibernate5. Unfortunately our projects are still tied to hibernate 3 for various reasons so we don't yet have an application in production with hibernate5. 

If you wanted to open a PR to fix hibernate's awful decisions we'd be happy to work with you.

**Comment by aklish** [comment]
Upgraded hibernate to 5.2.15 (latest final version from March 8th).
