### ISSUE TITLE
Some HibernateExceptions are converted to PersistenceException

### ISSUE THREAD

**Issue by olOwOlo** [yahoo/elide#640]
When I inserted a duplicate value into a unique column, I got a `ConstraintViolationException` which be converted to `PersistenceException` by [`ExceptionConverterImpl`](https://github.com/hibernate/hibernate-orm/blob/8c661baea2d930855ed6431671b3e19108e12832/hibernate-core/src/main/java/org/hibernate/internal/ExceptionConverterImpl.java#L85).

```
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149) ~[hibernate-core-5.2.14.Final.jar:5.2.14.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157) ~[hibernate-core-5.2.14.Final.jar:5.2.14.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:164) ~[hibernate-core-5.2.14.Final.jar:5.2.14.Final]
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1442) ~[hibernate-core-5.2.14.Final.jar:5.2.14.Final]
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1422) ~[hibernate-core-5.2.14.Final.jar:5.2.14.Final]
	at com.yahoo.elide.datastores.hibernate5.HibernateTransaction.flush(HibernateTransaction.java:87) ~[elide-datastore-hibernate5-4.2.0.jar:na]
```

Since the `flush` method doesn't catch `PersistenceException`, finally, I got http status 500.

https://github.com/yahoo/elide/blob/1aab9234538d9cef3f629eda4df3c5a9cdb2b76c/elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java#L80-L93

It seems that the `commit` method also has this problem. Is this a bug? Should I catch all `PersistenceException` ??

**Comment by QubitPi** [comment]
Thanks for the catch!

What is your expected behavior? Is your intent trying to have Elide return a different response saying you have `UNIQUE` constraint violation and not crashing your application?

**Comment by aklish** [comment]
I'm not sure exactly what the concern is.  Is the concern the HTTP status
code is not correct in this instance?
Would you rather see a 400 error?

Thanks.

Aaron

**Comment by olOwOlo** [comment]
Hi, thank you for your reply. @QubitPi @aklish 

The correct HTTP status code is better, and now it seems that only HTTP 423 is available when a `HibernateException` is thrown. In this case, personally I think the HTTP [409](https://tools.ietf.org/html/rfc7231#section-6.5.8) is better.

But what I really want to say is that we may miss the `PersistenceException`.  I found the following paragraph in the [Hibernate Migration Guide 5.2](https://github.com/hibernate/hibernate-orm/wiki/Migration-Guide---5.2).

> `org.hibernate.HibernateException` now extends `javax.persistence.PersistenceExceptions`.  Hibernate methods that "override" methods from their JPA counterparts now will also throw various JDK defined RuntimeExceptions (such as `IllegalArgumentException`, `IllegalStateException`, etc) as required by the JPA contract.

It seems that this will only happen in Hibernate 5.2, the `HibernateException` we wanted to capture was converted to `PersistenceException`.

**Comment by QubitPi** [comment]
You can either open a PR against Elide, which is quick, or, if they reject changes, have a downstream catch for `PersistenceException` in your spring-boot application.

**Comment by olOwOlo** [comment]
@QubitPi  I temporarily catch all `PersistenceException`, but I'm not sure if this is the right.  I'll be waiting for the update. 😄

**Comment by aklish** [comment]
@olOwOlo - Can you see if my PR fixes your issue?  Thanks.

**Comment by olOwOlo** [comment]
@aklish It works for me :D
