### ISSUE TITLE
Error : Unknown collection

### ISSUE THREAD

**Issue by 3mendous** [yahoo/elide#647]
Hi there,
I have difficulties with elide. I think it's somthing basic but I can't figure out what I'm doing wrong. I want to create rest service using elide, spring boot and postresql db. This is example article [](https://dzone.com/articles/create-a-json-api-rest-service-with-spring-boot-an) I know it's old, but it doesn't matter for now. My rest controller, package-info and application are exactly the same. This is my entity
```
import lombok.Getter;
import lombok.Setter;
import javax.persistence.*;
import java.io.Serializable;
@Entity
@Table(name = "test")
@NamedQuery(name="TestEntity.findAll", query="SELECT t FROM TestEntity t")
public class TestEntity implements Serializable {
    public TestEntity() {
    }
    //Entity name
    @Id
    @Getter
    @Setter
    @Column(name = "name")
    private String name;
    //Entity's owner
    @Getter
    @Setter
    private String owner;
    //Info about entity
    @Getter
    @Setter
    @Column(name = "info")
    private String info;
}
```
my application. properties
```
server.port = 8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
```
As i understood, I need to send my requests to localhost:8080/test, but there is always 'Unknown collection' error. I made this service with simple JPA easily, but with elide I faces some problems.
Could someone help me?

**Comment by clayreimann** [comment]
For anyone else who stumbles upon this issue in the future, the problem likely came from using a private id field (`@Id private String`)

**Comment by 3mendous** [comment]
I solved by naming my entity like table name. When it became public class Test all worked fine. The advice above didn't help me
