### ISSUE TITLE
No Way to Add Service Healthcheck

### ISSUE THREAD

**Issue by jstemen** [yahoo/elide#648]
I can't seem to find anyway to add a healthcheck endpoint to an Elide service.  Am I missing something, thanks.

**Comment by clayreimann** [comment]
Can you be more specific? Are you using `elide-standalone`? If not just follow your servlet’s standard mechanism. @DennisMcWherter is there a way to plug other end points into `elide-standalone`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DennisMcWherter** [comment]
Adding to what @clayreimann said, if you're using `elide-standalone`, you may want to see [ElideStandaloneSettings#getApplicationConfigurator](https://github.com/yahoo/elide/blob/master/elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java#L153-L156) if it is acceptable to have your servlet mounted under the same root path. From there you can use `ResourceConfig#packages` to add your new servlet.

For instance, if you had something like this for a trivial health check:

```java
package com.mypackage.my.servlets;

@Path("/my-health-check")
public class MyHealthCheck {
  @GET
  public String handleGet() {
    return "Working!";
  }
}
```

you could then add an override to your `ElideStandaloneSettings`:

```java
public class MySettings extends ElideStandaloneSettings {
  ...
  @Override
  public Consumer<ResourceConfig> getApplicationConfigurator() {
    return (config) -> config.packages("com.mypackage.my.servlets");
  }
  ...
```

If your API is mounted under `/api/v1`, then your health check would reside at `/api/v1/my-health-check`.

However, if mounting the health-check servlet under the API namespace is unacceptable (again, this is for `elide-standalone`. If not using `elide-standalone`, then you just configure your `web.xml` or webserver directly), then there is no way to do this today.

However, there are a few approaches we could take to quickly and easily resolve this issue. Namely, we could enable a configuration option which allows you to optionally load a `web.xml` and allow full customization of the embedded jetty servlet through that. Additionally, we could provide a hook in the `ElideStandaloneSettings` which allows you to manipulate jetty's `ServletContext` directly.

Haven't though hard enough yet to determine which approach is best exactly.

**Comment by jstemen** [comment]
Thanks for the fast replies!  Yes, I'm using ElideStandalone.  

The hook in ElideStandaloneSettings sounds good.  For the time-being, I just copy-tweaked the ElideStandalone class to look like like the following.  Seems to be working ok for me.  I'm not thrilled my solution involves copying and slightly changing the code, but it seem to work okay for now.

`    public void start() throws Exception {
        ServletContextHandler context = new ServletContextHandler();
        context.setContextPath("/");

        log.info("Starting jetty server on port: {}", elideStandaloneSettings.getPort());
        Server jettyServer = new Server(elideStandaloneSettings.getPort());
        jettyServer.setHandler(context);
        context.setContextPath("/");

        context.setAttribute(ELIDE_STANDALONE_SETTINGS_ATTR, elideStandaloneSettings);


        ServletHolder healthServ = context.addServlet(
                org.glassfish.jersey.servlet.ServletContainer.class, "/*");
        healthServ.setInitOrder(0);

        healthServ.setInitParameter(
                "jersey.config.server.provider.classnames",
                HealthCheckServlet.class.getCanonicalName());

        if (elideStandaloneSettings.enableJSONAPI()) {
            ServletHolder jerseyServlet = context.addServlet(ServletContainer.class,
                    elideStandaloneSettings.getJsonApiPathSpec());
            jerseyServlet.setInitOrder(0);
            jerseyServlet.setInitParameter("jersey.config.server.provider.packages", "com.yahoo.elide.resources");
            jerseyServlet.setInitParameter("javax.ws.rs.Application", ElideResourceConfig.class.getCanonicalName());
        }

        if (elideStandaloneSettings.enableGraphQL()) {
            ServletHolder jerseyServlet = context.addServlet(ServletContainer.class,
                    elideStandaloneSettings.getGraphQLApiPathSepc());
            jerseyServlet.setInitOrder(0);
            jerseyServlet.setInitParameter("jersey.config.server.provider.packages", "com.yahoo.elide.graphql");
            jerseyServlet.setInitParameter("javax.ws.rs.Application", ElideResourceConfig.class.getCanonicalName());
        }

        try {
            jettyServer.start();
            log.info("Jetty started!");
            jettyServer.join();
        } catch (Exception e) {
            log.error("Unexpected exception caught: {}", e.getMessage(), e);
            throw e;
        } finally {
            jettyServer.destroy();
        }
    }
`

**Comment by DennisMcWherter** [comment]
That looks like a reasonable short-term fix. I propose we add an additional setting to the `ElideStandaloneSettings` which allows you to manipulate the `ServletContextHandler` directly. If we provided that, you should be able to do away with the extra code.

@clayreimann @aklish does that sound reasonable? Should be an easy thing to implement.

**Comment by clayreimann** [comment]
👍

**Comment by DennisMcWherter** [comment]
Sorry for the delay here, but I have a proposed fix. Can you verify this will be sufficient?

https://github.com/yahoo/elide/pull/653

**Comment by jstemen** [comment]
Yep, looks like that will work quite nicely.  Thanks!
