### ISSUE TITLE
Errors should be objects

### ISSUE THREAD

**Issue by olOwOlo** [yahoo/elide#650]
In the JSON API [spec](http://jsonapi.org/format/#error-objects), the error is described as “Error Objects” and has some members. The GraphQL [spec](http://facebook.github.io/graphql/October2016/#sec-Errors) also require this.

**Actual Result**
```json
{
    "errors": [
        "error description"
    ]
}
```

**Expected Result**
```json
{
    "errors": [
        {
            "detail": "error description"
        }
    ]
}
```

**Comment by aklish** [comment]
I'm going to leave this open until we update the documentation for the new Elide setting to enable this behavior.  

We should remove the setting in Elide 5.0 so the default behavior is the behavior described in this issue.
