### ISSUE TITLE
How to register function hook in Spring?

### ISSUE THREAD

**Issue by olOwOlo** [yahoo/elide#654]
According to the [documentation](http://elide.io/pages/guide/02-data-model.html#registered-function-hooks), I tried `bindTrigger` method ([link](https://github.com/illyasviel/elide-spring-boot/blob/d8efb1860725fabdd780178a80bfc1e60466ddd1/elide-spring-boot-autoconfigure/src/main/java/org/illyasviel/elide/spring/boot/autoconfigure/ElideAutoConfiguration.java#L137-L139)):
```java
entityDictionary.bindTrigger(Account.class, OnCreatePostCommit.class, new AccountOnCreatePostCommit());
entityDictionary.bindTrigger(Account.class, OnCreatePreSecurity.class,
    (a, b, c) -> logger.debug("OnCreatePreSecurity lambda execute"));  // Yes, I know the log level is debug.
```

Then, I created an Account
```bash
curl -X POST \
  http://localhost:8080/api/account \
  -H 'Accept: application/vnd.api+json' \
  -H 'Content-Type: application/vnd.api+json' \
  -d '{
  "data": {
    "type": "account",
    "attributes": {
      "password": "test",
      "username": "test"
    }
  }
}'
```
However, I didn't see any logs I expected (callbacks were not invoked?).
Did I do something wrong? Is this feature unavailable in Spring?

---

You can reproduce in this [project](https://github.com/illyasviel/elide-spring-boot/tree/function_hook/elide-spring-boot-autoconfigure/src/main/java/org/illyasviel/elide/spring/boot) (branch: function_hook).

**Comment by aklish** [comment]
Briefly looked.  My guess is you are binding the triggers before you are binding the entities themselves.  In that case, Elide will silently accept your bindings but tied to the EMPTY_BINDING.

If this is in fact the case, we should probably do something intelligent (in Elide) here instead.  Maybe we should bind the entity when binding the trigger (if no binding already exists).

Here is the Elide code that currently binds the trigger:
```
    public void bindTrigger(Class<?> entityClass,
                            Class<? extends Annotation> annotationClass,
                            String fieldOrMethodName,
                            LifeCycleHook callback) {
        getEntityBinding(entityClass).bindTrigger(annotationClass, fieldOrMethodName, callback);
    }
```

Here is getEntityBinding (note the default case)
```
    protected EntityBinding getEntityBinding(Class<?> entityClass) {
        if (isMappedInterface(entityClass)) {
            return EntityBinding.EMPTY_BINDING;
        }
        return entityBindings.getOrDefault(lookupEntityClass(entityClass), EntityBinding.EMPTY_BINDING);
    }
```

**Comment by olOwOlo** [comment]
```diff
- entityDictionary.bindTrigger(...);

Elide elide = new Elide(...);

+ entityDictionary.bindTrigger(...);
```

I moved `bindTrigger` and invoked it after entities have been bound.

It works now! Thank you very much! @aklish
