### ISSUE TITLE
Elide Dependency Injection

### ISSUE THREAD

**Issue by DerKlassiker** [yahoo/elide#664]
I am using Elide with Spring and have an issue with dependency injection. 

Let's say here I have an entity named Employee. 
``` 
public class Employee {

   @Inject
   @Transient
   private EmployeeMetadataRepository repo;

   // ...and getters and setters for some other member variables

   @OnReadPostCommit()
   public void onRead() {
      Metadata metadata = new Metadata();
      repo.save(metadata);
   }

   public Employee(EmployeeMetadataRepository repo) {
      this.repo = repo;
   }
}

public interface EmployeeMetadataRepository extends CrudRepository<Metadata, String> {}
```

_EmployeeMetadataRepository_ was not injected. I guess that is because of configuration. Is my assumption correct? If so, what does it have to look like? Currently it looks like this. 
```
@Bean
public Employee employee(EmployeeMetadataRepository employeeMetadataRepository) {
   return new Employee(employeeMetadataRepository);
}
```

How can I wire EmployeeMetadataRepository with Employee in configuration?

**Comment by DennisMcWherter** [comment]
What servlet technology are you using and which datastore? How this is typically done is binding the injector to the initializer when the store is creating. You can [see the docs](http://elide.io/pages/guide/02-data-model.html#dependency-injection) for an example.

In summary, you want to override the datastore's `populateEntityDictionary` and wrap it such that the dictionary initializer will call inject on your new entities. Likewise, you will need to bind to this injector of course. If using a servlet technology like Jersey, you can do this in the `ResourceConfig` setup.

Let me know if anything is unclear!

**Comment by DerKlassiker** [comment]
Thank you for the answer. To be honest, the documentation is a bit unclear to me. Under the section Dependency Injection (http://elide.io/pages/guide/02-data-model.html#dependency-injection), what is this class Injector? There is no such class. Is this documentation not up to date by any chance? Is there any example or example code where dependency injection in Elide is done?

**Comment by olOwOlo** [comment]
Hi @DerKlassiker , I made a spring boot starter for elide, you can use it directly.

There is the [repo](https://github.com/illyasviel/elide-spring-boot).

There is the [code](https://github.com/illyasviel/elide-spring-boot/blob/b0b5486cf8ae94a778a4de907cd5e4192d8b895f/elide-spring-boot-autoconfigure/src/main/java/org/illyasviel/elide/spring/boot/datastore/SpringHibernateDataStore.java#L123) how to integrate spring dependency injection.

**Comment by DerKlassiker** [comment]
@DennisMcWherter , @olOwOlo : Thank you very much!
