### ISSUE TITLE
How to filter by attribute? 

### ISSUE THREAD

**Issue by DerKlassiker** [yahoo/elide#668]
I have a question regarding filtering. Let's say I have this class as below. 

```
public class Employee {
   private String id;
   private int age;
   private String address;
}
```
How can I filter by age for example only filter employees whose age is 30? Based on the documentation, it seems that 

"/employee?filter[age]=30"

But it won't work.

**Comment by DerKlassiker** [comment]
@DennisMcWherter : Do you know by any chance?

**Comment by aklish** [comment]
Try "/employee?filter[employee.age]=30"

Aaron

**Comment by DerKlassiker** [comment]
@aklish : Won't work

**Comment by aklish** [comment]
Can you elaborate?  It should.  There are lots of similar examples here:

https://github.com/yahoo/elide/blob/master/elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/FilterIT.groovy#L1337

Is age a computed or real attribute?

Aaron

**Comment by aklish** [comment]
Another possibility - your employee class has all fields listed as
private.  That could also be the problem.

Elide doesn't expose private fields.

Aaron

**Comment by aklish** [comment]
I also highly recommend all models to use public property accessors
(getAge, setAge) instead of fields.

All of our tests are on models with properties.  In theory, fields could
work - but it is not supported 100% (see
https://github.com/yahoo/elide/issues/644)

Aaron

**Comment by DerKlassiker** [comment]
@aklish : it is a real attribute and have public property accessors. Not working. Still trying to figure out why it is not working.

**Comment by DerKlassiker** [comment]
@aklish : I got "InvalidPredicateException: Invalid query parameter: filter[age]" error

**Comment by aklish** [comment]
Try changing *age* to* employee.age*

**Comment by DerKlassiker** [comment]
@aklish : tried both. none of them working :(

**Comment by aklish** [comment]
FYI, here is the code where Elide scans the model for fields to expose:

https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java#L119

It only includes public fields.

Aaron

**Comment by aklish** [comment]
Did you fix the model to add
public getAge and public setAge?

Aaron

**Comment by DerKlassiker** [comment]
Yes. any other possibilities?

**Comment by aklish** [comment]
Can you send me link to your repo?  Did you add @Include annotation on the
model?  Is it a JPA entity (@Entity)?

You need both annotations on the class.  Otherwise Elide doesn't expose it.

**Comment by DerKlassiker** [comment]
@aklish : it is working! Thank you so much!

**Comment by aklish** [comment]
No problem.  Make sure you adjust your other properties to public
getter/setters too (including the ID).  Take care.

Aaron

**Comment by aklish** [comment]
Looks like elide standalone (if you are using it) only enables RSQL filters
by default:

https://github.com/yahoo/elide/blob/master/elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java#L60-L61

It is still possible to enable the other dialect in code if you prefer that
format.

Aaron

**Comment by DerKlassiker** [comment]
@aklish : Thank you very much for your help once again. Could you tell me how to sort by age too? The documentation doesn't really seem clear to me.

**Comment by aklish** [comment]
`sort=age` for ascending
OR
`sort=-age` for descending

**Comment by aklish** [comment]
Can I close the issue?

**Comment by DerKlassiker** [comment]
@aklish : Thank you!
