### ISSUE TITLE
How can I make a field transient and still filter by the field? 

### ISSUE THREAD

**Issue by DerKlassiker** [yahoo/elide#671]
```
public class Employee {
   @Setter @NotBlank @Transient private String employeeId;
   // other fields
}
```
I don't want to expose this employeeId but still want to be able to filter by employeeId. 

1) /api/v1/employee
This works and it won't expose employeeIds. 

2) /api/v1/employee?filter[employee]=employeeId==12345
This causes an error saying "InvalidPredicateException: Invalid query parameter: filter[employee]\nNo such association employeeId for type employee". 
I believe this is because of the @Transient annotation. 

How can I make this field transient (or don't expose it) and still filter by it?

**Comment by aklish** [comment]
Fields which are not exposed cannot be filtered on.

Aaron

**Comment by DerKlassiker** [comment]
Thank you @aklish
