### ISSUE TITLE
mutiple datasource

### ISSUE THREAD

**Issue by ThreefLi** [yahoo/elide#675]
when config two datasource in springboot project,only the entity of the primary datasource is accessible

**Comment by aklish** [comment]
If you want more than a single data store active, you need to configure the Multiplex store.

http://elide.io/pages/guide/06-datatstores.html

Create a Multiplex store:
https://github.com/yahoo/elide/blob/master/elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexManager.java#L41

And then use that when you construct your Elide instance with ElideSettingsBuilder:

https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/ElideSettingsBuilder.java#L52

You'll need to bind your models to their respective stores.  Let me know if that resolves your issue.

**Comment by ThreefLi** [comment]
Thank you very much,it works well
