### ISSUE TITLE
@NotNull is not working

### ISSUE THREAD

**Issue by tbo-axelor** [yahoo/elide#676]
```
@Entity
@Table(name = "contact")
@Include(rootLevel = true)
public class Contact {

	private Long id;

	private String firstName;

	private String lastName;

	private String email;

	private String phone;

	private List<Address> addresses;

	public Contact() {

	}

	public Contact(long id, String firstName, String lastName, String email, String phone) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CONTACT_SEQ")
	@SequenceGenerator(name = "CONTACT_SEQ", sequenceName = "CONTACT_SEQ", allocationSize = 1)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@NotNull
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(mappedBy = "contact")
	public List<Address> getAddresses() {
		return addresses;
	}

	public void setAddresses(List<Address> addresses) {
		this.addresses = addresses;
	}

}

**Comment by clayreimann** [comment]
I think you need to put `@NotNull` on the setter. I believe you that it won’t do anything on the getter. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tbo-axelor** [comment]
public String getFirstName() {
		return firstName;
	}
	
	@NotNull
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

still is not working

**Comment by wcekan** [comment]
Actually, @NotNull goes on the getter and is a validation annotation: javax.validation.constraints.NotNull.

 Hibernate could do the constraint validation on save if configured, but Elide must not perform validations itself.  This could be useful.    On Wednesday, July 18, 2018, 8:23:26 AM CDT, tbo-axelor <notifications@github.com> wrote:  
 
 
public String getFirstName() {
return firstName;
}
@NotNull
public void setFirstName(String firstName) {
	this.firstName = firstName;
}

still is not working

**Comment by clayreimann** [comment]
@tbo-axelor did you solve the issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tbo-axelor** [comment]
yes, isolve that issue.
add one hibernate validator dependecies then it is working fine
compile 'org.hibernate:hibernate-validator:5.3.4.Final'
