### ISSUE TITLE
Relationship Exposure and Acquiring Entity Manager

### ISSUE THREAD

**Issue by jgiangv** [yahoo/elide#685]
Hi,
First, thank you very much for the offering framework.
I have a web application which entities such as Alpha, Beta, Gamma, relationship as follow:
Entities:
------relationship  ----
/---------|----------\        
Alpha  Beta      Gamma

APIs:      
aphas    betas     gammas

Alpha, Beta, Gamma are exposed to api.  Relationship has from_id which is id from (Alpha, Beta, Gamma) and to_id can be from any (Alpha, Beta, Gamma)

When I tried to delete one log relationship, elide deletes other relationship as well
localhost:9000/api/alphas/alpha123/relationships/gammas{
    data :{ "type" : grammas, id : gamma123}
}

How do I archive my goal that I delete only one desired relationship that matches alpha123 and gamma123, and nothing else?

How do I also expose relation entity ( I have an error) when access localhost:9000/api/relationships?
How do I acquire HibernateSession?

Thank you very much.

John G.

**Comment by aklish** [comment]
Can you post your model code and the HTTP requests you are making that work/don't work?

I'm not 100% following the problem the text.  Thanks.

**Comment by jgiangv** [comment]
Thank you very much for replying to me Aaron,

I have 3 entities:  Emails, Recipients, Relationships.  One email can have many recipients.  One recipient can have many emails.

So structure as follows:
@Entity (rootLeveL=true, type=”emails”)
Email
----------
Id
From
To

@Entity (rootLeveL=true, type=” recipients”)
Recipient
----------
Name
Id
Email

@Entity (rootLeveL=true, type=”relationships”)
Relationship
------------
Id
Name
fromId( Email.id| Recipient.id)
toId( Email.id| Recipient.id)

These are three entities, I expose 3 entities as rest service, but relationship threw error when we try GET
The goal is to delete a Relationship record where the record has its ids such as relationship.fromid =  Email.id and relationship.toID  =  Recipien
For example:
http://localhost:8080/api/emails/email_id/relationships/recipients
{
     “data”: {
“type” : “recipients”
“id”     :  “recipient_id”
}
}

This does delete the relationship but it does not delete only the relationship matches only email.id and recipient.id but other relationships which matching either provided email.id or provided recipient.id

So the question how to make sure it only delete one relationship record which matching say email.id=1 and recipient.id=1 only not either or?
Also why Relationship mapping to relationships return errors?  Is that Elide prohibits expose of relationship table?

Can we work with EntityManager only, instead of DataStore object and how?

Thank you very much.

John Giang

**Comment by jgiangv** [comment]
Hi Aaron,
May be let me try a simple as the fellowing:
I have 3 tables (entities): Alpha (has id, name), Relationship(has id, From_ID, To_ID) , Beta(has id, name).
Relationship table has its own id, fromId can be from Alpha/Beta and ToId can be from Beta/Alpha
For example.
Alpha (id=a1, name=alpha1),  Beta (id=b1, name=beta1), Relationship  (id=r1, from_Id=a1, To_ID=b1)
Alpha (id=a1, name=alpha1),  Beta (id=b2, name=beta2), Relationship  (id=r2, from_Id=a1, To_ID=b2)

Alpha, Beta, Relationship are entity and expose to the web using Elide framework.

1) The issue is how do I delete r1 only without delete r2 or other rn in Relationship table? 
Right now we delete r1, but also other rn records via the url below

http://localhost:8080/api/alphas/a1/relationships/beta
{
     “data”: {
          “type” : “betas”
          “id”     :  “b1”
   }
}

2) I exposed Relationship entity as web endpoint but get error return when invoke http://localhost:8080/relationships/.  How do I expose this relationship entity to be able query its data like alpha and beta (I expose exact syntax just like alpha, beta entities, they works but not the Relationship entity)?

3) How do I acquire EntityManager in Elide as if I would in JPA?  How do I hook my method that delete other tables's record if the criteria is also meets Relationship tables.  In other work, how do I intervene the delete of Relationship record?

I know I have several questions on this.  Our team is so interested to make our project works, using Elide framework.  Please give us your advice.  Thank you very much.

John G.

**Comment by aklish** [comment]
Hi John,

I'll try to take these one by one, but in almost all cases I'll need more information to help you.

1.  It should be possible to delete an individual relationship.  Can you send the HTTP request you are using to delete and the response you receive from the server?  Also, it would be great if you could share the actual source code for the models.

2. This is hard to say without seeing both the source code, the HTTP request, and the response you are getting.  The word 'relationships' in the path of your URL is pluralized.  It could be a simple problem that the path name does not match the type name ('relationship').

Also, the keyword 'relationships' is overloaded in jSON-API.  It has special meaning.  I would advise naming your type something else.

3.  In general, Elide & Hibernate (through annotations) should be sufficient for persistence and cleanup of your models that you expose through Elide.  You can cascade deletes, etc if you need to.  If you want to do something truly custom (outside the persistence of one of your entities), you can use a lifecycle hook to do that work.  You can use an elide initializer to pass the EntityManager to the hook (if it resides in a model), or register the hook outside the bean and construct it with the EntityManager.

Hope that helps.

Aaron

**Comment by nerdstep** [comment]
Hey @aklish, I'll try to help clarify the issue.

Here's the example source code:
https://gitlab.com/nerdstep/elide-test

It's somewhat of an unusual database design that we're stuck with, where there are many-to-many relationships all using one join table.

So for example entity `Alpha` can be related to many other entities of type `Alpha` as well as many other entities of type `Bravo`, etc. and it's the same for entity `Bravo`.

Okay, now let's say we have a record `Alpha.A1`, which looks like this:

```js
{
    "data": [
        {
            "type": "alphas",
            "id": "a1",
            "attributes": {
                "name": "alpha1"
            },
            "relationships": {
                "alphas": {
                    "data": [
                        {
                            "type": "alphas",
                            "id": "a2"
                        },
                        {
                            "type": "alphas",
                            "id": "a3"
                        }
                    ]
                },
                "bravos": {
                    "data": [
                        {
                            "type": "bravos",
                            "id": "b1"
                        },
                        {
                            "type": "bravos",
                            "id": "b2"
                        }
                    ]
                }
            }
        }
    ]
}
```

Now we're going to perform a delete request to remove `A1`'s relationships to the other `Alpha` entities.

```js
DELETE http://localhost:5000/api/alphas/a1/relationships/alphas

{
  "data": [
    {
      "type": "alphas",
      "id": "a2"
    },
    {
      "type": "alphas",
      "id": "a3"
    }
  ]
}
```

Here's what Hibernate does:

```sql
    delete 
    from
        relationship 
    where
        from_id=?
```

<details>
<pre>
2018-08-08 08:47:27.894 DEBUG 113896 --- [nio-5000-exec-5] org.hibernate.SQL                        : 
Hibernate: 
    select
        alpha0_.id as id1_0_,
        alpha0_.name as name2_0_ 
    from
        alpha alpha0_ 
    where
        alpha0_.id in (
            ?
        )
2018-08-08 08:47:27.894 TRACE 113896 --- [nio-5000-exec-5] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [VARCHAR] - [a1]
2018-08-08 08:47:27.895 DEBUG 113896 --- [nio-5000-exec-5] org.hibernate.SQL                        : 
Hibernate: 
    select
        alphas0_.from_id as from_id1_2_0_,
        alphas0_.to_id as to_id2_2_0_,
        alpha1_.id as id1_0_1_,
        alpha1_.name as name2_0_1_ 
    from
        relationship alphas0_ 
    inner join
        alpha alpha1_ 
            on alphas0_.to_id=alpha1_.id 
    where
        alphas0_.from_id=?
2018-08-08 08:47:27.896 TRACE 113896 --- [nio-5000-exec-5] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [VARCHAR] - [a1]
2018-08-08 08:47:27.898 DEBUG 113896 --- [nio-5000-exec-5] org.hibernate.SQL                        : 
Hibernate: 
    select
        alpha0_.id as id1_0_,
        alpha0_.name as name2_0_ 
    from
        alpha alpha0_ 
    where
        alpha0_.id in (
            ?
        )
2018-08-08 08:47:27.899 TRACE 113896 --- [nio-5000-exec-5] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [VARCHAR] - [a2]
2018-08-08 08:47:27.901 DEBUG 113896 --- [nio-5000-exec-5] org.hibernate.SQL                        : 
Hibernate: 
    select
        alpha0_.id as id1_0_,
        alpha0_.name as name2_0_ 
    from
        alpha alpha0_ 
    where
        alpha0_.id in (
            ?
        )
2018-08-08 08:47:27.901 TRACE 113896 --- [nio-5000-exec-5] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [VARCHAR] - [a3]
2018-08-08 08:47:27.902 DEBUG 113896 --- [nio-5000-exec-5] org.hibernate.SQL                        : 
Hibernate: 
    delete 
    from
        relationship 
    where
        from_id=?
2018-08-08 08:47:27.902 TRACE 113896 --- [nio-5000-exec-5] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [VARCHAR] - [a1]
</pre>
</details>

Which has the unintended consequence of removing **all** relationships to `A1`, and not just the `Alpha` relationships.

We don't think this is a fault of Elide, but rather Hibernate not understanding this setup. The primary thing we're trying to solve is how to manually manage that relationship from our model. It sounds like we need to use the Lifecycle hooks to do that.

**Comment by aklish** [comment]
Thanks for the clarification - issue makes more sense to me now.  

Another option for overriding this behavior is to make a custom DataStore & DataStoreTransaction (you could just subclass the Hibernate equivalents).

When a relationship is deleted, the persistence layer can do something special here by overriding these methods:


```    
    /**
     * Elide core will update the in memory representation of the objects to the requested state.
     * These functions allow a data store to optionally persist the relationship if needed.
     *
     * @param relationTx - The datastore that governs objects of the relationhip's type.
     * @param entity - The object which owns the relationship.
     * @param relationName - name of the relationship.
     * @param newRelationships - the set of the added relationship to the collection.
     * @param deletedRelationships - the set of the deleted relationship to the collection.
     * @param scope - contains request level metadata.
     */
    default void updateToManyRelation(DataStoreTransaction relationTx,
                                      Object entity,
                                      String relationName,
                                      Set<Object> newRelationships,
                                      Set<Object> deletedRelationships,
                                      RequestScope scope) {
    }

    /**
     * Elide core will update the in memory representation of the objects to the requested state.
     * These functions allow a data store to optionally persist the relationship if needed.
     *
     * @param relationTx - The datastore that governs objects of the relationhip's type.
     * @param entity - The object which owns the relationship.
     * @param relationName - name of the relationship.
     * @param relationshipValue - the new value of the updated one-to-one relationship
     * @param scope - contains request level metadata.
     */
    default void updateToOneRelation(DataStoreTransaction relationTx,
                                     Object entity,
                                     String relationName,
                                     Object relationshipValue,
                                     RequestScope scope) {
    }
```  
Elide code however still manipulates the collection in memory (and if that collection is a proxy, Hibernate may still generate some SQL that might not be what you intend).

**Comment by aklish** [comment]
Closing the issue.  Reopen if this is still a problem.
