### ISSUE TITLE
JPA configuration

### ISSUE THREAD

**Issue by tbo-axelor** [yahoo/elide#686]
is it possible to use persistence.xml instead of hibernate.cfg.xml ??

**Comment by aklish** [comment]
It is possible to use it.

You have to use 
https://github.com/yahoo/elide/blob/master/elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateEntityManagerStore.java

Here is an example in the integration tests where it configures the entity manager factory to look for a persistence unit named "elide-tests":

https://github.com/yahoo/elide/blob/master/elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/datastores/hibernate5/HibernateEntityManagerDataStoreSupplier.java#L68   

That in turn is bundled here:
https://github.com/yahoo/elide/blob/master/elide-integration-tests/src/test/resources/META-INF/persistence.xml

**Comment by clayreimann** [comment]
Or, in `elide-standalone` you can override the `getHibernate5ConfigPath` to reference your `persistence.xml` file

**Comment by tbo-axelor** [comment]
hii @clayreimann ,
i tried override getHibernate5ConfigPath but it is not working.override method like

@Override
    public String getHibernate5ConfigPath() {
        return "./src/main/resources/META-INF/persistence.xml";
    }

**Comment by tbo-axelor** [comment]
thanks @aklish  for replay,
i fix my issue. so once again thanks
