### ISSUE TITLE
Bulk update response data has null values instead resource representations

### ISSUE THREAD

**Issue by vmironichev** [yahoo/elide#694]
I'm using json patch extension for making bulk updates, which works fine, but my issue is that response code is HTTP 200 and it contains null values for the data instead of updated resource representations. I think this is due to internal response merging mechanism, since updates are happening per resource and initially response code is HTTP 204 with no data, but during populating resource responses, they are merged into array and response code is overridden with HTTP 200. Since data store transaction.save method returns void, there is no data to populate in response.  Is it possible to fix this?

Please let me know if you need more information.

Thank you,
Valeriy
  
```
curl -X PATCH \
  https://api-host/api/v1/someresource \
  -H 'Accept: application/vnd.api+json; ext=jsonpatch' \
  -H 'Content-Type: application/vnd.api+json; ext=jsonpatch' \
  -d '[
    {
        "op": "replace",
        "path": "/1",
        "value": {
            "id": "2",
            "type": "someresource",
            "attributes": {
                "status": "CLOSED"
            }
        }
    },
    {
        "op": "replace",
        "path": "/2",
        "value": {
            "id": "2",
            "type": "someresource",
            "attributes": {
                "status": "CLOSED"
            }
        }
    }
]'
 
 
## Response
HTTP 200 OK
[
    {
        "data": null
    },
    {
        "data": null
    }
]
```

**Comment by aklish** [comment]
Don't have plans to address this as it is inline with JSON-API.
