### ISSUE TITLE
DataStoreTransaction Generics

### ISSUE THREAD

**Issue by jstemen** [yahoo/elide#698]
It would be handy if the DataStoreTransaction interface supported generics instead of simply returning, and operating on, Object types.  I've made a number of custom DataStoreTransaction implementations that only operate on specific types.  I'd like to restrict the method signatures to only operate on my expected types, but I can't do that because the interface only applies to the Object type.

**Comment by aklish** [comment]
Yes.  Agreed.  We had considered doing this when we moved to Elide 3.0 but I can't remember why we didn't.  In any event, we'll have to wait for a major release since this is a core interface.
