### ISSUE TITLE
how to provide diffrenet url for both jsonapi and graphql 

### ISSUE THREAD

**Issue by tbo-axelor** [yahoo/elide#702]
public class ElideResourceConfig extends Application {
	
	@Override
	public Set<Object> getSingletons() {
				
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("graphql-pu");
		EntityManager em = emf.createEntityManager();
		DataStore dataStore = new HibernateEntityManagerStore(em, true, ScrollMode.FORWARD_ONLY);
		
		EntityDictionary dictionary = new EntityDictionary(Collections.emptyMap());
		Elide elide = new Elide(new ElideSettingsBuilder(dataStore)
				.withEntityDictionary(dictionary)
				.withAuditLogger(new Slf4jLogger()).build());
		
		Set<Object> set = new HashSet<>();
		set.add(new JsonApiEndpoint(elide, v -> null));
		set.add(new GraphQLEndpoint(elide, v -> null));
		return set;
	}

}

this is ma ElideResourceConfig and i want access with diffrent url like
for json api
GET http://localhost:8080/projectName/api/contact

for graphql 
POST http://localhost:8080/projectName/graphql

**Comment by DennisMcWherter** [comment]
Hi, @tbo-axelor did this fix your issue?
