### ISSUE TITLE
Adding triggers before population the EntityDictonary

### ISSUE THREAD

**Issue by axel1200** [yahoo/elide#703]
I added triggers before I populated the entity dictionary and that does not work apparently. 
So first 
```entityDictionary.bindTrigger(BanInfo.class, OnCreatePostCommit.class, banInfoPostCreateListener);```
and then
```
new Elide(new ElideSettingsBuilder(springHibernateDataStore)
      .withJsonApiMapper(new JsonApiMapper(entityDictionary, objectMapper))
      .withAuditLogger(extendedAuditLogger)
      .withEntityDictionary(entityDictionary)
      .withJoinFilterDialect(rsqlFilterDialect)
      .withSubqueryFilterDialect(rsqlFilterDialect)
      .build())
```
It would be good to either

- [ ] throw an Exception

- [ ] to add this to the introduction guide(http://elide.io/pages/guide/02-data-model.html)

-  [ ] or to the java doc.

Or even better all of it 😄

**Comment by axel1200** [comment]
https://github.com/yahoo/elide/blob/e0c54778e572f1be9de19de84f7a730133be00d2/elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java#L1019 One could check if ppl define a trigger on an Empty binding and throw an Exception in that case because they are definitely doing something wrong then

**Comment by aklish** [comment]
Agreed.  We had a similar issue with initializers and fixed by binding the entity explicitly if the entity was not yet bound:

https://github.com/yahoo/elide/pull/524/files

We could do something along the same lines here.

**Comment by axel1200** [comment]
sounds good
