### ISSUE TITLE
Query Parameters length exceed

### ISSUE THREAD

**Issue by ThreefLi** [yahoo/elide#705]
I query a list of entities with their uuids but it return a error response like this:
![image](https://user-images.githubusercontent.com/18640500/45612796-baffff00-ba96-11e8-88e5-1b916771bb38.png)
this is because  the max length of url  the GET method support is only 4k,can elide support the POST METHOD ? OR is there any way to fix it out?

**Comment by clayreimann** [comment]
This actually came up internally fairly recently. A header was the most promising option, however it’s not completely robust since headed length is an implementation detail of any server or proxy between an Elide instance and the client 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clayreimann** [comment]
@ThreefLi URL length may also be a configurable value in either nginx or your servlet container technology 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ThreefLi** [comment]
thank you for your suggestion,but adjusting the configuration is not a elegant way for me because with the system grows,the url will be much longer and it is difficult for my team to decise the length;i think it is neccesary to support the post method or sending params with header.

**Comment by DennisMcWherter** [comment]
Depending on how large the request becomes, as @clayreimann said, the headers will ultimately suffer from the same issue. 

Any issues with the meta-block option? This would at least avoid any non-obvious server limits. Even though it's non-standard JSON-API so is the filter header (thus, most clients would need to adapt for large filter queries anyway). Thoughts?

**Comment by aklish** [comment]
Closing this issue.  This can be solved by using GraphQL instead of JSON-API.
