### ISSUE TITLE
[Field level annotations] @Id in superclass shown as "null" in relationships

### ISSUE THREAD

**Issue by Brutus5000** [yahoo/elide#710]
Hey there, I'm still trying to migrate our application to field level annotations.
Since we fixed the @Id detection in superclasses I now run into a new issue:

For all my entities that use my AbstractEntity superclass with the @Id annotation the relationship id is now resolved as "null". Entities that habe the @Id annotation in their own class are not affected.

Example:
```
{
    "data": [
        {
            "type": "map",
            "id": "1",
            "attributes": {
                "averageReviewScore": 0,
                "battleType": "skirmish",
                "createTime": "2018-10-05T21:08:29+02:00",
                "displayName": "SCMP_001",
                "mapType": "FFA",
                "numberOfReviews": 0,
                "updateTime": "2018-10-05T21:08:29+02:00"
            },
            "relationships": {
                "author": {
                    "data": {
                        "type": "player",
                        "id": "null"
                    }
                },
                "latestVersion": {
                    "data": {
                        "type": "mapVersion",
                        "id": "null"
                    }
                },
                "statistics": {
                    "data": {
                        "type": "mapStatistics",
                        "id": "1"
                    }
                },
                "versions": {
                    "data": [
                        {
                            "type": "mapVersion",
                            "id": "null"
                        }
                    ]
                }
            }
        }
    ]
}
```

MapStatic entitiy has @Id on itself.
All other entities have it in their superclass.

**Comment by aklish** [comment]
Could you make a failing test case?  I eyeballed the code - but didn't see anything obvious.

**Comment by aklish** [comment]
@Brutus5000 I started to investigate.  It looks like I failed to notice that your original IT test wasn't running.  This PR gets that working and fixes a bug (although I think there maybe a better way to do this) for setting private fields from inherited classes.  Can you rebase your test PR on this [PR](https://github.com/yahoo/elide/pull/712)?  Thanks.

**Comment by aklish** [comment]
I believe this is now fixed.
