### ISSUE TITLE
Support life cycle hooks within the Entity class for entities with field access

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#729]
Currently, if an Elide entity is using field level access (`@Id` annotates a field), Elide will not register life cycle hooks that are defined within the entity because they are functions.

A workaround is to mark them as `@ComputedAttribute` and `@Exclude` but this is ugly.

**Comment by DennisMcWherter** [comment]
Closed with https://github.com/yahoo/elide/pull/731/files?
