### ISSUE TITLE
entity with generic type field

### ISSUE THREAD

**Issue by d31m07y1988** [yahoo/elide#733]
If entity has generic parameterized type field, elide create wrong mapping.

for parameterized type field, elide maps to java.lang.Object.

And on entityBinding we'll get IllegalArgumentException because I haven't entity class Object.

It happen's because getFieldType return class by getType() and getReturnType() methods, which return Object for generic types.

**Comment by clayreimann** [comment]
Thanks for the bug report, could you provide a small example that reproduces the issue? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d31m07y1988** [comment]
> Thanks for the bug report, could you provide a small example that reproduces the issue?
> 
> Sent with [GitHawk](http://githawk.com)

https://github.com/d31m07y1988/elide_bug

**Comment by aklish** [comment]
Created a fix that might work.  I need to add some tests, but feel free to try it.

**Comment by d31m07y1988** [comment]
any work on merging PR?

**Comment by aklish** [comment]
Yes.  Was waiting on new jsonapi test dsl to add some IT tests.  I hope to
add IT tests this week.
