### ISSUE TITLE
Elide security layer implementation

### ISSUE THREAD

**Issue by The-Zombie-Horde** [yahoo/elide#750]
I am using elide to expose the entity something like /book/{id}. We have 2 way ssl implemented. How to  integrate elide security layer so that elide security permissions tags can be used. We have 2 way ssl handshake using x.509 certificate.

**Comment by aklish** [comment]
Assuming you are using the JAX-RS servlet to expose Elide, you would write a JAX-RS  `ContainerRequestFilter` which extracts the CN from your X509 cert and maps that to a `SecurityContext`.  

You do that in a method like:

```    @Override
    public void filter(ContainerRequestContext containerRequestContext) throws IOException {
         SecurityContext originalSecurityContext = containerRequestContext.getSecurityContext();
         containerRequestContext.setSecurityContext(new SecurityContext() {

         ...
```

Make sure you are using the latest version of Elide (which passes the User object as the SecurityContext by default).  Otherwise there is an extra step.

**Comment by The-Zombie-Horde** [comment]
I was looking at your documentation of elide framework and they are old and hence wanted to confirm with you. 

Is it via com.yahoo.elide.resources.JsonApiEndpoint that SecurityContext extracted from above step will be sent to JsonApiEndpoint ?

**Comment by aklish** [comment]
You don't have to use the provided JAX-RS endpoints - but you would need to create something equivalent to them.

I've hopefully addressed the documentation issue here:

https://github.com/yahoo/elide-doc/pull/77

**Comment by The-Zombie-Horde** [comment]
Thanks a million! Let me take a look and get back to you if any issue.

**Comment by aklish** [comment]
I'm not totally following the question although there is another pull request for a proper Jpa DataStore that's in review:

https://github.com/yahoo/elide/pull/747

**Comment by aklish** [comment]
Closing this issue since the documentation has been merged.
