### ISSUE TITLE
Make RSQL Filter Default

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#776]
.withJoinFilterDialect(new RSQLFilterDialect(dictionary))

should be the default in Elide 5.0

**Comment by nemoLx** [comment]
I vote for this as I got very confused when trying to use filters based on elide.io documentation, which is based on RSQL, while not realizing RSQL need to be added manually via settings.

Also could you please elaborate on the difference between joinFilterDialect and SubqueryFilterDialect? I had to add RSQL to both for filter in query params to work.

**Comment by aklish** [comment]
Make RSQL standard will be fixed in 4.4.1 release (this week).  

Documentation for JoinFilterDialect was removed sometime ago.  You can read about the distinction here:

https://github.com/yahoo/elide-doc/blob/f4d6668bfaba5d749360a3c619df7b100f0fd377/pages/guide/06-filters.md

Check out the difference between _disjoint_ and _joined filters_.  

While Elide still supports joined filters, it is currently an undocumented feature because there are some limitations to it (that is why the documentation was removed).

**Comment by aklish** [comment]
Fixed in 4.4.1
