### ISSUE TITLE
Allow access to resources as JPA entities in Elide response

### ISSUE THREAD

**Issue by nemLx** [yahoo/elide#789]
In Elide's response object today, we are working with a JSON-API string and a response code. We customized the Elide class to at least get the JsonApiDocument back. But it would nice to have access to the JPA entities directly, so we could attach our own serialization and transport layer.

**Comment by aklish** [comment]
Are you using JSON-API at all - or are you leveraging Elide purely for its security model?

**Comment by aklish** [comment]
Closing for lack of response.
