### ISSUE TITLE
Support for BigDecimal in GraphQL API

### ISSUE THREAD

**Issue by arpradhan** [yahoo/elide#812]
Hello, our team would like to enable the GraphQL on our Elide project, but one of our models has a BigDecimal field which is not supported in Elide. 

Would it be possible to add BigDecimal support in GraphQLConversionUtils#classToScalarType?
https://github.com/yahoo/elide/blob/b76f50409c253cb18f6ace450e3eae42e123da37/elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java#L61

It appears that java-graphql has support for BigDecimal: https://github.com/graphql-java/graphql-java/blob/1e12da93a692b8fff549e417906c899c9bf21345/src/main/java/graphql/Scalars.java#L528

I can make a PR to add this change if it helps.

**Comment by aklish** [comment]
Happy to review the PR if you want to submit one.  It looks like this should be fairly straightforward.
