### ISSUE TITLE
Customize Predicate JPQL Generation

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#815]
# Problem Statement

There are several scenarios where it would be useful to have more control over the JPQL generated for a given filter predicate.  Examples:
1. A database table has a FULLTEXT index enabled on a column that would benefit from different syntax than ```LIKE %value%'```.
2. Elide uses lowercase to perform case-insensitive search.  Other parts of the application may use uppercase for the same purpose.  These arbitrary implementation differences can prevent the use of a single database index over the column in question.

# Solution

The JPA DataStore can leverage a new functional interface that maps a Predicate to equivalent JPQL.

```java

@FunctionalInterface
public interface JPQLPredicateGenerator {
    String generate(String columnAlias, List<FilterParameter> parameters);
} 
```

These can be registered with the HQLFilterOperation by Predicate operator.  Once registered, the generator will override the default JPQL generation for that operator.
 
```java
public static void registerPredicateGenerator(Operator op, JPQLPredicateGenerator generator);
```
  
They can also be registered by Predicate operator, entity class, and field name.  Once registered, the generator will only be called for Predicates with a matching operator and columnAlias.  This will allow column specific JPQL generation.
  
```java
public static void registerPredicateGenerator(Operator op, Class<?> entityClass, String fieldName, JPQLPredicateGenerator generator);
```

**Comment by Brutus5000** [comment]
From solution outline it sounds like it should be possible to register a generator either for an operator, a class or a field.
Looking at the method signature it looks like it allows any combination (with or without nullable parameters). If this is the case, it would raise questions regarding the order in which the generators are selected. If this is not desired, then maybe the method should just be overloaded once per parameter (Operator, Class, Field)?

**Comment by aklish** [comment]
The intent is that a generator is registered either:

1. For an operator.  This generator overrides the default JPQL generation globally for all instances of that operator.  This should be handy for the use case to swap insensitive operators to user `upper` instead of `lower`.
2. For an operator, class, and field.  This is to support the changing the operator only for a specific column of a specific database table.  The intended use is for full text indices on certain columns.

The precedence is that more specific overrides more generic.  A field level registration will override an operator only registration which in turn overrides the default behavior.
