### ISSUE TITLE
AggregationDataStore: Static Attribute Aggregation

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#818]
The AggregationDataStore needs a schema for each entity that:
- Specifies that an attribute is a metric
- Specifies that an attribute or relationship is a dimension
- Specifies that an attribute is a Data/Time column and supports grain.
- Specifies that an Attribute is a _friendlyName_ or human displayable column for that dimension.
- Specifies whether a dimension has small, medium, or large cardinality.

## Expected Behavior
New AggregationDataStore annotations should be created:

1. MetricAggregation
2. Cardinality
3. ComputedMetric
4. FriendlyName

### Examples
```java
@MetricAggregation(default = Sum.class, aggregations = {Max.class, Median.class})
```

```java
@ComputedMetric(expression = '(fieldA * fieldB) / 100')
```

```java
@Cardinality(size = MEDIUM)
```

```java
@FriendlyName
```

## Current Behavior
N/A

## Possible Solution
Elide calls `populateEntityDictionary` on each data store. 

The AggregationDataStore should only bind entities that have at least one `MetricAggregation` annotation.    For each entity bound, it should use the `EntityDictionary` to lookup other data store specific annotations and construct a schema object for that entity.  The schema will be used as foundational metadata for the store to perform its functions.

**Comment by QubitPi** [comment]
@aklish I'm working on it

**Comment by QubitPi** [comment]
@aklish Is `@Cardinality` is same thing as the cardinality in JPQL database? Do we simply trust user who will set whatever value it will be for `size`?

Could we have more background/business-background on the `@FriendlyName`? This helps me implement it.

**Comment by aklish** [comment]
@Cardinality is a new annotation that will have a value of SMALL, MEDIUM, or LARGE.  We trust the developer to set it.  The values should be an enum.  Also, let's rename `@ComputedMetric` to `@MetricComputation`.

**Comment by QubitPi** [comment]
Ok. Yeah enum is my choice, too
