### ISSUE TITLE
AggregationDataStore: Having Clause Support

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#819]
Filter expressions must be split into those that apply to metric aggregations (having clauses) and those that apply to dimensions (where clauses).

A single filter expression is passed to the datastore, but not all expression conjunctions (notably OR) can be split into a having and where clause in a meaningful way.

## Expected Behavior
An expression parser should throw an error whenever an illegal expression is encountered.  Here are examples of legal & illegal expressions.  Clauses prefixed with H are having clauses.  Clauses prefixed with W are where clauses.

### Legal
```
Expression: H1 AND W1 AND H2 
SQL: WHERE W1 HAVING (H1 AND H2)
```
```
Expression: (H1 OR H2) AND W1
SQL: WHERE W1 HAVING (H1 OR H2)
```

### Illegal
* H1 OR W1
* (W1 AND H1) OR W2

The parser should either:

- Split the filter expression into a *where* expression and a *having* expression.
- Throw an exception

## Possible Solution
Create a visitor that will walk the `FilterExpression` abstract syntax tree and split the filter expression into where and having clauses.

Prior to walking the syntax tree, it should leverage the `FilterExpressionNormalizationVisitor` to transform expressions like:
`NOT (A AND B)` into `NOT A OR NOT B`

The visitor will be leveraged by the AggregationStore to construct the JPQL query.

## Context

https://github.com/yahoo/elide/issues/804

**Comment by aklish** [comment]
Instead of throwing an exception, the illegal combinations can be promoted to a having clause.

**Comment by QubitPi** [comment]
@aklish When we say `Instead of throwing an exception, the illegal combinations can be promoted to a having clause.`, do we secretly throw away any `WHERE` expression?
