### ISSUE TITLE
AggregationDataStore : RequestScope should include fields requested for a given entity load

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#823]
The Aggregation Data Store needs to know what attributes and relationships are being fetched so that it can construct a complete JPQL query.

While this information is available today for JSON-API (via the request headers and the list of sparse fields for a given entity model), this capability does not exist for GraphQL.

## Expected Behavior
A new field, *requestedSubgraph* will be set inside the requestScope each time `loadObjects` or `getRelationship` is called on the `DataStoreTransaction`.

This field will contains a nested map containing the entity relationship graph (entities, fields, and relationships to other entities) that is being requested starting at the current collection or entity that is being loaded.

## Possible Solution
Both JSON-API and GraphQL will require changes:

1. JSON-API can construct this graph from the `&include` and `&fields` query parameters.
2. GraphQL can look at the `SelectionSet` passed in the `DataFetchingEnvironment`.

## Context
https://github.com/yahoo/elide/issues/804

**Comment by QubitPi** [comment]
@aklish I assume `requestedSubgraph` will essentially be the same thing as `RequestScope.sparseFields`, right?

**Comment by QubitPi** [comment]
@aklish When, in the case of JSON-API, the graph can be constructed using `&include` and `&fields`, what will be the use of **setting the graph each time `loadObjects` or `getRelationship` is called on the `DataStoreTransaction`**?
