### ISSUE TITLE
Revamp Security Backend

### ISSUE THREAD

**Issue by DeathByTape** [yahoo/elide#84]
Below is the proposal for revamping the Elide security backend. It will require *breaking* changes to the public-facing API and-- consequently-- will be rolled up into **Elide 2.0**. This is a working document. That is, I will keep this up-to-date with developments on progression plans.

# Current Limitations

Due to the current design of the security system, Elide faces problematic security limitations. These problems are not security vulnerabilities, but they disallow expression of certain security constraints. Moreover, they can also lead to confusion which is a show-stopper for effective security. That is, the best security rules are simple and clear making them less error-prone; the system executing these rules should also be clear in nature.

  1. **Fine-Grained Update Control.** At the moment, it is not feasible to specify controls on Updates based on type of modification. For instance, if a user should be able to add objects to a list but disallowed to remove any, this cannot be effectively expressed in the current system. As it stands, we broadly check "update" permissions. In our case, an update of empty list effectively removes all elements within a list.
  1. **Check Execution Reasoning.** In our current model, authorization check execution flow is determined dynamically at runtime based on a multitude of factors. In other words, the current system is trying to be "smart." Effectively, this makes reasoning about security checks far more difficult based upon when they would/should be executed.
  1. **Inability to control short-circuiting.** It is common practice in programming to perform a couple of cheap checks before an expensive one. If any of these cheaper checks fail, then you can avoid computing the expensive check. In our current system, the lack of control on check execution does not guarantee that such a thing can be done repeatedly.
  1. **`UserCheck`'s are tightly-coupled with security.** The notion of a `UserCheck` in practice is not strictly for security, but more of an optimization instead. As a result, their tight-coupling to the security system makes them confusing to work with and limits the expressiveness of the system.

# Solution

Below I have outlined the current state of our proposed solution. This solution comes from discussions with multiple sources and I suspect will further evolve through continued discourse before it is fully implemented. Again, I will keep this section up-to-date with the latest information as it's decided.

  1. **Fine-grained modification support.** We will update the `Check` interface to support `Changesets` for `Update` requests. In particular, the `Changeset` object (pseudo-code outlined below) will become a parameter describing the proposed modification to an object. This will allow `Check` writers to verify the type of data modifications permitted. This solves the problem of **Fine-Grained Update Control** mentioned above.
  1. **Operation vs. Commit Execution.** We will introduce two new concepts known as *operation checks* and *commit checks*. In particular, **operation** checks are intended to be run immediately upon request. That is, finalized data is not required to fully validate the security of this data. On the other hand, **commit** checks are expected to run only immediately before a transaction commit to the datastore. These checks often require the data to be fully manipulated and are run on the exact set of data which is about to be stored in the datastore. Providing checks at these granularities solve both issues of **check execution reasoning** and the ability to **control short-circuiting** since the developer now has direct control over the check execution points (i.e. operation checks can be executed to short-circuit expensive commit checks, for instance).
  1. **Separating `UserCheck`.** We will elevate the `UserCheck` interface to a first-class citizen. Surfacing a new annotation and providing independent control from the general object security will make things less confusing in the future.

## Proposed Check Interface Update
Below is the primary check interface:

```java
public interface Check<T> {
  /**
   * This method will be called on operation-based checks since object data is not
   * necessarily finalized at this point
   */
  public boolean ok(RequestScope rs, Optional<Changeset<F>> cs);

  /**
   * This method will be called on commit-based checks since all data is finalized.
   */
  public boolean ok(T obj, RequestScope rs, Optional<Changeset<F>> cs);
}
```

However, since all permission types don't necessarily *commitChecks* (i.e. `ReadPermission` and `DeletePermission`, for instance), the _commitChecks_ will be run as _operationChecks_ in these scenarios joined by an and clause.

## Refactoring of Security Code

These changes will include larger internal refactoring of the security. To simplify the logic and shared-state, I am suggesting a simpler `PermissionManager`. A `PermissionManager` instance will be bound to a particular `RequestScope`. Below is the proposed interface for calling into the `PermissionManager`

```java
public class PermissionManager {

  public void checkPermissions(Class<? extends Check>[] checks, boolean isAny, PersistentResource<?> resource);

  public void checkPermissions(Class<? extends Check>[] checks, boolean isAny, PersistentResource<?> resource, ChangeSpec<?> changeSpec);

  public void executeCommitChecks();
}
```

## Separation of Concern for User Checks

The current concept of `UserCheck` is intended for **optimization** (i.e. short-circuit DB load based on user properties) rather than **security**. As a result, we should separate these concepts. I propose that the `UserCheck` interface remain the same (except, perhaps, no longer making it a direct descendant of the `Check` interface) but we move it to another package (perhaps an `optimization` package or similar?). This may call for a new annotation. My proposal is the `@UserPermission` annotation. This will be very similar to existing checks, however, `UserPermission` will first be evaluated. If it does not evaluate to true, nothing else is checked and access it omitted to the full object. The `@UserPermission` annotation will apply **strictly** at the entity-level and there **will not be** field-level support for this annotation.

## Pseudo-code for Changeset object
```java
public class Changeset<T> {
  public String fieldName; // The modified field on the object
  public T added; // The serialized form of the updated field value
  public T removed; // The serialized form of the original field value
}
```

# FAQ

  1. **Will this break my existing code?** Yes. In particular, we suspect it will affect all custom permission checks as we intended to update the interface. That being said, we will be performing a major version bump when this feature is completed.
  1. **Am I insecure on Elide 1.x?** In short: not that we are aware of. While this change affects the security backend of Elide, it is not prompted by any inherent vulnerabilities in our current approach with Elide 1.x. As a result, your current services should not be adversely affected. However, it is expected that all future updates will be applied to future versions of Elide and we suggest upgrading to stay current.

**Comment by aklish** [comment]
Good overview.  I don't think the Changeset should have serialized fields, but rather the actual type being changed.

**Comment by DeathByTape** [comment]
@aklish I've updated the main doc with this correction

**Comment by clayreimann** [comment]
Perhaps the modes should be *Immediate* and *Deferred* to reflect that they are executed at the time the operation has been requested or once the data model has settled.

**Comment by jkusa** [comment]
I am in favor of naming the *check modes* so that they give some context to **when** (in the request lifecycle) they will be executed.

Perhaps the names could be:
 - `operationCheck` - executes during the entity operation phase, when operations are performed on entities (fetch, create, update, etc)
 - `commitCheck` - executes during the commit phase, after all entity operations are complete

**Comment by DeathByTape** [comment]
I feel `operationCheck` and `commitCheck` are clearer in the context of the code. Anyone have strong objects to these?

**Comment by DeathByTape** [comment]
@aklish and I spoke offline yesterday. I have amended the docs with some thoughts from our discussion. Please review.
