### ISSUE TITLE
Support PeriodOverPeriod in Aggregation DataStore

### ISSUE THREAD

**Issue by hellohanchen** [yahoo/elide#853]
In aggregation data store, if a fact table support aggregation on a datatime field, it might be valuable to support periodOverPeriod analysis. For example the following query
```
Sales in Q1 for years 2015~2019
```
By periodOverPeriod analysis, we can calculate Q1 sales growth rate of years 2016~2019.

## Design Behavior
- Supports period in two different period representations
  - Time window, e.g. Q1 = from Jan01-00-00-00 [inclusive] to Apr-01-00-00-00 [exclusive]
  - Period with duration, e.g. 3 months = consecutive 3-month windows from a **given time**
- Supports **PARTITION BY** other dimension fields
- Supports multiple aggregation/computation at the same time
- Supports computation of periodOverPeriod rate

### Example Java Class: PlayerStat
```java
public class PlayerStat {
  @Id
  private long statId;

  @ManyToOne
  private Player player;

  @MetricAggregation(default = SUM.class, aggregations = {MAX.class, Median.class})
  private long score;

  @MetricAggregation(default = SUM.class, aggregations = {MAX.class, Median.class})
  private long time;

  @Temporal
  @AggregationPeriod(timeGrain = Daily, window = YES, duration = YES)
  private date gameDate;

  // 1. this field would never be persisted in the database
  @AggregationPeriodOverPeriod
  @Exclude
  private Map<String, Float> overPreviousPeriod;

  // 1. this field would never be persisted in the database
  @AggregationMap
  @Exclude
  private Map<String, BigDecimal> aggregations;

  @ManyToOne
  private Country country;
}
```
#### New annotation: AggregationPeriod
This annotation should be put on a timestamp field that can be used in period aggregation.
- Must be applied to a field with ISO8601 format
- timeGrain is the most precise time grain supported by this field
- **window** whether this fields support time window representation
- **duration** whether this fields support period duration representation
```java
@AggregationPeriod(timeGrain = Daily, window = YES, duration = YES)
```

#### New annotation: AggregationPeriodOverPeriod
This annotation is a place holder for periodOverPeriod results, should be applied on a field that would not be persisted in the database.
```java
@AggregationPeriodOverPeriod
```

### Sample Request (time window presentation)
```graphQL
{
  PlayerStats (filter: "gameDate IN ['2018', '2019', '2020'] AND country == 'USA' AND aggregations.totalScore > 300") {
    edges {
      node {
        aggregations {
          edges {
            node {
              totalScore: score (aggregation: "SUM")
              maxTime: time (aggregation: "MAX")
            }
          }        
        }
        player {
          edges {
            node {
              name
            }
          }
        }
        gameDate (start: "DT1M", end: "DT2M")
        overPreviousPeriod {
          edges {
            node {
              totalScore
            }
          }
        }
        country {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}
```
**This query is trying to get the USA player with total score > 300 and max game time for games from Jan-01 00:00:00 (inclusive) to Feb-01 00:00:00 (exclusive), and calculate the growth rate of total score over recent 3 years.**
**DT1M** is just a dummy representation of January, we can change the format of this later.
Since the window is *monthly* level, a *daily* fact table can support this query, and the time step is *yearly*.
I think it makes sense to use *yearly* as the largest time step. 

#### Corresponding MySQL
If the database supports DATE_FORMAT and STR_TO_DATE or equvialent functions, we can push the aggregation down to the database. **This is just a design idea, I don't know how to convert this into JPQL**.
```MySQL
SELECT 
  tb1.score AS totalScore,
  tb1.time AS maxTime,
  tb1.player AS player,
  tb1.country AS country,
  tb1.gameDate AS gameDate,
  -- for the first period, there is not periodOverPeriod value
  IF(tb2.score IS NULL, NULL, tb1.score / tb2.score) AS overPreviousPeriod
FROM -- aggregated table represents current values
  (
    SELECT 
      SUM(score) AS score, 
      MAX(time) AS time, 
      player, 
      country, 
      -- convert the truncated timestamp (string) back to timestamp type
      STR_TO_DATE(DATE_FORMAT(gameDate, '%y'), '%y%m%d%H%i%s') AS gameDate
    FROM 
      playerStats 
    GROUP BY 
      player, 
      country, 
      -- truncate the timestamp to time step level and used as group by key
      DATE_FORMAT(gameDate, '%y')
    WHERE 
      -- truncate the timestamp to time window level
      -- start='0101000000' here
      DATE_FORMAT(gameDate, '%m%d%H%i%s') >= start 
        AND 
      -- end='0201000000'
      DATE_FORMAT(gameDate, '%m%d%H%i%s') < end
        AND -- dimension filter can be applied in the inner SQL
      country = 'USA';
  ) tb1
LEFT JOIN -- the second table is the same table, just used to find the preivous period value
  (
    SELECT 
      SUM(score) AS score,
      MAX(time) AS time,
      player, 
      country, 
      STR_TO_DATE(DATE_FORMAT(gameDate, '%y'), '%y%m%d%H%i%s') AS gameDate
    FROM 
      playerStats 
    GROUP BY 
      player, 
      country, 
      DATE_FORMAT(gameDate, '%y')
    WHERE 
      DATE_FORMAT(gameDate, '%m%d%H%i%s') >= start 
        AND 
      DATE_FORMAT(gameDate, '%m%d%H%i%s') < end
        AND
      country = 'USA';
  ) tb2
ON -- dimension attributes needs to be the same
  tb1.player = tb2.player 
    AND 
  tb1.country = tb2.country
    AND -- different of windows should be 1 time step
  tb2.gameDate = tb1.gameDate - 1 YEAR INTERVAL
WHERE -- aggregation and period filter can only be applied after aggregation is finished
  tb1.score > 300 
    AND
  DATE_FORMAT(tb1.gameDate, '%y') IN ['2018', '2019', '2020'];
```

#### Expected Response
```Json
{
  "PlayerStats": {
    "edges": [
      { 
        "node": {
          "aggregations": {
            "edges": [
              {
                "node" : {
                  "totalScore": 500,
                  "maxTime": 60
                }
              }
            ]
          },
          "player" : {
            "edges": [
              {
                "node": {
                  "name": "player1"
                }
              }
            ]
          },
          "gameDate": "2018-01-01 00:00:00",
          "overPreviousPeriod": {
            "edges": [
              {
                "node" : {
                  "totalScore": ""
                }
              }
            ]
          },
          "country": {
            "edges": [
              { 
                "node": {
                  "name": "USA"
                }
              }
            ]
          }
        }
      },
      { 
        "node": {
          "aggregations": {
            "edges": [
              {
                "node" : {
                  "totalScore": 1000,
                  "maxTime": 70
                }
              }
            ]
          },
          "player" : {
            "edges": [
              {
                "node": {
                  "name": "player1"
                }
              }
            ]
          },
          "gameDate": "2019-01-01 00:00:00",
          "overPreviousPeriod": {
            "edges": [
              {
                "node" : {
                  "totalScore": "2.0"
                }
              }
            ]
          },
          "country": {
            "edges": [
              { 
                "node": {
                  "name": "USA"
                }
              }
            ]
          }
        }
      }
    ]
  }
}
```

### Sample Request (period duration)
```GraphQL
{
  PlayerStats (filter: "gameDate IN ['201902', '201811', '201808'] AND country == 'USA' AND aggregations.totalScore > 300") {
    edges {
      node {
        aggregations {
          edges {
            node {
              totalScore: score (aggregation: "SUM")
              maxTime: time (aggregation: "MAX")
            }
          }        
        }
        player {
          edges {
            node {
              name
            }
          }
        }
        gameDate (start: "DT2018Y08M", duration: "P3M")
        overPreviousPeriod {
          edges {
            node {
              totalScore
            }
          }
        }
        country {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}
```
**This query is trying to get the USA players with total scores > 300 and their max game time in 3 consecutive months from Aug 2018 (inclusive)**

#### Corresponding MySQL
```MySQL
SELECT 
  tb1.score AS totalScore,
  tb1.time AS maxTime,
  tb1.player AS player,
  tb1.country AS country,
  -- this is the start date of each period
  -- duration = 3 here
  -- now = 201808 here
  STR_TO_DATE(PERIOD_ADD(now, duration * tb1.periods), '%y%m') AS gameDate,
  IF(tb2.score IS NULL, NULL, tb1.score / tb2.score) AS overPreviousPeriod
FROM -- aggregated table represents current values
  (
    SELECT
      SUM(score) AS score, 
      MAX(time) AS time, 
      player, 
      country,
      -- get the number of periods between gameDate and start time
      PERIOD_DIFF(DATE_FORMAT(gameDate, '%y%m'), start) / duration AS periods
    FROM 
      playerStats 
    GROUP BY 
      player, 
      country, 
      -- group by the number of periods between gameDate and start time
      PERIOD_DIFF(DATE_FORMAT(gameDate, '%y%m'), start) / duration
    WHERE -- dimension attributes filter
      country = 'USA';
  ) tb1
LEFT JOIN -- aggregation table represents previous values
  (
    SELECT
      SUM(score) AS score, 
      MAX(time) AS time, 
      player, 
      country, 
      PERIOD_DIFF(DATE_FORMAT(gameDate, '%y%m'), start) / duration AS periods
    FROM 
      playerStats 
    GROUP BY 
      player, 
      country, 
      PERIOD_DIFF(end, DATE_FORMAT(gameDate, '%y%m')) / duration
    WHERE
      country = 'USA';
  ) tb2
ON -- dimension attributes need to be the same
  tb1.player = tb2.player
    AND 
  tb1.country = tb2.country
    AND  -- shift duration window for 1
  tb2.periods = tb1.periods - 1
WHERE -- aggregation and period filter can only be applied after aggregation is finished
  tb1.score > 300 
    AND
  PERIOD_ADD(start, duration * tb1.periods) IN [201902, 201811, 201808];
```

#### Expected Response
```Json
{
  "PlayerStats": {
    "edges": [
      { 
        "node": {
          "aggregations": {
            "edges": [
              {
                "node" : {
                  "totalScore": 500,
                  "maxTime": 60
                }
              }
            ]
          },
          "player" : {
            "edges": [
              {
                "node": {
                  "name": "player1"
                }
              }
            ]
          },
          "gameDate": "2018-08-01 00:00:00",
          "overPreviousPeriod": {
            "edges": [
              {
                "node" : {
                  "totalScore": ""
                }
              }
            ]
          },
          "country": {
            "edges": [
              { 
                "node": {
                  "name": "USA"
                }
              }
            ]
          }
        }
      },
      { 
        "node": {
          "aggregations": {
            "edges": [
              {
                "node" : {
                  "totalScore": 1000,
                  "maxTime": 70
                }
              }
            ]
          },
          "player" : {
            "edges": [
              {
                "node": {
                  "name": "player1"
                }
              }
            ]
          },
          "gameDate": "2018-11-01 00:00:00",
          "overPreviousPeriod": {
            "edges": [
              {
                "node" : {
                  "totalScore": "2.0"
                }
              }
            ]
          },
          "country": {
            "edges": [
              { 
                "node": {
                  "name": "USA"
                }
              }
            ]
          }
        }
      },
      { 
        "node": {
          "aggregations": {
            "edges": [
              {
                "node" : {
                  "totalScore": 1500,
                  "maxTime": 90
                }
              }
            ]
          },
          "player" : {
            "edges": [
              {
                "node": {
                  "name": "player1"
                }
              }
            ]
          },
          "gameDate": "2019-02-01 00:00:00",
          "overPreviousPeriod": {
            "edges": [
              {
                "node" : {
                  "totalScore": "1.5"
                }
              }
            ]
          },
          "country": {
            "edges": [
              { 
                "node": {
                  "name": "USA"
                }
              }
            ]
          }
        }
      }
    ]
  }
}
```

## Discussion
- Whether the expected behaviour is what we really want to support
- Need JPQL solutions for the queries
- Complex case like multiple tables with join clauses
- Whether supports multiple periodOverPeriod analysis in one query
- If the database doesn't support timestamp functions, the in-memory implementation of aggregation might be expensive.

**Comment by aklish** [comment]
The aggregation store (for now) will be limited to JPQL which has a very
limited syntax.  All the windowing must be done after the JPQL query (or we
have to switch to SQL which will be considerably more complex).

**Comment by aklish** [comment]
If there is only a single period over period metric that takes an argument,
it may not be possible to ask for two period over period metrics in the
same query.  It might be better to pin the period over period metric to
another metric in the annotation

**Comment by hellohanchen** [comment]
@aklish Do we have current JPQL implementation for aggregation store?
If we want to do the windowing in-memory, the aggregation might be slow when we have many partition keys/dimensions, but we can supports multiple periodsOverPeriods for sure.
We can have multiple fields with `@AggregationPeriodOverPeriod` annotation, e.g. `timePeriodOverPeriod` and `scorePeriodOverPeriod`. Or we can make that field a map type, and put the values into that map. The response might look like
```Json
"overPreviousPeriod" : {
  "score": "1.5",
  "time": "1.2"
}
```
But the map solution can't be pushed down to the database.

**Comment by aklish** [comment]
JPQL was the original plan as it simplifies joins and is portable across
sql dialects.  It also is simpler because we can deal with the entity model
instead of the underlying tables and columns

**Comment by hellohanchen** [comment]
We can just do aggregation in the database, and find a proper way to calculate period over period rate for all, in this example, `(player, country, gameDate)` combination.

**Comment by aklish** [comment]
Yes.  Aggregate in the dB.  We can assume a single time grain for
aggregations per query

**Comment by hellohanchen** [comment]
In that case I think as JPQL can't do nested select statement. We only need
- `@AggregationPeriod` annotation on time fields that support period analysis
- `@PeriodOverPeriodResult` annotation on a e.g. `Map<String, Float> overPreviousPeriod` field, that would be returned in json format showing period over period results for all requested aggregation
```Json
"overPreviousPeriod" : {
  "score": "1.5",
  "time": "1.2"
}
```
- Implementation to calculate period over period result in-mem, we can add `ORDER BY` in the generated JPQL. So that the result list would be sorted by all partition keys e.g. `(player, country, gameDate)`, we don't need to store the whole result list in a huge multi-level hash map. 
- Define the timeWindow and periodDuration syntax for representing period.
- Find a way to make truncate a timestamp field into the corresponding time window representation. Some thing like `DATE_FORMAT()` in MySQL. I think this can be done by java udf. **OR** we can make the `gameDate` field a string that represents ISO8601 format time. And then we use JPQL `substring()` function to truncate the date.

**Comment by aklish** [comment]
The only way to project a metric should be to explicitly request it in
graphql.  This consistency allows filters and sorting to work.  Rather than
have a map, each period metric should be its own entity attribute.

**Comment by jkusa** [comment]
>  @Temporal
>  @AggregationPeriod(timeGrain = Daily, window = YES, duration = YES)
> private date gameDate;

Would it make sense to remove the concept of aggregation from `@AggregationPeriod`  and just annotate properties of the temporal field?

**Comment by jkusa** [comment]
Does this design support the concept of requesting several "trend" metrics in a single request? Ex: from a daily grain column: `totalPoints`, `pointsYoY` (year over year), & `pointsMoM` (month over month)

**Comment by hellohanchen** [comment]
> Does this design support the concept of requesting several "trend" metrics in a single request? Ex: from a daily grain column: `totalPoints`, `pointsYoY` (year over year), & `pointsMoM` (month over month)

Currently, no. The totalPoints would be different for yearly grain and monthly grain.

**Comment by hellohanchen** [comment]
> > @TeMPOraL
> > @AggregationPeriod(timeGrain = Daily, window = YES, duration = YES)
> > private date gameDate;
> 
> Would it make sense to remove the concept of aggregation from `@AggregationPeriod` and just annotate properties of the temporal field?

Does `@temporal` support string representation of ISO8601 timestamp? If so, I think we can merge those two annotations.
