### ISSUE TITLE
Aggregation Store: Hydrate GraphQL Schema with parameterized attributes

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#890]
The Aggregation Store requires metrics and some dimensions to take arguments.  These arguments need to be:
1. Exposed in the GraphQL Schema
2. Added to the `EntityProjection` so that the Aggregation DataStoreTransaction can leverage them when buildings its queries.

## Possible Solution

The `EntityDictionary` should have new methods for adding arguments to attributes.

The `AggregationDataStore` should populate the dictionary with these attributes in the function `populateEntityDictionary`.   The store can leverage the new Schema class to determine which attributes to add.

For now, we should add the following attributes to the schema;
1. Metrics with the `@MetricAggregation` annotation should take a parameter for the name of the aggregation to compute.
2. Time based dimensions with `@Temporal` annotation should take grain and timeZone parameters.

This work should be based on the branch AddDataCollectionClassHierarchy that includes @QubitPi changes for GraphQL.

**Comment by QubitPi** [comment]
> This work should be based on the branch AddDataCollectionClassHierarchy that includes @QubitPi changes for GraphQL.

https://github.com/yahoo/elide/pull/896
