### ISSUE TITLE
Return 200 instead of 204 on update

### ISSUE THREAD

**Issue by DeathByTape** [yahoo/elide#93]
There has been expressed interest in returning a proper 200 OK code (with proper response body) upon updating instead of a 204 No Content. As far as I can tell, there are no technical limitations to us doing this at the moment. This is likely an artifact of an artificial limitation we encountered during our initial development.

That said, this should comply with the JSON API spec: http://jsonapi.org/format/#crud-updating-responses-200

**Comment by wcekan** [comment]
The spec is unclear on this point.  It says to respond with either 200 or 204 when the changes are applied.  However, always choosing 200 would simplify client processing.

**Comment by pokaru** [comment]
Hey William,

I think this issue came from one of my request.  Basically, what I'd like is for the updated object to be returned on updates.  We would like to sent our clients the updated object without having to make another rs call.

**Comment by QubitPi** [comment]
Can I pick up this one? Just make sure this feature is still needed

**Comment by aklish** [comment]
I think this should be OK to do, but we should have an option in Elide builder to enable this behavior.  Default should be what it does today so it won't break anyone's API.

**Comment by QubitPi** [comment]
OK, I will add the option, leave all tests unchanged, and add some new tests to test this option

**Comment by DeathByTape** [comment]
Done in #377, thanks @QubitPi
