### ISSUE TITLE
ElideStandalone should use H2 (by default), Spring boot, and spring security's secure headers.

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#953]
## Expected Behavior
We've had a lot of requests for Spring Boot over the years.  Elide Standalone should use spring boot.  Once spring is a dependency, it makes sense to pull in Spring Security so that we can leverage its secure headers configuration.

Also, it will be simpler to use H2 internally instead of mysql for setup of Elide Standalone.

**Comment by thaingo** [comment]
@rmihalko would you please give us some update on this?

**Comment by rmihalko** [comment]
@thaingo, work on this has not started yet. I am planning on getting started on this task this week. I'll provide an update once I get a good idea of how long this will take.

**Comment by aklish** [comment]
Update on this.  Our plan is to have maybe an example repo out in a week or two. 

We'll then create a new project called elide-spring where the common bits will live.

**Comment by aklish** [comment]
Here is an example repo:
https://github.com/aklish/elide-spring

I plan on folding this into Elide sometime this week.  The next release should have an elide-spring-boot artifact.
