### ISSUE TITLE
Support filtering by id

### ISSUE THREAD

**Issue by jkusa** [yahoo/elide#96]
Currently, you can not execute a GET request and filter entities by `id`. This case is especially useful when performing an filter with an `in` operator. For example, requesting `comments` where `id ` is `in` `[1,5,7,8]`.

**Comment by mcasperson** [comment]
+1

**Comment by DeathByTape** [comment]
I will probably start working at getting this and #97 in as soon as we finish up the reworked security. We should (hopefully) be closing that up this week.

In the meantime, if anyone has some spare cycles to send a PR on this, that's also welcome :)

**Comment by DeathByTape** [comment]
Fixed in https://github.com/yahoo/elide/pull/114
