### ISSUE TITLE
Support filtering by relationship fields

### ISSUE THREAD

**Issue by jkusa** [yahoo/elide#97]
Currently, you can not execute a GET request and filter entities by its relationship fields. 

**Example**: 

Given `Book` and `User` entities and `Book` has an `author` field that is a one-to-one to relationship to `User`.

I would like to request all `Books` where `author` is = `55`

or 

`myAwesomeElideInstance.com/books?filter[books.author]=55`

**Comment by mcasperson** [comment]
+1
This would be an amazing feature

**Comment by tonysan** [comment]
+1 it's more like a must have

**Comment by DeathByTape** [comment]
Looks like I should have some spare cycles to take a look at this now. I'm picking it up and hopefully will have an implemented solution soon!

**Comment by DeathByTape** [comment]
FYI: The PR is located here: https://github.com/yahoo/elide/pull/179

After review and iteration, this should go in soon.

**Comment by DeathByTape** [comment]
Changes have been merged. They will go out officially in version `2.0.8`
